Repository mesosphere/kommander-applications, pull requests merged in 2021-11, with the labels that each got.

#22 feat: create Ingress for Gitea
  services/gitea/4.1.1/defaults/cm.yaml
  services/traefik/10.3.0/defaults/cm.yaml
Labels: enhancement, ready-for-review

#21 fix: make clean install of Istio work again
  services/istio/1.9.1/helmrelease.yaml
  services/istio/1.9.1/helmrelease/helmrelease.yaml
  services/istio/1.9.1/istio-ca.yaml
  services/istio/1.9.1/istio-ca/istio-ca.yaml
  services/istio/1.9.1/istio-system-namespace.yaml
  services/istio/1.9.1/istio-system-namespace/istio-system.yaml
  services/istio/1.9.1/kustomization.yaml
  services/jaeger/2.21.0/jaeger.yaml
Labels: bug, ready-for-review

#23 Remove trailing dots in hostnames
  services/fluent-bit/0.16.2/defaults/cm.yaml
  services/grafana-loki/0.33.1/defaults/cm.yaml
  services/kommander-flux/0.17.2/templates/apps_v1_deployment_source-controller.yaml
  services/project-grafana-loki/0.33.1/defaults/cm.yaml
Labels: ready-for-review

#24 chore: Bump kubecost/centralized-kubecost to 0.20.0
  services/centralized-kubecost/0.20.0/centralized-kubecost.yaml
  services/centralized-kubecost/0.20.0/defaults/cm.yaml
  services/centralized-kubecost/0.20.0/defaults/kustomization.yaml
  services/centralized-kubecost/0.20.0/kustomization.yaml
  services/kubecost/0.20.0/defaults/cm.yaml
  services/kubecost/0.20.0/defaults/kustomization.yaml
  services/kubecost/0.20.0/kubecost.yaml
  services/kubecost/0.20.0/kustomization.yaml
Labels: ready-for-review

#25 fix: align with flux's upstream manifests
  services/kommander-flux/0.17.2/templates/apps_v1_deployment_source-controller.yaml
Labels: ready-for-review

#26 Revert "chore: Bump kubecost/centralized-kubecost to 0.20.0"
  services/centralized-kubecost/0.19.0/centralized-kubecost.yaml
  services/centralized-kubecost/0.19.0/defaults/cm.yaml
  services/centralized-kubecost/0.19.0/defaults/kustomization.yaml
  services/centralized-kubecost/0.19.0/kustomization.yaml
  services/kubecost/0.19.0/defaults/cm.yaml
  services/kubecost/0.19.0/defaults/kustomization.yaml
  services/kubecost/0.19.0/kubecost.yaml
  services/kubecost/0.19.0/kustomization.yaml
Labels: ready-for-review

#28 fix: re-add gitserver URL to list of prefixes to strip
  services/traefik/10.3.0/defaults/cm.yaml
Labels: ready-for-review

#30 fix: user correct ordering for prefix stripping
  services/traefik/10.3.0/defaults/cm.yaml
Labels: ready-for-review

#34 fix: Update centralized-kubecost cms
  services/centralized-kubecost/0.19.0/centralized-kubecost.yaml
Labels: ready-for-review

#33 fix: Remove hooks and cleanup jobs from centralized-kubecost/thanos
  services/centralized-kubecost/0.19.0/centralized-kubecost.yaml
  services/thanos/0.4.5/thanos.yaml
Labels: ready-for-review

#27 Fix: make reloader annotations point to the right traefik certificate
  services/dex-k8s-authenticator/1.2.8/defaults/cm.yaml
  services/dex/2.9.10/defaults/cm.yaml
  services/kube-oidc-proxy/0.2.5/defaults/cm.yaml
  services/traefik-forward-auth-mgmt/0.3.2/defaults/cm.yaml
Labels: ready-for-review

#35 fix: Typo, check cm in retry loop
  services/centralized-grafana/17.2.1/defaults/cm.yaml
  services/centralized-kubecost/0.19.0/kustomization.yaml
  services/centralized-kubecost/0.19.0/post-install-jobs.yaml
  services/centralized-kubecost/0.19.0/post-install-jobs/post-install-jobs.yaml
  services/centralized-kubecost/0.19.0/release.yaml
  services/centralized-kubecost/0.19.0/release/release.yaml
Labels: ready-for-review, do-not-merge

#31 chore: Set resource requests/limits for centralized-kubecost thanos
  services/centralized-kubecost/0.19.0/defaults/cm.yaml
Labels: ready-for-review

#38 fix: Cluster domain to work in alpine linux
  services/gitea/4.1.1/defaults/cm.yaml
Labels: ready-for-review

#29 kubecost: Bump to 0.20.0
  services/centralized-kubecost/0.20.0/defaults/cm.yaml
  services/centralized-kubecost/0.20.0/defaults/kustomization.yaml
  services/centralized-kubecost/0.20.0/kustomization.yaml
  services/centralized-kubecost/0.20.0/post-install-jobs.yaml
  services/centralized-kubecost/0.20.0/post-install-jobs/post-install-jobs.yaml
  services/centralized-kubecost/0.20.0/release.yaml
  services/centralized-kubecost/0.20.0/release/release.yaml
  services/kubecost/0.20.0/defaults/cm.yaml
  services/kubecost/0.20.0/defaults/kustomization.yaml
  services/kubecost/0.20.0/kubecost.yaml
  services/kubecost/0.20.0/kustomization.yaml
Labels: ready-for-review

#40 chore: Update kommander defaults
  services/kommander/0.1.0/defaults/cm.yaml
Labels: ready-for-review

#32 refactor: Deploy kubefed to kube-federation-system
  services/kubefed/0.8.1/defaults/cm.yaml
  services/kubefed/0.8.1/federatedtypeconfigs.yaml
  services/kubefed/0.8.1/federatedtypeconfigs/federatedtypeconfigs.yaml
  services/kubefed/0.8.1/kube-federation-system-namespace.yaml
  services/kubefed/0.8.1/kube-federation-system-namespace/kube-federation-system.yaml
  services/kubefed/0.8.1/kustomization.yaml
  services/kubefed/0.8.1/release.yaml
  services/kubefed/0.8.1/release/release.yaml
Labels: ready-for-review

#41 fix: allow plugin for kube-prome-stack
  services/kube-prometheus-stack/17.2.1/defaults/cm.yaml
Labels: ready-for-review

#14 feat: guard src ctrl ingress access with network policy
  services/kommander-flux/0.17.2/kustomization.yaml
  services/kommander-flux/0.17.2/patch-source-ctrl-network-policy.yaml
Labels: ready-for-review

#43 fix: add Traefik dependencies
  services/dex-k8s-authenticator/1.2.8/dex-k8s-authenticator.yaml
Labels: ready-for-review

#44 Bump flux to 0.22.1
  grafana-dashboards/centralized/kustomization.yaml
  grafana-dashboards/core-components/kustomization.yaml
  grafana-dashboards/kube-prometheus-stack/kustomization.yaml
  grafana-dashboards/traefik/kustomization.yaml
  grafana-dashboards/velero/kustomization.yaml
  services/centralized-kubecost/0.20.0/post-install-jobs.yaml
  services/centralized-kubecost/0.20.0/release.yaml
  services/cert-manager/0.2.7/release.yaml
  services/cert-manager/0.2.7/root-ca.yaml
  services/istio/1.9.1/helmrelease.yaml
  services/istio/1.9.1/istio-ca.yaml
  services/istio/1.9.1/istio-system-namespace.yaml
  services/kommander-flux/0.22.1/defaults/cm.yaml
  services/kommander-flux/0.22.1/defaults/kustomization.yaml
  services/kommander-flux/0.22.1/kustomization.yaml
  services/kommander-flux/0.22.1/patch-proxy-env-vars.yaml
  services/kommander-flux/0.22.1/patch-source-ctrl-network-policy.yaml
  services/kommander-flux/0.22.1/templates/apiextensions.k8s.io_v1_customresourcedefinition_alerts.notification.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.22.1/templates/apiextensions.k8s.io_v1_customresourcedefinition_buckets.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.22.1/templates/apiextensions.k8s.io_v1_customresourcedefinition_gitrepositories.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.22.1/templates/apiextensions.k8s.io_v1_customresourcedefinition_helmcharts.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.22.1/templates/apiextensions.k8s.io_v1_customresourcedefinition_helmreleases.helm.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.22.1/templates/apiextensions.k8s.io_v1_customresourcedefinition_helmrepositories.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.22.1/templates/apiextensions.k8s.io_v1_customresourcedefinition_kustomizations.kustomize.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.22.1/templates/apiextensions.k8s.io_v1_customresourcedefinition_providers.notification.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.22.1/templates/apiextensions.k8s.io_v1_customresourcedefinition_receivers.notification.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.22.1/templates/apps_v1_deployment_helm-controller.yaml
  services/kommander-flux/0.22.1/templates/apps_v1_deployment_kustomize-controller.yaml
  services/kommander-flux/0.22.1/templates/apps_v1_deployment_notification-controller.yaml
  services/kommander-flux/0.22.1/templates/apps_v1_deployment_source-controller.yaml
  services/kommander-flux/0.22.1/templates/kustomization.yaml
  services/kommander-flux/0.22.1/templates/networking.k8s.io_v1_networkpolicy_allow-egress.yaml
  services/kommander-flux/0.22.1/templates/networking.k8s.io_v1_networkpolicy_allow-scraping.yaml
  services/kommander-flux/0.22.1/templates/networking.k8s.io_v1_networkpolicy_allow-source.yaml
  services/kommander-flux/0.22.1/templates/networking.k8s.io_v1_networkpolicy_allow-webhooks.yaml
  services/kommander-flux/0.22.1/templates/rbac.authorization.k8s.io_v1_clusterrole_crd-controller-kommander-flux.yaml
  services/kommander-flux/0.22.1/templates/rbac.authorization.k8s.io_v1_clusterrolebinding_cluster-reconciler-kommander-flux.yaml
  services/kommander-flux/0.22.1/templates/rbac.authorization.k8s.io_v1_clusterrolebinding_crd-controller-kommander-flux.yaml
  services/kommander-flux/0.22.1/templates/v1_service_notification-controller.yaml
  services/kommander-flux/0.22.1/templates/v1_service_source-controller.yaml
  services/kommander-flux/0.22.1/templates/v1_service_webhook-receiver.yaml
  services/kommander-flux/0.22.1/templates/v1_serviceaccount_helm-controller.yaml
  services/kommander-flux/0.22.1/templates/v1_serviceaccount_kustomize-controller.yaml
  services/kommander-flux/0.22.1/templates/v1_serviceaccount_notification-controller.yaml
  services/kommander-flux/0.22.1/templates/v1_serviceaccount_source-controller.yaml
  services/kubefed/0.8.1/federatedtypeconfigs.yaml
  services/kubefed/0.8.1/kube-federation-system-namespace.yaml
  services/kubefed/0.8.1/release.yaml
Labels: ready-for-review

#47 feat: add tooling for updating Flux
  .tool-versions
  Dockerfile.ci
  Makefile
  hack/flux/flux-update-kustomization.yaml
  hack/flux/templates/networking.k8s.io_v1_networkpolicy_allow-source.yaml
  hack/flux/update-flux.sh
  make/all.mk
  make/ci.mk
  make/docker.mk
  make/flux.mk
  make/help.mk
  make/make.mk
  make/repo.mk
  make/shell.mk
  make/tools.mk
Labels: ready-for-review

#52 fix: really add all changes to commit
  hack/flux/update-flux.sh
Labels: ready-for-review

#54 fix: Disable clusterroles in project-grafana-logging
  services/project-grafana-logging/6.13.9/defaults/cm.yaml
Labels: ready-for-review

#60 chore: Bump kubefed to 0.9.0
  services/kubefed/0.9.0/defaults/cm.yaml
  services/kubefed/0.9.0/defaults/kustomization.yaml
  services/kubefed/0.9.0/federatedtypeconfigs.yaml
  services/kubefed/0.9.0/federatedtypeconfigs/federatedtypeconfigs.yaml
  services/kubefed/0.9.0/kube-federation-system-namespace.yaml
  services/kubefed/0.9.0/kube-federation-system-namespace/kube-federation-system.yaml
  services/kubefed/0.9.0/kustomization.yaml
  services/kubefed/0.9.0/release.yaml
  services/kubefed/0.9.0/release/release.yaml
Labels: ready-for-review

#59 fix: use release Kustomization for Gatekeeper
  services/gatekeeper/0.6.8/constrainttemplates.yaml
  services/gatekeeper/0.6.8/kustomization.yaml
  services/gatekeeper/0.6.8/release.yaml
Labels: ready-for-review

#64 feat: align configmap-reload image tag with other containers
  services/logging-operator/3.13.0/defaults/cm.yaml
Labels: ready-for-review

#65 feat: use TFA 3.0.3
  services/traefik-forward-auth-mgmt/0.3.2/defaults/cm.yaml
Labels: ready-for-review

#67 chore: Add mergebot config
  mergebot-config.json
Labels: ready-for-review, needs-backport

#71 feat: Upgrade flux to 0.24.0
  .envrc
  .tool-versions
  services/kommander-flux/0.24.0/defaults/cm.yaml
  services/kommander-flux/0.24.0/defaults/kustomization.yaml
  services/kommander-flux/0.24.0/kustomization.yaml
  services/kommander-flux/0.24.0/patch-proxy-env-vars.yaml
  services/kommander-flux/0.24.0/patch-source-ctrl-network-policy.yaml
  services/kommander-flux/0.24.0/templates/apiextensions.k8s.io_v1_customresourcedefinition_alerts.notification.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.24.0/templates/apiextensions.k8s.io_v1_customresourcedefinition_buckets.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.24.0/templates/apiextensions.k8s.io_v1_customresourcedefinition_gitrepositories.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.24.0/templates/apiextensions.k8s.io_v1_customresourcedefinition_helmcharts.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.24.0/templates/apiextensions.k8s.io_v1_customresourcedefinition_helmreleases.helm.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.24.0/templates/apiextensions.k8s.io_v1_customresourcedefinition_helmrepositories.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.24.0/templates/apiextensions.k8s.io_v1_customresourcedefinition_kustomizations.kustomize.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.24.0/templates/apiextensions.k8s.io_v1_customresourcedefinition_providers.notification.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.24.0/templates/apiextensions.k8s.io_v1_customresourcedefinition_receivers.notification.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.24.0/templates/apps_v1_deployment_helm-controller.yaml
  services/kommander-flux/0.24.0/templates/apps_v1_deployment_kustomize-controller.yaml
  services/kommander-flux/0.24.0/templates/apps_v1_deployment_notification-controller.yaml
  services/kommander-flux/0.24.0/templates/apps_v1_deployment_source-controller.yaml
  services/kommander-flux/0.24.0/templates/kustomization.yaml
  services/kommander-flux/0.24.0/templates/networking.k8s.io_v1_networkpolicy_allow-egress.yaml
  services/kommander-flux/0.24.0/templates/networking.k8s.io_v1_networkpolicy_allow-scraping.yaml
  services/kommander-flux/0.24.0/templates/networking.k8s.io_v1_networkpolicy_allow-source.yaml
  services/kommander-flux/0.24.0/templates/networking.k8s.io_v1_networkpolicy_allow-webhooks.yaml
  services/kommander-flux/0.24.0/templates/rbac.authorization.k8s.io_v1_clusterrole_crd-controller-kommander-flux.yaml
  services/kommander-flux/0.24.0/templates/rbac.authorization.k8s.io_v1_clusterrolebinding_cluster-reconciler-kommander-flux.yaml
  services/kommander-flux/0.24.0/templates/rbac.authorization.k8s.io_v1_clusterrolebinding_crd-controller-kommander-flux.yaml
  services/kommander-flux/0.24.0/templates/v1_namespace_kommander-flux.yaml
  services/kommander-flux/0.24.0/templates/v1_service_notification-controller.yaml
  services/kommander-flux/0.24.0/templates/v1_service_source-controller.yaml
  services/kommander-flux/0.24.0/templates/v1_service_webhook-receiver.yaml
  services/kommander-flux/0.24.0/templates/v1_serviceaccount_helm-controller.yaml
  services/kommander-flux/0.24.0/templates/v1_serviceaccount_kustomize-controller.yaml
  services/kommander-flux/0.24.0/templates/v1_serviceaccount_notification-controller.yaml
  services/kommander-flux/0.24.0/templates/v1_serviceaccount_source-controller.yaml
Labels: ready-for-review

#72 feat: add an audit dashboard to grafana-logging
  grafana-dashboards/logging/audit.json
  grafana-dashboards/logging/kustomization.yaml
  services/fluent-bit/0.16.2/defaults/cm.yaml
  services/grafana-logging/6.13.9/defaults/cm.yaml
  services/grafana-logging/6.13.9/kustomization.yaml
Labels: ready-for-review, ok-to-test, needs-backport

#76 chore: Bump logging-operator to 3.15.0
  services/logging-operator/3.15.0/defaults/cm.yaml
  services/logging-operator/3.15.0/defaults/kustomization.yaml
  services/logging-operator/3.15.0/kustomization.yaml
  services/logging-operator/3.15.0/logging-operator-logging.yaml
  services/logging-operator/3.15.0/logging-operator.yaml
Labels: ready-for-review, ok-to-test

#74 chore: update docker image tag for dex
  services/dex/2.9.10/defaults/cm.yaml
Labels: ready-for-review, ok-to-test, needs-backport

#77 feat: Provide release target
  .tool-versions
  make/all.mk
  make/release.mk
Labels: ready-for-review

#81 fix: updating docs link to kubecost
  services/kubecost/metadata.yaml
Labels: ready-for-review, ok-to-test
