Repository mesosphere/kommander-applications, pull requests merged in 2021-12, with the labels that each got.

#78 Add NFS Server Provisioner service
  services/nfs-server-provisioner/0.6.0/defaults/cm.yaml
  services/nfs-server-provisioner/0.6.0/defaults/kustomization.yaml
  services/nfs-server-provisioner/0.6.0/kustomization.yaml
  services/nfs-server-provisioner/0.6.0/nfs-server-provisioner.yaml
  services/nfs-server-provisioner/metadata.yaml
Labels: ready-for-review, ok-to-test

#80 chore: Use workspaceNamespace instead of traefikNamespace
  services/traefik-forward-auth/0.3.2/traefik-forward-auth.yaml
Labels: ready-for-review

#84 chore: Add kubecost 0.20.2
  services/centralized-kubecost/0.20.2/defaults/cm.yaml
  services/centralized-kubecost/0.20.2/defaults/kustomization.yaml
  services/centralized-kubecost/0.20.2/kustomization.yaml
  services/centralized-kubecost/0.20.2/post-install-jobs.yaml
  services/centralized-kubecost/0.20.2/post-install-jobs/post-install-jobs.yaml
  services/centralized-kubecost/0.20.2/release.yaml
  services/centralized-kubecost/0.20.2/release/release.yaml
  services/kubecost/0.20.2/defaults/cm.yaml
  services/kubecost/0.20.2/defaults/kustomization.yaml
  services/kubecost/0.20.2/kubecost.yaml
  services/kubecost/0.20.2/kustomization.yaml
Labels: ready-for-review, needs-backport

#85 chore: update docker image tag for dex-k8s-auth
  services/dex-k8s-authenticator/1.2.8/defaults/cm.yaml
Labels: ready-for-review, needs-backport

#83 fix: Restore all pod labels to metrics emitted by kube-state-metrics
  services/kube-prometheus-stack/18.1.1/defaults/cm.yaml
Labels: ready-for-review, ok-to-test

#86 fix: Deploy fluent-bit for pod logs to control plane
  services/logging-operator/3.15.0/defaults/cm.yaml
Labels: ready-for-review, ok-to-test

#89 feat: add knative serving as kommander application
  services/knative/0.18.3/defaults/cm.yaml
  services/knative/0.18.3/defaults/kustomization.yaml
  services/knative/0.18.3/knative-serving.yaml
  services/knative/0.18.3/kustomization.yaml
  services/knative/metadata.yaml
Labels: ready-for-review, ok-to-test

#90 bug: move Knative to "general" category
  services/knative/metadata.yaml
Labels: ready-for-review, ok-to-test

#92 fix: Upgrade Grafana to pull in a fix for CVE-2021-43798
  services/centralized-grafana/18.1.1/defaults/cm.yaml
  services/grafana-logging/6.16.14/defaults/cm.yaml
  services/kube-prometheus-stack/18.1.1/defaults/cm.yaml
Labels: ready-for-review, ok-to-test

#94 fix: change `cert-manager` group from foundation to security
  services/cert-manager/metadata.yaml
Labels: ready-for-review, ok-to-test

#98 fix: Bump project-grafana-logging/kubecost graf img to pull in a fix for CVE-2021-43798
  services/kubecost/0.20.2/defaults/cm.yaml
  services/project-grafana-logging/6.16.14/defaults/cm.yaml
Labels: ready-for-review, needs-backport

#97 [release-2.1] feat: Add mesosphere-spark and pravega helmrepos
  common/helm-repositories/mesosphere-spark.yaml
  common/helm-repositories/pravega.yaml
Labels: ready-for-review

#103 fix: Remove kube-prometheus-stack dep from knative
  services/knative/0.18.3/knative-serving.yaml
Labels: ready-for-review

#105 [release-2.1][BACKPORT] feat: Update KPS to 18.1.1 & Grafana to 6.16.14
  services/centralized-grafana/18.1.1/centralized-grafana.yaml
  services/centralized-grafana/18.1.1/defaults/cm.yaml
  services/centralized-grafana/18.1.1/defaults/kustomization.yaml
  services/centralized-grafana/18.1.1/kustomization.yaml
  services/grafana-logging/6.16.14/defaults/cm.yaml
  services/grafana-logging/6.16.14/defaults/kustomization.yaml
  services/grafana-logging/6.16.14/grafana.yaml
  services/grafana-logging/6.16.14/kustomization.yaml
  services/kube-prometheus-stack/18.1.1/defaults/cm.yaml
  services/kube-prometheus-stack/18.1.1/defaults/kustomization.yaml
  services/kube-prometheus-stack/18.1.1/kube-prometheus-stack.yaml
  services/kube-prometheus-stack/18.1.1/kustomization.yaml
  services/kube-prometheus-stack/metadata.yaml
  services/project-grafana-logging/6.16.14/defaults/cm.yaml
  services/project-grafana-logging/6.16.14/defaults/kustomization.yaml
  services/project-grafana-logging/6.16.14/kustomization.yaml
  services/project-grafana-logging/6.16.14/project-grafana.yaml
Labels: ready-for-review, ok-to-test

#107 Add metadata for knative and correct dependency information
  services/knative/0.18.3/knative-serving.yaml
  services/knative/metadata.yaml
Labels: needs-backport

#109 fix: Remove newlines in knative icon
  services/knative/metadata.yaml
Labels: ready-for-review, needs-backport

#110 [BACKPORT][release-2.1] fix: Remove newlines in knative icon
  services/knative/metadata.yaml
Labels: ready-for-review, backport-pr

#112 Fix misplaced `dependsOn` property for KNative
  services/knative/0.18.3/knative-serving.yaml
Labels: ready-for-review, needs-backport

#106 feat: add kaptain
  services/kaptain/1.3.0/defaults/cm.yaml
  services/kaptain/1.3.0/defaults/kustomization.yaml
  services/kaptain/1.3.0/kaptain.yaml
  services/kaptain/1.3.0/kustomization.yaml
  services/kaptain/metadata.yaml
Labels: ready-for-review

#111 chore: bump velero for K8s 1.22
  services/velero/3.1.4/defaults/cm.yaml
  services/velero/3.1.4/defaults/kustomization.yaml
  services/velero/3.1.4/kustomization.yaml
  services/velero/3.1.4/velero.yaml
Labels: ready-for-review, ok-to-test

#114 fix: set sha to empty to ensure airgapped works
  services/kube-prometheus-stack/18.1.1/defaults/cm.yaml
Labels: ready-for-review, needs-backport

#119 feat: add chartmuseum app
  services/chartmuseum/3.4.0/README.md
  services/chartmuseum/3.4.0/chartmuseum-3.4.0.tgz
  services/chartmuseum/3.4.0/chartmuseum.yaml
  services/chartmuseum/3.4.0/defaults/cm.yaml
  services/chartmuseum/3.4.0/defaults/kustomization.yaml
  services/chartmuseum/3.4.0/kustomization.yaml
Labels: ready-for-review, ok-to-test

#120 feat: Add kaptain helm repository
  common/helm-repositories/kaptain.yaml
Labels: ready-for-review

#118 fix: Remove trailing whitespace (#117)
  services/kube-prometheus-stack/18.1.1/defaults/cm.yaml
Labels: ready-for-review

#116 chore: bump dex for k8s 1.22
  services/dex/2.9.11/defaults/cm.yaml
  services/dex/2.9.11/defaults/kustomization.yaml
  services/dex/2.9.11/dex.yaml
  services/dex/2.9.11/kustomization.yaml
Labels: ready-for-review, ok-to-test
