Repository mesosphere/kommander-applications, pull requests merged in 2022-07, with the labels that each got.

#457 feat: Bump kiali and jaeger
  services/istio/1.14.1/defaults/cm.yaml
  services/istio/1.14.1/defaults/kustomization.yaml
  services/istio/1.14.1/helmrelease.yaml
  services/istio/1.14.1/helmrelease/helmrelease.yaml
  services/istio/1.14.1/kustomization.yaml
  services/jaeger/2.32.2/defaults/cm.yaml
  services/jaeger/2.32.2/defaults/kustomization.yaml
  services/jaeger/2.32.2/helmrelease.yaml
  services/jaeger/2.32.2/helmrelease/release.yaml
  services/jaeger/2.32.2/kustomization.yaml
  services/jaeger/2.32.2/pre-upgrade.yaml
  services/jaeger/2.32.2/pre-upgrade/delete-jaeger-deployment.yaml
  services/kiali/1.52.0/defaults/cm.yaml
  services/kiali/1.52.0/defaults/kustomization.yaml
  services/kiali/1.52.0/kiali.yaml
  services/kiali/1.52.0/kustomization.yaml
Labels: ready-for-review, ok-to-test

#455 feat: traefik-forward-auth-mgmt: move init logic to controller
  services/traefik-forward-auth-mgmt/0.3.9/defaults/cm.yaml
  services/traefik-forward-auth-mgmt/0.3.9/defaults/kustomization.yaml
  services/traefik-forward-auth-mgmt/0.3.9/kustomization.yaml
  services/traefik-forward-auth-mgmt/0.3.9/traefik-forward-auth-mgmt.yaml
  services/traefik-forward-auth/0.3.8/defaults/cm.yaml
Labels: ready-for-review, ok-to-test, do-not-merge/testing

#468 fix: usage of readonly var in `update-flux.sh`
  hack/flux/update-flux.sh
Labels: ready-for-review, ok-to-test

#469 feat: remove dex init container
  services/dex/2.9.19/defaults/cm.yaml
  services/dex/2.9.19/defaults/kustomization.yaml
  services/dex/2.9.19/dex.yaml
  services/dex/2.9.19/kustomization.yaml
Labels: ready-for-review, ok-to-test

#465 feat: bump chartmuseum to 3.9.0
  services/chartmuseum/3.6.2/chartmuseum-3.6.2.tgz
  services/chartmuseum/3.9.0/README.md
  services/chartmuseum/3.9.0/chartmuseum-3.9.0.tgz
  services/chartmuseum/3.9.0/chartmuseum.yaml
  services/chartmuseum/3.9.0/defaults/cm.yaml
  services/chartmuseum/3.9.0/defaults/kustomization.yaml
  services/chartmuseum/3.9.0/kustomization.yaml
Labels: ready-for-review, ok-to-test

#471 build: fix flux bump tooling
  hack/flux/update-flux.sh
Labels: ready-for-review, ok-to-test

#454 chore: Bump memcached and postgresql images in gitea helm release
  services/gitea/5.0.9/defaults/cm.yaml
Labels: ready-for-review, ok-to-test

#443 chore: Bump Kubecost to 1.94.3
  services/centralized-kubecost/0.25.3/defaults/cm.yaml
  services/centralized-kubecost/0.25.3/defaults/kustomization.yaml
  services/centralized-kubecost/0.25.3/kustomization.yaml
  services/centralized-kubecost/0.25.3/post-install-jobs.yaml
  services/centralized-kubecost/0.25.3/post-install-jobs/post-install-jobs.yaml
  services/centralized-kubecost/0.25.3/release.yaml
  services/centralized-kubecost/0.25.3/release/release.yaml
  services/kommander/0.3.0/defaults/cm.yaml
  services/kubecost/0.25.3/defaults/cm.yaml
  services/kubecost/0.25.3/defaults/kustomization.yaml
  services/kubecost/0.25.3/kubecost.yaml
  services/kubecost/0.25.3/kustomization.yaml
Labels: ready-for-review, ok-to-test

#470 build: add pull request template
  .github/pull_request_template.md
Labels: documentation, ready-for-review

#472 feat: add webhook cert values for appmanagement
  services/kommander-appmanagement/0.3.0/defaults/cm.yaml
  services/kommander/0.3.0/defaults/cm.yaml
Labels: ready-for-review, ok-to-test, let-me-merge-it

#474 feat: Use gh-dkp tool for calculating dev release name
  .go-tools
  .tool-versions
  make/repo.mk
  make/tools.mk
Labels: ready-for-review, ok-to-test

#478 fix: remove trailing whitespace
  .github/pull_request_template.md
Labels: ready-for-review, ok-to-test

#476 chore: add .idea dir to gitignore
  .gitignore
Labels: ready-for-review, ok-to-test

#477 chore: add direnv plugin to .tool-versions
  .tool-versions
Labels: ready-for-review, ok-to-test

#480 fix: Remove outdated grafana app dashboard
  services/kube-prometheus-stack/34.9.3/grafana-dashboards/grafana.json
  services/kube-prometheus-stack/34.9.3/grafana-dashboards/kustomization.yaml
Labels: ready-for-review, ok-to-test, needs-backport, auto-backport, backport-to-release-2.2

#483 [release-2.2][BACKPORT] fix: Remove outdated grafana app dashboard (#480)
  services/kube-prometheus-stack/33.1.6/grafana-dashboards/grafana.json
  services/kube-prometheus-stack/33.1.6/grafana-dashboards/kustomization.yaml
Labels: ready-for-review, ok-to-test, backport-pr

#486 feat: Upgrade flux to 0.31.4
  .tool-versions
  services/kommander-flux/0.31.4/defaults/cm.yaml
  services/kommander-flux/0.31.4/defaults/kustomization.yaml
  services/kommander-flux/0.31.4/kustomization.yaml
  services/kommander-flux/0.31.4/patch-proxy-env-vars.yaml
  services/kommander-flux/0.31.4/patch-source-ctrl-network-policy.yaml
  services/kommander-flux/0.31.4/templates/apiextensions.k8s.io_v1_customresourcedefinition_alerts.notification.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.31.4/templates/apiextensions.k8s.io_v1_customresourcedefinition_buckets.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.31.4/templates/apiextensions.k8s.io_v1_customresourcedefinition_gitrepositories.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.31.4/templates/apiextensions.k8s.io_v1_customresourcedefinition_helmcharts.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.31.4/templates/apiextensions.k8s.io_v1_customresourcedefinition_helmreleases.helm.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.31.4/templates/apiextensions.k8s.io_v1_customresourcedefinition_helmrepositories.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.31.4/templates/apiextensions.k8s.io_v1_customresourcedefinition_kustomizations.kustomize.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.31.4/templates/apiextensions.k8s.io_v1_customresourcedefinition_providers.notification.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.31.4/templates/apiextensions.k8s.io_v1_customresourcedefinition_receivers.notification.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.31.4/templates/apps_v1_deployment_helm-controller.yaml
  services/kommander-flux/0.31.4/templates/apps_v1_deployment_kustomize-controller.yaml
  services/kommander-flux/0.31.4/templates/apps_v1_deployment_notification-controller.yaml
  services/kommander-flux/0.31.4/templates/apps_v1_deployment_source-controller.yaml
  services/kommander-flux/0.31.4/templates/kustomization.yaml
  services/kommander-flux/0.31.4/templates/networking.k8s.io_v1_networkpolicy_allow-egress.yaml
  services/kommander-flux/0.31.4/templates/networking.k8s.io_v1_networkpolicy_allow-scraping.yaml
  services/kommander-flux/0.31.4/templates/networking.k8s.io_v1_networkpolicy_allow-source.yaml
  services/kommander-flux/0.31.4/templates/networking.k8s.io_v1_networkpolicy_allow-webhooks.yaml
  services/kommander-flux/0.31.4/templates/rbac.authorization.k8s.io_v1_clusterrole_crd-controller-kommander-flux.yaml
  services/kommander-flux/0.31.4/templates/rbac.authorization.k8s.io_v1_clusterrolebinding_cluster-reconciler-kommander-flux.yaml
  services/kommander-flux/0.31.4/templates/rbac.authorization.k8s.io_v1_clusterrolebinding_crd-controller-kommander-flux.yaml
  services/kommander-flux/0.31.4/templates/v1_namespace_kommander-flux.yaml
  services/kommander-flux/0.31.4/templates/v1_service_notification-controller.yaml
  services/kommander-flux/0.31.4/templates/v1_service_source-controller.yaml
  services/kommander-flux/0.31.4/templates/v1_service_webhook-receiver.yaml
  services/kommander-flux/0.31.4/templates/v1_serviceaccount_helm-controller.yaml
  services/kommander-flux/0.31.4/templates/v1_serviceaccount_kustomize-controller.yaml
  services/kommander-flux/0.31.4/templates/v1_serviceaccount_notification-controller.yaml
  services/kommander-flux/0.31.4/templates/v1_serviceaccount_source-controller.yaml
  services/kommander/0.3.0/defaults/cm.yaml
Labels: ready-for-review, ok-to-test, slack-notify

#473 feat: Upgrade flux to 0.31.3
  .tool-versions
  services/kommander-flux/0.31.3/defaults/cm.yaml
  services/kommander-flux/0.31.3/defaults/kustomization.yaml
  services/kommander-flux/0.31.3/kustomization.yaml
  services/kommander-flux/0.31.3/patch-proxy-env-vars.yaml
  services/kommander-flux/0.31.3/patch-source-ctrl-network-policy.yaml
  services/kommander-flux/0.31.3/templates/apiextensions.k8s.io_v1_customresourcedefinition_alerts.notification.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.31.3/templates/apiextensions.k8s.io_v1_customresourcedefinition_buckets.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.31.3/templates/apiextensions.k8s.io_v1_customresourcedefinition_gitrepositories.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.31.3/templates/apiextensions.k8s.io_v1_customresourcedefinition_helmcharts.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.31.3/templates/apiextensions.k8s.io_v1_customresourcedefinition_helmreleases.helm.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.31.3/templates/apiextensions.k8s.io_v1_customresourcedefinition_helmrepositories.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.31.3/templates/apiextensions.k8s.io_v1_customresourcedefinition_kustomizations.kustomize.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.31.3/templates/apiextensions.k8s.io_v1_customresourcedefinition_providers.notification.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.31.3/templates/apiextensions.k8s.io_v1_customresourcedefinition_receivers.notification.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.31.3/templates/apps_v1_deployment_helm-controller.yaml
  services/kommander-flux/0.31.3/templates/apps_v1_deployment_kustomize-controller.yaml
  services/kommander-flux/0.31.3/templates/apps_v1_deployment_notification-controller.yaml
  services/kommander-flux/0.31.3/templates/apps_v1_deployment_source-controller.yaml
  services/kommander-flux/0.31.3/templates/kustomization.yaml
  services/kommander-flux/0.31.3/templates/networking.k8s.io_v1_networkpolicy_allow-egress.yaml
  services/kommander-flux/0.31.3/templates/networking.k8s.io_v1_networkpolicy_allow-scraping.yaml
  services/kommander-flux/0.31.3/templates/networking.k8s.io_v1_networkpolicy_allow-source.yaml
  services/kommander-flux/0.31.3/templates/networking.k8s.io_v1_networkpolicy_allow-webhooks.yaml
  services/kommander-flux/0.31.3/templates/rbac.authorization.k8s.io_v1_clusterrole_crd-controller-kommander-flux.yaml
  services/kommander-flux/0.31.3/templates/rbac.authorization.k8s.io_v1_clusterrolebinding_cluster-reconciler-kommander-flux.yaml
  services/kommander-flux/0.31.3/templates/rbac.authorization.k8s.io_v1_clusterrolebinding_crd-controller-kommander-flux.yaml
  services/kommander-flux/0.31.3/templates/v1_namespace_kommander-flux.yaml
  services/kommander-flux/0.31.3/templates/v1_service_notification-controller.yaml
  services/kommander-flux/0.31.3/templates/v1_service_source-controller.yaml
  services/kommander-flux/0.31.3/templates/v1_service_webhook-receiver.yaml
  services/kommander-flux/0.31.3/templates/v1_serviceaccount_helm-controller.yaml
  services/kommander-flux/0.31.3/templates/v1_serviceaccount_kustomize-controller.yaml
  services/kommander-flux/0.31.3/templates/v1_serviceaccount_notification-controller.yaml
  services/kommander-flux/0.31.3/templates/v1_serviceaccount_source-controller.yaml
  services/kommander/0.2.2/defaults/cm.yaml
Labels: ready-for-review, slack-notify

#479 feat: Bump knative, use chart version as app version (#296)
  services/knative/0.3.9/defaults/cm.yaml
  services/knative/0.3.9/defaults/kustomization.yaml
  services/knative/0.3.9/knative-serving.yaml
  services/knative/0.3.9/kustomization.yaml
Labels: ready-for-review, ok-to-test

#482 chore: wire appmgmt webhook images from installer config
  services/kommander-appmanagement/0.3.0/defaults/cm.yaml
Labels: ready-for-review, ok-to-test

#488 feat: Bump kubecost to 0.26.0
  services/centralized-kubecost/0.26.0/defaults/cm.yaml
  services/centralized-kubecost/0.26.0/defaults/kustomization.yaml
  services/centralized-kubecost/0.26.0/kustomization.yaml
  services/centralized-kubecost/0.26.0/post-install-jobs.yaml
  services/centralized-kubecost/0.26.0/post-install-jobs/post-install-jobs.yaml
  services/centralized-kubecost/0.26.0/release.yaml
  services/centralized-kubecost/0.26.0/release/release.yaml
  services/kommander/0.3.0/defaults/cm.yaml
  services/kubecost/0.26.0/defaults/cm.yaml
  services/kubecost/0.26.0/defaults/kustomization.yaml
  services/kubecost/0.26.0/kubecost.yaml
  services/kubecost/0.26.0/kustomization.yaml
Labels: ready-for-review, ok-to-test

#490 feat: Bump thanos kapps version
  services/kommander/0.3.0/defaults/cm.yaml
  services/thanos/0.4.7/defaults/cm.yaml
  services/thanos/0.4.7/defaults/kustomization.yaml
  services/thanos/0.4.7/jobs.yaml
  services/thanos/0.4.7/jobs/jobs.yaml
  services/thanos/0.4.7/kustomization.yaml
  services/thanos/0.4.7/thanos.yaml
Labels: ready-for-review, ok-to-test

#491 feat: Bump DKP-Insights to 0.2.0
  services/dkp-insights-management/0.2.0/defaults/cm.yaml
  services/dkp-insights-management/0.2.0/defaults/kustomization.yaml
  services/dkp-insights-management/0.2.0/helmrelease.yaml
  services/dkp-insights-management/0.2.0/helmrelease/helmrelease.yaml
  services/dkp-insights-management/0.2.0/kustomization.yaml
Labels: ready-for-review, ok-to-test

#495 fix: Add timeouts in install/upgrade
  services/kube-prometheus-stack/34.9.3/kube-prometheus-stack.yaml
Labels: ready-for-review, ok-to-test

#496 feat: Bump DKP-Insights to 0.2.1
  services/dkp-insights-management/0.2.1/defaults/cm.yaml
  services/dkp-insights-management/0.2.1/defaults/kustomization.yaml
  services/dkp-insights-management/0.2.1/helmrelease.yaml
  services/dkp-insights-management/0.2.1/helmrelease/helmrelease.yaml
  services/dkp-insights-management/0.2.1/kustomization.yaml
Labels: ready-for-review, ok-to-test

#498 feat: Bump DKP-Insights to 0.2.2
  services/dkp-insights-management/0.2.2/defaults/cm.yaml
  services/dkp-insights-management/0.2.2/defaults/kustomization.yaml
  services/dkp-insights-management/0.2.2/helmrelease.yaml
  services/dkp-insights-management/0.2.2/helmrelease/helmrelease.yaml
  services/dkp-insights-management/0.2.2/kustomization.yaml
Labels: ready-for-review, ok-to-test

#499 feat: Use gh-dkp tool for calculating dev release name (#474)
  .tool-versions
  make/repo.mk
  make/tools.mk
Labels: ready-for-review, ok-to-test

#500 feat: Use gh-dkp tool for calculating dev release name (#474)
  .tool-versions
  make/repo.mk
  make/tools.mk
Labels: ready-for-review, ok-to-test

#502 chore: Post-release bumps for release-2.3 branch
  mergebot-config.json
  services/kommander-appmanagement/0.3.1/defaults/cm.yaml
  services/kommander-appmanagement/0.3.1/defaults/kustomization.yaml
  services/kommander-appmanagement/0.3.1/kommander-appmanagement.yaml
  services/kommander-appmanagement/0.3.1/kustomization.yaml
  services/kommander/0.3.1/defaults/cm.yaml
  services/kommander/0.3.1/defaults/kustomization.yaml
  services/kommander/0.3.1/dynamic-helmreleases/README.txt
  services/kommander/0.3.1/dynamic-helmreleases/cluster-observer/cluster-observer.yaml
  services/kommander/0.3.1/dynamic-helmreleases/cluster-observer/kustomization.yaml
  services/kommander/0.3.1/dynamic-helmreleases/mtls-proxy/kustomization.yaml
  services/kommander/0.3.1/dynamic-helmreleases/mtls-proxy/mtls-proxy.yaml
  services/kommander/0.3.1/kommander.yaml
  services/kommander/0.3.1/kustomization.yaml
Labels: ready-for-review, ok-to-test

#501 chore: Post release bumps for main branch
  mergebot-config.json
  services/kommander-appmanagement/0.4.0/defaults/cm.yaml
  services/kommander-appmanagement/0.4.0/defaults/kustomization.yaml
  services/kommander-appmanagement/0.4.0/kommander-appmanagement.yaml
  services/kommander-appmanagement/0.4.0/kustomization.yaml
  services/kommander/0.4.0/defaults/cm.yaml
  services/kommander/0.4.0/defaults/kustomization.yaml
  services/kommander/0.4.0/dynamic-helmreleases/README.txt
  services/kommander/0.4.0/dynamic-helmreleases/cluster-observer/cluster-observer.yaml
  services/kommander/0.4.0/dynamic-helmreleases/cluster-observer/kustomization.yaml
  services/kommander/0.4.0/dynamic-helmreleases/mtls-proxy/kustomization.yaml
  services/kommander/0.4.0/dynamic-helmreleases/mtls-proxy/mtls-proxy.yaml
  services/kommander/0.4.0/kommander.yaml
  services/kommander/0.4.0/kustomization.yaml
Labels: ready-for-review, ok-to-test

#504 Seialkali/fix/2.3 update Stakater and centralized cost monitoring links
  services/kubecost/metadata.yaml
  services/reloader/metadata.yaml
Labels: ok-to-test

#505 chore: update app refs in metadata
  services/kube-prometheus-stack/metadata.yaml
  services/kubecost/metadata.yaml
Labels: ready-for-review, ok-to-test, auto-backport, backport-to-release-2.3

#503 fix: update URLs for Stakater and centralized cost monitoring docs page
  services/kubecost/metadata.yaml
  services/reloader/metadata.yaml
Labels: ok-to-test

#507 build: Bump mergebot release-2.3 version back to 2.3.0
  mergebot-config.json
Labels: ready-for-review, ok-to-test, auto-backport, backport-to-release-2.3

#517 feat: Bump `dex-controller` to `v0.6.21` by bumping `dex` to `2.9.19`
  services/dex/2.9.19/dex.yaml
Labels: ready-for-review, ok-to-test, needs-backport, auto-backport, backport-to-release-2.3

#516 chore: relax logging stack resource limitations
  services/fluent-bit/0.19.20/defaults/cm.yaml
  services/grafana-loki/0.48.4/defaults/cm.yaml
Labels: ready-for-review, ok-to-test, needs-backport

#511 refactor: Make chart version updater functionality public
  hack/release/cmd/prerelease/prerelease.go
  hack/release/pkg/chartversion/chartversion.go
  hack/release/pkg/chartversion/chartversion_test.go
Labels: ready-for-review, ok-to-test

#520 chore: bump loki ingester limits as a precaution
  services/grafana-loki/0.48.4/defaults/cm.yaml
Labels: ready-for-review, ok-to-test

#497 fix: Change project logging app metadata to type platform
  services/project-grafana-logging/metadata.yaml
  services/project-grafana-loki/metadata.yaml
  services/project-logging/metadata.yaml
Labels: ready-for-review, ok-to-test, backport-to-release-2.3

#522 [release-2.3] chore: relax logging stack resource limitations
  services/fluent-bit/0.19.20/defaults/cm.yaml
  services/grafana-loki/0.48.4/defaults/cm.yaml
Labels: ready-for-review, ok-to-test, backport-pr

#521 chore: bump grpc client size
  services/grafana-loki/0.48.4/defaults/cm.yaml
Labels: ready-for-review, ok-to-test
