Repository mesosphere/kommander-applications, pull requests merged in 2022-05, with the labels that each got.

#373 feat: Upgrade flux to 0.29.5
  .tool-versions
  services/kommander-flux/0.29.5/defaults/cm.yaml
  services/kommander-flux/0.29.5/defaults/kustomization.yaml
  services/kommander-flux/0.29.5/kustomization.yaml
  services/kommander-flux/0.29.5/patch-proxy-env-vars.yaml
  services/kommander-flux/0.29.5/patch-source-ctrl-network-policy.yaml
  services/kommander-flux/0.29.5/templates/apiextensions.k8s.io_v1_customresourcedefinition_alerts.notification.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.29.5/templates/apiextensions.k8s.io_v1_customresourcedefinition_buckets.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.29.5/templates/apiextensions.k8s.io_v1_customresourcedefinition_gitrepositories.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.29.5/templates/apiextensions.k8s.io_v1_customresourcedefinition_helmcharts.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.29.5/templates/apiextensions.k8s.io_v1_customresourcedefinition_helmreleases.helm.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.29.5/templates/apiextensions.k8s.io_v1_customresourcedefinition_helmrepositories.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.29.5/templates/apiextensions.k8s.io_v1_customresourcedefinition_kustomizations.kustomize.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.29.5/templates/apiextensions.k8s.io_v1_customresourcedefinition_providers.notification.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.29.5/templates/apiextensions.k8s.io_v1_customresourcedefinition_receivers.notification.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.29.5/templates/apps_v1_deployment_helm-controller.yaml
  services/kommander-flux/0.29.5/templates/apps_v1_deployment_kustomize-controller.yaml
  services/kommander-flux/0.29.5/templates/apps_v1_deployment_notification-controller.yaml
  services/kommander-flux/0.29.5/templates/apps_v1_deployment_source-controller.yaml
  services/kommander-flux/0.29.5/templates/kustomization.yaml
  services/kommander-flux/0.29.5/templates/networking.k8s.io_v1_networkpolicy_allow-egress.yaml
  services/kommander-flux/0.29.5/templates/networking.k8s.io_v1_networkpolicy_allow-scraping.yaml
  services/kommander-flux/0.29.5/templates/networking.k8s.io_v1_networkpolicy_allow-source.yaml
  services/kommander-flux/0.29.5/templates/networking.k8s.io_v1_networkpolicy_allow-webhooks.yaml
  services/kommander-flux/0.29.5/templates/rbac.authorization.k8s.io_v1_clusterrole_crd-controller-kommander-flux.yaml
  services/kommander-flux/0.29.5/templates/rbac.authorization.k8s.io_v1_clusterrolebinding_cluster-reconciler-kommander-flux.yaml
  services/kommander-flux/0.29.5/templates/rbac.authorization.k8s.io_v1_clusterrolebinding_crd-controller-kommander-flux.yaml
  services/kommander-flux/0.29.5/templates/v1_namespace_kommander-flux.yaml
  services/kommander-flux/0.29.5/templates/v1_service_notification-controller.yaml
  services/kommander-flux/0.29.5/templates/v1_service_source-controller.yaml
  services/kommander-flux/0.29.5/templates/v1_service_webhook-receiver.yaml
  services/kommander-flux/0.29.5/templates/v1_serviceaccount_helm-controller.yaml
  services/kommander-flux/0.29.5/templates/v1_serviceaccount_kustomize-controller.yaml
  services/kommander-flux/0.29.5/templates/v1_serviceaccount_notification-controller.yaml
  services/kommander-flux/0.29.5/templates/v1_serviceaccount_source-controller.yaml
  services/kommander/0.3.0/defaults/cm.yaml
Labels: ready-for-review, ok-to-test, slack-notify

#375 fix: bump KPS chart based Apps
  services/centralized-grafana/34.9.1/centralized-grafana.yaml
  services/centralized-grafana/34.9.1/defaults/cm.yaml
  services/centralized-grafana/34.9.1/defaults/kustomization.yaml
  services/centralized-grafana/34.9.1/grafana-dashboards/global-overview.json
  services/centralized-grafana/34.9.1/grafana-dashboards/kustomization.yaml
  services/centralized-grafana/34.9.1/kustomization.yaml
  services/kommander/0.3.0/defaults/cm.yaml
  services/kube-prometheus-stack/34.9.1/defaults/cm.yaml
  services/kube-prometheus-stack/34.9.1/defaults/kustomization.yaml
  services/kube-prometheus-stack/34.9.1/grafana-dashboards/calico.json
  services/kube-prometheus-stack/34.9.1/grafana-dashboards/flux-cluster-stats.json
  services/kube-prometheus-stack/34.9.1/grafana-dashboards/flux-control-plane.json
  services/kube-prometheus-stack/34.9.1/grafana-dashboards/grafana.json
  services/kube-prometheus-stack/34.9.1/grafana-dashboards/kustomization.yaml
  services/kube-prometheus-stack/34.9.1/kube-prometheus-stack.yaml
  services/kube-prometheus-stack/34.9.1/kustomization.yaml
Labels: ready-for-review, ok-to-test

#378 fix: Put minio creds secret back at old name
  services/grafana-loki/0.48.3/minio.yaml
  services/project-grafana-loki/0.48.3/minio.yaml
Labels: ready-for-review, ok-to-test, do-not-merge/testing

#377 chore: bump dex
  services/dex/2.9.16/defaults/cm.yaml
  services/dex/2.9.16/defaults/kustomization.yaml
  services/dex/2.9.16/dex.yaml
  services/dex/2.9.16/kustomization.yaml
Labels: ready-for-review, ok-to-test

#369 chore: sops encryption config params in kommander-vars cm
  services/kommander/0.3.0/defaults/cm.yaml
Labels: ready-for-review, ok-to-test, needs-backport

#380 feat: add validation against multiple Kubernetes versions
  .bloodhound.yml
  make/validate.mk
Labels: ready-for-review, ok-to-test

#384 chore: KPS & central grafana permission backport
  services/centralized-grafana/33.1.6/centralized-grafana.yaml
  services/centralized-grafana/33.1.6/defaults/cm.yaml
  services/centralized-grafana/33.1.6/defaults/kustomization.yaml
  services/centralized-grafana/33.1.6/grafana-dashboards/global-overview.json
  services/centralized-grafana/33.1.6/grafana-dashboards/kustomization.yaml
  services/centralized-grafana/33.1.6/kustomization.yaml
  services/kommander/0.2.1/defaults/cm.yaml
  services/kube-prometheus-stack/33.1.6/defaults/cm.yaml
  services/kube-prometheus-stack/33.1.6/defaults/kustomization.yaml
  services/kube-prometheus-stack/33.1.6/grafana-dashboards/calico.json
  services/kube-prometheus-stack/33.1.6/grafana-dashboards/flux-cluster-stats.json
  services/kube-prometheus-stack/33.1.6/grafana-dashboards/flux-control-plane.json
  services/kube-prometheus-stack/33.1.6/grafana-dashboards/grafana.json
  services/kube-prometheus-stack/33.1.6/grafana-dashboards/kustomization.yaml
  services/kube-prometheus-stack/33.1.6/kube-prometheus-stack.yaml
  services/kube-prometheus-stack/33.1.6/kustomization.yaml
Labels: ready-for-review, ok-to-test

#386 chore: upgrade bloodhound with Helm capability fixes
  .bloodhound.yml
  make/validate.mk
Labels: ready-for-review, ok-to-test

#385 feat: Bump kubecost to 0.24.0
  services/centralized-kubecost/0.24.0/defaults/cm.yaml
  services/centralized-kubecost/0.24.0/defaults/kustomization.yaml
  services/centralized-kubecost/0.24.0/kustomization.yaml
  services/centralized-kubecost/0.24.0/post-install-jobs.yaml
  services/centralized-kubecost/0.24.0/post-install-jobs/post-install-jobs.yaml
  services/centralized-kubecost/0.24.0/release.yaml
  services/centralized-kubecost/0.24.0/release/release.yaml
  services/kommander/0.3.0/defaults/cm.yaml
  services/kubecost/0.24.0/defaults/cm.yaml
  services/kubecost/0.24.0/defaults/kustomization.yaml
  services/kubecost/0.24.0/kubecost.yaml
  services/kubecost/0.24.0/kustomization.yaml
Labels: ready-for-review, ok-to-test

#391 feat: add crds policy to minio-operator HelmRelease
  services/minio-operator/4.4.16/minio-operator-helmrelease/release.yaml
Labels: ready-for-review, ok-to-test, needs-backport

#396 feat: Use -dev for development release instead of -next
  .go-tools
  make/repo.mk
Labels: ready-for-review, ok-to-test

#397 feat: Bump komm charts to v2.2.1-rc.1
  services/kommander-appmanagement/0.2.1/kommander-appmanagement.yaml
  services/kommander/0.2.1/kommander.yaml
Labels: ready-for-review, ok-to-test

#398 fix: Lint against release-2.1 branch, update tools
  .tool-versions
  make/pre-commit.mk
Labels: ok-to-test

#401 fix: Update Loki tenant to support minio-operator upgrade
  services/grafana-loki/0.48.3/minio.yaml
Labels: ready-for-review, ok-to-test, needs-backport

#408 build: add backport-action to repo
  .github/workflows/backport.yaml
Labels: ready-for-review, ok-to-test

#404 build: add 0.0.2 cert-federation chart for airgapped bundle
  .github/workflows/backport.yaml
  common/build/kommander-cert-federation.yaml
Labels: ready-for-review, ok-to-test, needs-backport, auto-backport, backport-to-release-2.2

#411 [release 2.2] build: add 0.0.2 cert-federation chart for airgapped bundle
  common/build/kommander-cert-federation.yaml
Labels: ready-for-review, ok-to-test

#413 build: bump komm charts to v2.2.1-rc.3
  services/kommander-appmanagement/0.2.1/kommander-appmanagement.yaml
  services/kommander/0.2.1/kommander.yaml
Labels: ready-for-review, ok-to-test

#416 build: bump konvoy and kommander to v2.2.1
  services/kommander-appmanagement/0.2.1/kommander-appmanagement.yaml
  services/kommander/0.2.1/kommander.yaml
Labels: ready-for-review, ok-to-test

#415 feat: Bump Kubecost chart to 0.25.0
  services/centralized-kubecost/0.25.0/defaults/cm.yaml
  services/centralized-kubecost/0.25.0/defaults/kustomization.yaml
  services/centralized-kubecost/0.25.0/kustomization.yaml
  services/centralized-kubecost/0.25.0/post-install-jobs.yaml
  services/centralized-kubecost/0.25.0/post-install-jobs/post-install-jobs.yaml
  services/centralized-kubecost/0.25.0/release.yaml
  services/centralized-kubecost/0.25.0/release/release.yaml
  services/kommander/0.3.0/defaults/cm.yaml
  services/kubecost/0.25.0/defaults/cm.yaml
  services/kubecost/0.25.0/defaults/kustomization.yaml
  services/kubecost/0.25.0/kubecost.yaml
  services/kubecost/0.25.0/kustomization.yaml
Labels: ready-for-review, ok-to-test

#417 feat: Bump kommander versions post release
  services/kommander-appmanagement/0.2.2/defaults/cm.yaml
  services/kommander-appmanagement/0.2.2/defaults/kustomization.yaml
  services/kommander-appmanagement/0.2.2/kommander-appmanagement.yaml
  services/kommander-appmanagement/0.2.2/kustomization.yaml
  services/kommander/0.2.2/defaults/cm.yaml
  services/kommander/0.2.2/defaults/kustomization.yaml
  services/kommander/0.2.2/dynamic-helmreleases/README.txt
  services/kommander/0.2.2/dynamic-helmreleases/cluster-observer/cluster-observer.yaml
  services/kommander/0.2.2/dynamic-helmreleases/cluster-observer/kustomization.yaml
  services/kommander/0.2.2/dynamic-helmreleases/mtls-proxy/kustomization.yaml
  services/kommander/0.2.2/dynamic-helmreleases/mtls-proxy/mtls-proxy.yaml
  services/kommander/0.2.2/kommander.yaml
  services/kommander/0.2.2/kustomization.yaml
Labels: ready-for-review, ok-to-test
