Repository mesosphere/kommander-applications, pull requests merged in 2022-09, with the labels that each got.

#585 feat: collect Loki distributor metrics
  services/grafana-loki/0.48.4/defaults/cm.yaml
Labels: ready-for-review, ok-to-test, auto-backport, backport-to-release-2.3, size/XS

#563 feat: Bump prometheus-adapter to 3.4.0
  services/kommander/0.4.0/defaults/cm.yaml
  services/kube-prometheus-stack/34.9.3/defaults/cm.yaml
  services/prometheus-adapter/2.17.1/defaults/cm.yaml
  services/prometheus-adapter/2.17.1/kustomization.yaml
  services/prometheus-adapter/3.4.0/defaults/cm.yaml
  services/prometheus-adapter/3.4.0/defaults/kustomization.yaml
  services/prometheus-adapter/3.4.0/helmrelease/prometheus-adapter.yaml
  services/prometheus-adapter/3.4.0/kustomization.yaml
  services/prometheus-adapter/3.4.0/pre-upgrade/delete-prometheus-adapter-deployment.yaml
  services/prometheus-adapter/3.4.0/prometheus-adapter-helmrelease.yaml
  services/prometheus-adapter/3.4.0/prometheus-adapter-pre-upgrade.yaml
Labels: ready-for-review, ok-to-test, size/L

#590 fix: Add reloader annotations for fluentd/fluentbit
  services/logging-operator/3.17.8/defaults/cm.yaml
  services/logging-operator/3.17.8/defaults/kustomization.yaml
  services/logging-operator/3.17.8/grafana-dashboards/kustomization.yaml
  services/logging-operator/3.17.8/grafana-dashboards/logging-operator.json
  services/logging-operator/3.17.8/kustomization.yaml
  services/logging-operator/3.17.8/logging-operator-logging.yaml
  services/logging-operator/3.17.8/logging-operator.yaml
Labels: ready-for-review, do-not-merge, ok-to-test, needs-backport, auto-backport, backport-to-release-2.2, backport-to-release-2.3, size/S

#592 ci: add linters to check if title is semantic commit message
  .github/workflows/lint-pr.yaml
Labels: ready-for-review, ok-to-test, size/S

#589 feat: use interval flush_mode for fluentd
  services/logging-operator/3.17.8/defaults/cm.yaml
  services/project-logging/1.0.1/defaults/cm.yaml
  services/project-logging/1.0.1/defaults/kustomization.yaml
  services/project-logging/1.0.1/kustomization.yaml
  services/project-logging/1.0.1/project-logging.yaml
Labels: ready-for-review, do-not-merge, ok-to-test, needs-backport, auto-backport, backport-to-release-2.2, backport-to-release-2.3, size/XS

#596 [backport] [release-2.2] fix: Add reloader annotations for fluentd/fluentbit
  services/logging-operator/3.17.3/defaults/cm.yaml
  services/logging-operator/3.17.3/defaults/kustomization.yaml
  services/logging-operator/3.17.3/kustomization.yaml
  services/logging-operator/3.17.3/logging-operator-logging.yaml
  services/logging-operator/3.17.3/logging-operator.yaml
Labels: ready-for-review, ok-to-test, backport-pr

#598 build: Add workflow to create kommander branch
  .github/workflows/kommander-branch.yaml
Labels: ready-for-review, ok-to-test, size/M

#597 chore: bump project-logging to 1.0.3
  services/project-logging/1.0.3/defaults/cm.yaml
  services/project-logging/1.0.3/defaults/kustomization.yaml
  services/project-logging/1.0.3/kustomization.yaml
  services/project-logging/1.0.3/project-logging.yaml
Labels: ready-for-review, ok-to-test, size/XS

#605 build: Improve kommander branch workflow
  .github/workflows/kommander-branch.yaml
Labels: ready-for-review, ok-to-test, size/S, open-kommander-pr

#588 fix: update loki dashboard queries
  services/grafana-loki/0.48.4/grafana-dashboards/loki-deletion.json
  services/grafana-loki/0.48.4/grafana-dashboards/loki-reads-resources.json
  services/grafana-loki/0.48.4/grafana-dashboards/loki-retention.json
  services/grafana-loki/0.48.4/grafana-dashboards/loki-writes-resources.json
Labels: ready-for-review, ok-to-test, size/XL

#608 chore: Switch cert-manager helmrelease order
  services/cert-manager/1.7.1/release/release.yaml
Labels: ready-for-review, ok-to-test, size/S, open-kommander-pr

#604 chore: Bump DKP Insights to v0.3.0-dev
  services/dkp-insights-management/0.3.0/defaults/cm.yaml
  services/dkp-insights-management/0.3.0/defaults/kustomization.yaml
  services/dkp-insights-management/0.3.0/helmrelease.yaml
  services/dkp-insights-management/0.3.0/helmrelease/helmrelease.yaml
  services/dkp-insights-management/0.3.0/kustomization.yaml
Labels: ready-for-review, ok-to-test, size/S

#587 feat: collect project Loki distributor metrics
  services/grafana-loki/0.48.5/defaults/cm.yaml
  services/grafana-loki/0.48.5/defaults/kustomization.yaml
  services/grafana-loki/0.48.5/grafana-dashboards-logging/kustomization.yaml
  services/grafana-loki/0.48.5/grafana-dashboards-logging/logging-loki-dashboard.json
  services/grafana-loki/0.48.5/grafana-dashboards/grafana-loki.json
  services/grafana-loki/0.48.5/grafana-dashboards/kustomization.yaml
  services/grafana-loki/0.48.5/grafana-dashboards/loki-chunks.json
  services/grafana-loki/0.48.5/grafana-dashboards/loki-deletion.json
  services/grafana-loki/0.48.5/grafana-dashboards/loki-reads-resources.json
  services/grafana-loki/0.48.5/grafana-dashboards/loki-retention.json
  services/grafana-loki/0.48.5/grafana-dashboards/loki-writes-resources.json
  services/grafana-loki/0.48.5/grafana-loki.yaml
  services/grafana-loki/0.48.5/kustomization.yaml
  services/grafana-loki/0.48.5/minio.yaml
  services/project-grafana-loki/0.48.5/defaults/cm.yaml
  services/project-grafana-loki/0.48.5/defaults/kustomization.yaml
  services/project-grafana-loki/0.48.5/grafana-dashboards-logging/kustomization.yaml
  services/project-grafana-loki/0.48.5/grafana-dashboards-logging/logging-loki-dashboard.json
  services/project-grafana-loki/0.48.5/kustomization.yaml
  services/project-grafana-loki/0.48.5/minio.yaml
  services/project-grafana-loki/0.48.5/project-grafana-loki.yaml
Labels: ready-for-review, do-not-merge, ok-to-test, needs-backport, auto-backport, backport-to-release-2.3, size/S

#610 build: Run lint pr workflow on ubuntu-latest
  .github/workflows/lint-pr.yaml
Labels: ready-for-review, size/XS

#603 feat: Upgrade grafana and kube-prometheus-stack
  services/centralized-grafana/40.0.0/centralized-grafana.yaml
  services/centralized-grafana/40.0.0/defaults/cm.yaml
  services/centralized-grafana/40.0.0/defaults/kustomization.yaml
  services/centralized-grafana/40.0.0/grafana-dashboards/global-overview.json
  services/centralized-grafana/40.0.0/grafana-dashboards/kustomization.yaml
  services/centralized-grafana/40.0.0/kustomization.yaml
  services/grafana-logging/6.38.1/defaults/cm.yaml
  services/grafana-logging/6.38.1/defaults/kustomization.yaml
  services/grafana-logging/6.38.1/grafana.yaml
  services/grafana-logging/6.38.1/kustomization.yaml
  services/kommander/0.4.0/defaults/cm.yaml
  services/kube-prometheus-stack/40.0.0/defaults/cm.yaml
  services/kube-prometheus-stack/40.0.0/defaults/kustomization.yaml
  services/kube-prometheus-stack/40.0.0/grafana-dashboards/calico.json
  services/kube-prometheus-stack/40.0.0/grafana-dashboards/flux-cluster-stats.json
  services/kube-prometheus-stack/40.0.0/grafana-dashboards/flux-control-plane.json
  services/kube-prometheus-stack/40.0.0/grafana-dashboards/kustomization.yaml
  services/kube-prometheus-stack/40.0.0/helmrelease.yaml
  services/kube-prometheus-stack/40.0.0/helmrelease/kube-prometheus-stack.yaml
  services/kube-prometheus-stack/40.0.0/kustomization.yaml
  services/kube-prometheus-stack/40.0.0/pre-upgrade.yaml
  services/kube-prometheus-stack/40.0.0/pre-upgrade/delete-node-exporter-daemonset.yaml
  services/kube-prometheus-stack/metadata.yaml
  services/project-grafana-logging/6.38.1/defaults/cm.yaml
  services/project-grafana-logging/6.38.1/defaults/kustomization.yaml
  services/project-grafana-logging/6.38.1/kustomization.yaml
  services/project-grafana-logging/6.38.1/project-grafana.yaml
Labels: ready-for-review, size/L, open-kommander-pr

#616 build: Add workflow for stale prs
  .github/workflows/stale-prs.yaml
Labels: ready-for-review, size/S

#606 feat: Add new nvidia-gpu-operator app
  common/helm-repositories/kustomization.yaml
  common/helm-repositories/nvidia.yaml
  services/nvidia-gpu-operator/1.11.1/defaults/cm.yaml
  services/nvidia-gpu-operator/1.11.1/defaults/kustomization.yaml
  services/nvidia-gpu-operator/1.11.1/helmrelease.yaml
  services/nvidia-gpu-operator/1.11.1/helmrelease/nvidia.yaml
  services/nvidia-gpu-operator/1.11.1/kustomization.yaml
  services/nvidia-gpu-operator/metadata.yaml
Labels: ready-for-review, ok-to-test, size/L, open-kommander-pr

#613 [release-2.3][backport] feat: collect project Loki distributor metrics
  services/project-grafana-loki/0.48.5/defaults/cm.yaml
  services/project-grafana-loki/0.48.5/defaults/kustomization.yaml
  services/project-grafana-loki/0.48.5/kustomization.yaml
  services/project-grafana-loki/0.48.5/minio.yaml
  services/project-grafana-loki/0.48.5/project-grafana-loki.yaml
Labels: ready-for-review, do-not-merge, ok-to-test, backport-pr, open-kommander-pr

#619 fix: Calico dashboard
  services/kube-prometheus-stack/40.0.0/grafana-dashboards/calico.json
Labels: ready-for-review, ok-to-test, size/XXL

#618 build: Improve workflows to support release branches
  .github/workflows/kommander-branch.yaml
  .github/workflows/kommander-revert-kapps-ref.yaml
Labels: ready-for-review, size/S, open-kommander-pr

#620 build: Add automatic rebase workflow
  .github/workflows/rebase.yaml
Labels: ready-for-review, size/S

#623 build: Fix revert kapps workflow to work with release branches
  .github/workflows/kommander-branch.yaml
  .github/workflows/kommander-revert-kapps-ref.yaml
Labels: ready-for-review, size/S, open-kommander-pr

#617 build: Add workflow to open kommander pr
  .github/workflows/kommander-branch.yaml
  .github/workflows/kommander-revert-kapps-ref.yaml
Labels: ready-for-review, backport-pr, auto-backport, backport-to-release-2.2, backport-to-release-2.1, open-kommander-pr

#627 feat: logging stack stress dashboard
  services/logging-operator/3.17.8/grafana-dashboards/kustomization.yaml
  services/logging-operator/3.17.8/grafana-dashboards/logging-stack-stress.json
Labels: ready-for-review, ok-to-test, size/XXL

#628 Bump kommander service version to 0.2.3
  services/kommander/0.2.3/defaults/cm.yaml
  services/kommander/0.2.3/defaults/kustomization.yaml
  services/kommander/0.2.3/dynamic-helmreleases/README.txt
  services/kommander/0.2.3/dynamic-helmreleases/cluster-observer/cluster-observer.yaml
  services/kommander/0.2.3/dynamic-helmreleases/cluster-observer/kustomization.yaml
  services/kommander/0.2.3/dynamic-helmreleases/mtls-proxy/kustomization.yaml
  services/kommander/0.2.3/dynamic-helmreleases/mtls-proxy/mtls-proxy.yaml
  services/kommander/0.2.3/kommander.yaml
  services/kommander/0.2.3/kustomization.yaml
Labels: ready-for-review

#629 feat: adds a default config for daily cluster for gpus
  services/nvidia-gpu-operator/1.11.1/defaults/cm.yaml
  services/nvidia-gpu-operator/1.11.1/grafana-dashboards/gpu-operator.json
  services/nvidia-gpu-operator/1.11.1/grafana-dashboards/kustomization.yaml
  services/nvidia-gpu-operator/1.11.1/kustomization.yaml
Labels: ready-for-review, ok-to-test, size/XXL, open-kommander-pr

#602 ci: Reimplemented mergebot
  .github/workflows/mergebot.yml
Labels: ready-for-review, ok-to-test, size/M

#658 chore: bump dkp-bloodhound to 0.7.1
  make/validate.mk
Labels: ready-for-review, ok-to-test, needs-backport, auto-backport, backport-to-release-2.3, size/XS

#667 feat: bump kommander chart versions to v2.3.1
  services/kommander-appmanagement/0.3.2/kommander-appmanagement.yaml
  services/kommander/0.3.2/kommander.yaml
Labels: ready-for-review, ok-to-test

#668 chore: bump gatekeeper to 3.8.3
  services/gatekeeper/3.8.3/constraints.yaml
  services/gatekeeper/3.8.3/constraints/enforce-helmrelease-sa.yaml
  services/gatekeeper/3.8.3/constraints/enforce-kustomization-sa.yaml
  services/gatekeeper/3.8.3/constrainttemplates.yaml
  services/gatekeeper/3.8.3/constrainttemplates/enforce-sa-constrainttemplate.yaml
  services/gatekeeper/3.8.3/defaults/cm.yaml
  services/gatekeeper/3.8.3/defaults/kustomization.yaml
  services/gatekeeper/3.8.3/kustomization.yaml
  services/gatekeeper/3.8.3/release.yaml
  services/gatekeeper/3.8.3/release/kustomization.yaml
  services/gatekeeper/3.8.3/release/release.yaml
  services/gatekeeper/bootstrap/kustomization.yaml
  services/kommander/0.4.0/defaults/cm.yaml
Labels: ready-for-review, ok-to-test, size/S

#624 feat: add `rook-ceph` and `rook-ceph-cluster` services
  common/helm-repositories/kustomization.yaml
  common/helm-repositories/rook-ceph.yaml
  services/rook-ceph-cluster/1.10.1/defaults/cm.yaml
  services/rook-ceph-cluster/1.10.1/defaults/kustomization.yaml
  services/rook-ceph-cluster/1.10.1/helmrelease/dashboard-cm.yaml
  services/rook-ceph-cluster/1.10.1/helmrelease/helmrelease.yaml
  services/rook-ceph-cluster/1.10.1/helmrelease/kustomization.yaml
  services/rook-ceph-cluster/1.10.1/kustomization.yaml
  services/rook-ceph-cluster/1.10.1/rook-ceph-cluster.yaml
  services/rook-ceph-cluster/metadata.yaml
  services/rook-ceph/1.10.1/defaults/cm.yaml
  services/rook-ceph/1.10.1/defaults/kustomization.yaml
  services/rook-ceph/1.10.1/helmrelease/helmrelease.yaml
  services/rook-ceph/1.10.1/helmrelease/kustomization.yaml
  services/rook-ceph/1.10.1/kustomization.yaml
  services/rook-ceph/1.10.1/rook-ceph.yaml
  services/rook-ceph/metadata.yaml
  services/traefik/10.9.3/defaults/cm.yaml
Labels: ready-for-review, ok-to-test, size/L

#669 chore: Bump DKP Insights to v0.3.0-beta.1
  services/dkp-insights-management/0.3.0/defaults/cm.yaml
  services/dkp-insights-management/0.3.0/helmrelease/helmrelease.yaml
Labels: ready-for-review, ok-to-test, size/XS

#671 fix: explicitly set null for the sc
  services/rook-ceph-cluster/1.10.1/defaults/cm.yaml
Labels: ready-for-review, ok-to-test, size/XS
