Repository mesosphere/kommander-applications, pull requests merged in 2022-04, with the labels that each got.

#285 fix: Bump fluentbit and logging-operator to use same fluentbit image
  services/fluent-bit/0.19.22/defaults/cm.yaml
  services/fluent-bit/0.19.22/defaults/kustomization.yaml
  services/fluent-bit/0.19.22/fluent-bit.yaml
  services/fluent-bit/0.19.22/kustomization.yaml
  services/logging-operator/3.17.3/defaults/cm.yaml
  services/logging-operator/3.17.3/defaults/kustomization.yaml
  services/logging-operator/3.17.3/kustomization.yaml
  services/logging-operator/3.17.3/logging-operator-logging.yaml
  services/logging-operator/3.17.3/logging-operator.yaml
Labels: ok-to-test

#288 [release-2.2] bump kommander charts to rc.4
  make/release.mk
  services/fluent-bit/0.19.22/defaults/cm.yaml
  services/fluent-bit/0.19.22/defaults/kustomization.yaml
  services/fluent-bit/0.19.22/fluent-bit.yaml
  services/fluent-bit/0.19.22/kustomization.yaml
  services/kommander-appmanagement/0.2.0/kommander-appmanagement.yaml
  services/kommander/0.2.0/defaults/cm.yaml
  services/kommander/0.2.0/kommander.yaml
  services/logging-operator/3.17.3/defaults/cm.yaml
  services/logging-operator/3.17.3/defaults/kustomization.yaml
  services/logging-operator/3.17.3/kustomization.yaml
  services/logging-operator/3.17.3/logging-operator-logging.yaml
  services/logging-operator/3.17.3/logging-operator.yaml
Labels: ready-for-review, ok-to-test

#289 fix: Logging operator upgrade process
  services/logging-operator/3.17.3/logging-operator-logging.yaml
  services/logging-operator/3.17.3/logging-operator.yaml
Labels: ready-for-review, ok-to-test

#290 release v2.2.0 rc.5
  services/kommander-appmanagement/0.2.0/kommander-appmanagement.yaml
  services/kommander/0.2.0/kommander.yaml
  services/logging-operator/3.17.3/logging-operator-logging.yaml
  services/logging-operator/3.17.3/logging-operator.yaml
Labels: ready-for-review, ok-to-test

#295 feat: Release DKP-Insights v0.1.3
  services/dkp-insights-management/0.1.3/defaults/cm.yaml
  services/dkp-insights-management/0.1.3/defaults/kustomization.yaml
  services/dkp-insights-management/0.1.3/helmrelease.yaml
  services/dkp-insights-management/0.1.3/helmrelease/helmrelease.yaml
  services/dkp-insights-management/0.1.3/kustomization.yaml
Labels: ready-for-review, ok-to-test

#296 feat: Bump knative, use chart version as app version
  services/knative/0.3.9/defaults/cm.yaml
  services/knative/0.3.9/defaults/kustomization.yaml
  services/knative/0.3.9/knative-serving.yaml
  services/knative/0.3.9/kustomization.yaml
Labels: ready-for-review, ok-to-test

#294 chore: Bump kubectl images to latest release
  services/centralized-kubecost/0.23.3/defaults/cm.yaml
  services/centralized-kubecost/0.23.3/post-install-jobs/post-install-jobs.yaml
  services/centralized-kubecost/0.23.3/release/release.yaml
  services/gatekeeper/3.7.0/cleanup/cert-cleanup.yaml
  services/jaeger/2.29.0/pre-upgrade/delete-jaeger-deployment.yaml
  services/kube-prometheus-stack/33.1.5/defaults/cm.yaml
  services/kubecost/0.23.3/defaults/cm.yaml
  services/minio-operator/4.4.10/minio-operator-pre-upgrade/delete-minio-operator-deployment.yaml
  services/thanos/0.4.6/thanos.yaml
  services/traefik/10.9.1/defaults/cm.yaml
  services/velero/3.2.0/defaults/cm.yaml
  services/velero/3.2.0/defaults/kustomization.yaml
  services/velero/3.2.0/grafana-dashboards/kustomization.yaml
  services/velero/3.2.0/grafana-dashboards/velero.json
  services/velero/3.2.0/kustomization.yaml
  services/velero/3.2.0/velero.yaml
Labels: ready-for-review, ok-to-test

#299 [release-2.2] revert kubectl bumps
  services/centralized-kubecost/0.23.3/defaults/cm.yaml
  services/centralized-kubecost/0.23.3/post-install-jobs/post-install-jobs.yaml
  services/centralized-kubecost/0.23.3/release/release.yaml
  services/gatekeeper/3.7.0/cleanup/cert-cleanup.yaml
  services/jaeger/2.29.0/pre-upgrade/delete-jaeger-deployment.yaml
  services/kube-prometheus-stack/33.1.5/defaults/cm.yaml
  services/kubecost/0.23.3/defaults/cm.yaml
  services/minio-operator/4.4.10/minio-operator-pre-upgrade/delete-minio-operator-deployment.yaml
  services/thanos/0.4.6/thanos.yaml
  services/traefik/10.9.1/defaults/cm.yaml
  services/velero/3.1.5/defaults/cm.yaml
  services/velero/3.1.5/defaults/kustomization.yaml
  services/velero/3.1.5/grafana-dashboards/kustomization.yaml
  services/velero/3.1.5/grafana-dashboards/velero.json
  services/velero/3.1.5/kustomization.yaml
  services/velero/3.1.5/velero.yaml
Labels: ready-for-review, ok-to-test

#300 Revert "chore: Bump kubectl images to latest release (#294)"
  services/centralized-kubecost/0.23.3/defaults/cm.yaml
  services/centralized-kubecost/0.23.3/post-install-jobs/post-install-jobs.yaml
  services/centralized-kubecost/0.23.3/release/release.yaml
  services/gatekeeper/3.7.0/cleanup/cert-cleanup.yaml
  services/jaeger/2.29.0/pre-upgrade/delete-jaeger-deployment.yaml
  services/kube-prometheus-stack/33.1.5/defaults/cm.yaml
  services/kubecost/0.23.3/defaults/cm.yaml
  services/minio-operator/4.4.10/minio-operator-pre-upgrade/delete-minio-operator-deployment.yaml
  services/thanos/0.4.6/thanos.yaml
  services/traefik/10.9.1/defaults/cm.yaml
  services/velero/3.1.5/defaults/cm.yaml
  services/velero/3.1.5/defaults/kustomization.yaml
  services/velero/3.1.5/grafana-dashboards/kustomization.yaml
  services/velero/3.1.5/grafana-dashboards/velero.json
  services/velero/3.1.5/kustomization.yaml
  services/velero/3.1.5/velero.yaml
Labels: ready-for-review, ok-to-test

#302 [release-2.2] cherry-pick insights fix
  services/dkp-insights-management/0.1.3/defaults/cm.yaml
  services/dkp-insights-management/0.1.3/defaults/kustomization.yaml
  services/dkp-insights-management/0.1.3/helmrelease.yaml
  services/dkp-insights-management/0.1.3/helmrelease/helmrelease.yaml
  services/dkp-insights-management/0.1.3/kustomization.yaml
Labels: ready-for-review, ok-to-test

#276 chore: remove redundant CA cert
  services/cert-manager/1.7.1/root-ca/root-ca.yaml
Labels: ready-for-review, ok-to-test

#303 fix: tfa should reload on cm change
  services/traefik-forward-auth/0.3.6/defaults/cm.yaml
Labels: ready-for-review, ok-to-test, needs-backport

#287 build: bump flux version in default apps
  hack/flux/update-flux.sh
Labels: ready-for-review, ok-to-test

#306 fix: Add crd policy to kommander HelmReleases
  services/kommander-appmanagement/0.2.0/kommander-appmanagement.yaml
  services/kommander/0.2.0/kommander.yaml
Labels: ready-for-review, ok-to-test, needs-backport

#308 feat: Release DKP-Insights v0.1.4
  services/dkp-insights-management/0.1.4/defaults/cm.yaml
  services/dkp-insights-management/0.1.4/defaults/kustomization.yaml
  services/dkp-insights-management/0.1.4/helmrelease.yaml
  services/dkp-insights-management/0.1.4/helmrelease/helmrelease.yaml
  services/dkp-insights-management/0.1.4/kustomization.yaml
Labels: ready-for-review, ok-to-test, needs-backport

#301 fix: Add ttl to jobs
  services/centralized-kubecost/0.23.3/post-install-jobs/post-install-jobs.yaml
  services/centralized-kubecost/0.23.3/release/release.yaml
  services/gatekeeper/3.7.0/cleanup/cert-cleanup.yaml
  services/grafana-loki/0.33.2/minio.yaml
  services/jaeger/2.29.0/pre-upgrade/delete-jaeger-deployment.yaml
  services/minio-operator/4.4.10/minio-operator-pre-upgrade/delete-minio-operator-deployment.yaml
  services/project-grafana-loki/0.33.2/minio.yaml
  services/thanos/0.4.6/thanos.yaml
Labels: ready-for-review, ok-to-test, needs-backport

#309 fix: Update appversions
  services/centralized-grafana/33.1.5/centralized-grafana.yaml
  services/grafana-logging/6.22.0/grafana.yaml
  services/jaeger/2.29.0/helmrelease/release.yaml
  services/karma/2.0.1/karma.yaml
  services/kiali/1.47.0/kiali.yaml
  services/kube-prometheus-stack/33.1.5/kube-prometheus-stack.yaml
  services/kubecost/0.23.3/kubecost.yaml
  services/kubernetes-dashboard/5.1.1/kubernetes-dashboard.yaml
  services/minio-operator/4.4.10/minio-operator-helmrelease/release.yaml
  services/traefik/10.9.1/traefik.yaml
Labels: ready-for-review, ok-to-test, needs-backport

#314 [release-2.2] bump kommander charts to rc.7
  services/kommander-appmanagement/0.2.0/kommander-appmanagement.yaml
  services/kommander/0.2.0/kommander.yaml
Labels: ready-for-review, do-not-merge, ok-to-test

#317 feat: Bump cluster-observer to 1.0.3
  services/kommander/0.2.0/dynamic-helmreleases/cluster-observer/cluster-observer.yaml
Labels: ok-to-test, needs-backport, do-not-merge/testing

#319 [release-2.2] feat: Bump kommander charts to v2.2.0-rc.9
  services/kommander-appmanagement/0.2.0/kommander-appmanagement.yaml
  services/kommander/0.2.0/kommander.yaml
Labels: ready-for-review, do-not-merge, ok-to-test

#320 build: Remove prefix from git archive
  .gitignore
  make/release.mk
Labels: ready-for-review, ok-to-test

#322 Revert "fix: Add ttl to jobs (#301)"
  services/centralized-kubecost/0.23.3/post-install-jobs/post-install-jobs.yaml
  services/centralized-kubecost/0.23.3/release/release.yaml
  services/gatekeeper/3.7.0/cleanup/cert-cleanup.yaml
  services/grafana-loki/0.33.2/minio.yaml
  services/jaeger/2.29.0/pre-upgrade/delete-jaeger-deployment.yaml
  services/minio-operator/4.4.10/minio-operator-pre-upgrade/delete-minio-operator-deployment.yaml
  services/project-grafana-loki/0.33.2/minio.yaml
  services/thanos/0.4.6/thanos.yaml
Labels: ready-for-review, ok-to-test, needs-backport

#324 [release-2.2] feat: Bump kommander charts to v2.2.0-rc.10
  services/kommander-appmanagement/0.2.0/kommander-appmanagement.yaml
  services/kommander/0.2.0/kommander.yaml
Labels: ready-for-review, ok-to-test

#327 [release-2.2] feat: Bump kommander charts to rc.11
  services/kommander-appmanagement/0.2.0/kommander-appmanagement.yaml
  services/kommander/0.2.0/kommander.yaml
Labels: ready-for-review, do-not-merge, ok-to-test

#328 feat: Bump kommander charts to v2.2.0 GA
  services/kommander-appmanagement/0.2.0/kommander-appmanagement.yaml
  services/kommander/0.2.0/kommander.yaml
Labels: ready-for-review, ok-to-test

#330 fix: Produce correct tag for a daily release
  .go-tools
  make/repo.mk
Labels: ready-for-review, ok-to-test

#329 feat: Bump reloader to 0.0.110
  services/kommander/0.2.0/defaults/cm.yaml
  services/reloader/0.0.110/defaults/cm.yaml
  services/reloader/0.0.110/defaults/kustomization.yaml
  services/reloader/0.0.110/kustomization.yaml
  services/reloader/0.0.110/reloader.yaml
Labels: ready-for-review, do-not-merge, ok-to-test

#336 fix: Fetch all tags before checking the most recent
  make/repo.mk
Labels: ready-for-review, ok-to-test

#326 feat: Upgrade flux to 0.28.5
  .tool-versions
  services/kommander-flux/0.27.4/templates/apiextensions.k8s.io_v1_customresourcedefinition_buckets.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.27.4/templates/apiextensions.k8s.io_v1_customresourcedefinition_gitrepositories.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.27.4/templates/apiextensions.k8s.io_v1_customresourcedefinition_helmcharts.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.27.4/templates/apiextensions.k8s.io_v1_customresourcedefinition_helmrepositories.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.28.5/defaults/cm.yaml
  services/kommander-flux/0.28.5/defaults/kustomization.yaml
  services/kommander-flux/0.28.5/kustomization.yaml
  services/kommander-flux/0.28.5/patch-proxy-env-vars.yaml
  services/kommander-flux/0.28.5/patch-source-ctrl-network-policy.yaml
  services/kommander-flux/0.28.5/templates/apiextensions.k8s.io_v1_customresourcedefinition_alerts.notification.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.28.5/templates/apiextensions.k8s.io_v1_customresourcedefinition_buckets.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.28.5/templates/apiextensions.k8s.io_v1_customresourcedefinition_gitrepositories.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.28.5/templates/apiextensions.k8s.io_v1_customresourcedefinition_helmcharts.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.28.5/templates/apiextensions.k8s.io_v1_customresourcedefinition_helmreleases.helm.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.28.5/templates/apiextensions.k8s.io_v1_customresourcedefinition_helmrepositories.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.28.5/templates/apiextensions.k8s.io_v1_customresourcedefinition_kustomizations.kustomize.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.28.5/templates/apiextensions.k8s.io_v1_customresourcedefinition_providers.notification.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.28.5/templates/apiextensions.k8s.io_v1_customresourcedefinition_receivers.notification.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.28.5/templates/apps_v1_deployment_helm-controller.yaml
  services/kommander-flux/0.28.5/templates/apps_v1_deployment_kustomize-controller.yaml
  services/kommander-flux/0.28.5/templates/apps_v1_deployment_notification-controller.yaml
  services/kommander-flux/0.28.5/templates/apps_v1_deployment_source-controller.yaml
  services/kommander-flux/0.28.5/templates/kustomization.yaml
  services/kommander-flux/0.28.5/templates/networking.k8s.io_v1_networkpolicy_allow-egress.yaml
  services/kommander-flux/0.28.5/templates/networking.k8s.io_v1_networkpolicy_allow-scraping.yaml
  services/kommander-flux/0.28.5/templates/networking.k8s.io_v1_networkpolicy_allow-source.yaml
  services/kommander-flux/0.28.5/templates/networking.k8s.io_v1_networkpolicy_allow-webhooks.yaml
  services/kommander-flux/0.28.5/templates/rbac.authorization.k8s.io_v1_clusterrole_crd-controller-kommander-flux.yaml
  services/kommander-flux/0.28.5/templates/rbac.authorization.k8s.io_v1_clusterrolebinding_cluster-reconciler-kommander-flux.yaml
  services/kommander-flux/0.28.5/templates/rbac.authorization.k8s.io_v1_clusterrolebinding_crd-controller-kommander-flux.yaml
  services/kommander-flux/0.28.5/templates/v1_namespace_kommander-flux.yaml
  services/kommander-flux/0.28.5/templates/v1_service_notification-controller.yaml
  services/kommander-flux/0.28.5/templates/v1_service_source-controller.yaml
  services/kommander-flux/0.28.5/templates/v1_service_webhook-receiver.yaml
  services/kommander-flux/0.28.5/templates/v1_serviceaccount_helm-controller.yaml
  services/kommander-flux/0.28.5/templates/v1_serviceaccount_kustomize-controller.yaml
  services/kommander-flux/0.28.5/templates/v1_serviceaccount_notification-controller.yaml
  services/kommander-flux/0.28.5/templates/v1_serviceaccount_source-controller.yaml
  services/kommander/0.2.0/defaults/cm.yaml
Labels: ready-for-review, ok-to-test, needs-backport, slack-notify

#338 feat: Bump default kommander to a new daily release
  services/kommander-appmanagement/0.2.0/kommander-appmanagement.yaml
  services/kommander/0.2.0/kommander.yaml
Labels: ready-for-review, ok-to-test, do-not-merge/testing

#340 build: Bump mergebot versions post 2.2.0
  mergebot-config.json
Labels: ready-for-review, ok-to-test, needs-backport

#342 mikolajb/bump to daily
  services/kommander-appmanagement/0.2.0/kommander-appmanagement.yaml
  services/kommander/0.2.0/kommander.yaml
Labels: ready-for-review, ok-to-test

#343 feat: Bump kommander version to 0.3.0
  services/kommander-appmanagement/0.3.0/defaults/cm.yaml
  services/kommander-appmanagement/0.3.0/defaults/kustomization.yaml
  services/kommander-appmanagement/0.3.0/kommander-appmanagement.yaml
  services/kommander-appmanagement/0.3.0/kustomization.yaml
  services/kommander/0.3.0/defaults/cm.yaml
  services/kommander/0.3.0/defaults/kustomization.yaml
  services/kommander/0.3.0/dynamic-helmreleases/README.txt
  services/kommander/0.3.0/dynamic-helmreleases/cluster-observer/cluster-observer.yaml
  services/kommander/0.3.0/dynamic-helmreleases/cluster-observer/kustomization.yaml
  services/kommander/0.3.0/dynamic-helmreleases/mtls-proxy/kustomization.yaml
  services/kommander/0.3.0/dynamic-helmreleases/mtls-proxy/mtls-proxy.yaml
  services/kommander/0.3.0/kommander.yaml
  services/kommander/0.3.0/kustomization.yaml
Labels: ready-for-review, ok-to-test

#344 feat: Bump kps to 34.9.0
  services/centralized-grafana/34.9.0/centralized-grafana.yaml
  services/centralized-grafana/34.9.0/defaults/cm.yaml
  services/centralized-grafana/34.9.0/defaults/kustomization.yaml
  services/centralized-grafana/34.9.0/grafana-dashboards/global-overview.json
  services/centralized-grafana/34.9.0/grafana-dashboards/kustomization.yaml
  services/centralized-grafana/34.9.0/kustomization.yaml
  services/kommander/0.3.0/defaults/cm.yaml
  services/kube-prometheus-stack/34.9.0/defaults/cm.yaml
  services/kube-prometheus-stack/34.9.0/defaults/kustomization.yaml
  services/kube-prometheus-stack/34.9.0/grafana-dashboards/calico.json
  services/kube-prometheus-stack/34.9.0/grafana-dashboards/flux-cluster-stats.json
  services/kube-prometheus-stack/34.9.0/grafana-dashboards/flux-control-plane.json
  services/kube-prometheus-stack/34.9.0/grafana-dashboards/grafana.json
  services/kube-prometheus-stack/34.9.0/grafana-dashboards/kustomization.yaml
  services/kube-prometheus-stack/34.9.0/kube-prometheus-stack.yaml
  services/kube-prometheus-stack/34.9.0/kustomization.yaml
Labels: ready-for-review, ok-to-test

#315 chore: Bump kubefed's kubectl image
  services/kubefed/0.9.1/defaults/cm.yaml
Labels: ready-for-review, ok-to-test

#337 chore: Bump minio images to latest releases
  services/grafana-loki/0.33.2/minio.yaml
  services/project-grafana-loki/0.33.2/minio.yaml
  services/velero/3.1.5/defaults/cm.yaml
Labels: ready-for-review, ok-to-test

#346 feat: Bump kommander app to 0.2.1
  services/kommander-appmanagement/0.2.1/defaults/cm.yaml
  services/kommander-appmanagement/0.2.1/defaults/kustomization.yaml
  services/kommander-appmanagement/0.2.1/kommander-appmanagement.yaml
  services/kommander-appmanagement/0.2.1/kustomization.yaml
  services/kommander/0.2.1/defaults/cm.yaml
  services/kommander/0.2.1/defaults/kustomization.yaml
  services/kommander/0.2.1/dynamic-helmreleases/README.txt
  services/kommander/0.2.1/dynamic-helmreleases/cluster-observer/cluster-observer.yaml
  services/kommander/0.2.1/dynamic-helmreleases/cluster-observer/kustomization.yaml
  services/kommander/0.2.1/dynamic-helmreleases/mtls-proxy/kustomization.yaml
  services/kommander/0.2.1/dynamic-helmreleases/mtls-proxy/mtls-proxy.yaml
  services/kommander/0.2.1/kommander.yaml
  services/kommander/0.2.1/kustomization.yaml
Labels: ready-for-review, ok-to-test

#298 chore: Set istio's kubectl image to the latest release
  services/istio/1.11.6/defaults/cm.yaml
Labels: ready-for-review, ok-to-test

#345 chore: Bump kubetunnel's kubectl image
  services/kubetunnel/0.0.12/defaults/cm.yaml
  services/kubetunnel/0.0.12/defaults/kustomization.yaml
  services/kubetunnel/0.0.12/kubetunnel.yaml
  services/kubetunnel/0.0.12/kustomization.yaml
Labels: ready-for-review, ok-to-test

#347 fix: Set CreateReplace upgrade policy on kps
  services/centralized-grafana/34.9.0/centralized-grafana.yaml
  services/kube-prometheus-stack/34.9.0/kube-prometheus-stack.yaml
  services/kube-prometheus-stack/metadata.yaml
  services/kubetunnel/0.0.12/kubetunnel.yaml
Labels: ready-for-review, ok-to-test, needs-backport

#350 fix: Prevent mutating minio-operator job during upgrade
  services/grafana-loki/0.33.2/jobs.yaml
  services/grafana-loki/0.33.2/jobs/minio.yaml
  services/grafana-loki/0.33.2/kustomization.yaml
  services/grafana-loki/0.33.2/minio.yaml
  services/project-grafana-loki/0.33.2/jobs.yaml
  services/project-grafana-loki/0.33.2/jobs/minio.yaml
  services/project-grafana-loki/0.33.2/kustomization.yaml
  services/project-grafana-loki/0.33.2/minio.yaml
Labels: ready-for-review, ok-to-test, needs-backport

#351 fix: Upgrade minio-operator
  services/grafana-loki/0.33.2/jobs/minio.yaml
  services/grafana-loki/0.33.2/kustomization.yaml
  services/grafana-loki/0.33.2/minio.yaml
  services/minio-operator/4.4.10/minio-operator-pre-upgrade.yaml
  services/minio-operator/4.4.10/minio-tenant-helmrelease.yaml
  services/minio-operator/4.4.16/defaults/cm.yaml
  services/minio-operator/4.4.16/defaults/kustomization.yaml
  services/minio-operator/4.4.16/kustomization.yaml
  services/minio-operator/4.4.16/minio-operator-helmrelease.yaml
  services/minio-operator/4.4.16/minio-operator-helmrelease/release.yaml
  services/minio-operator/4.4.16/minio-operator-pre-upgrade.yaml
  services/minio-operator/4.4.16/minio-operator-pre-upgrade/delete-minio-operator-deployment.yaml
  services/minio-operator/4.4.16/minio-tenant-helmrelease.yaml
  services/minio-operator/4.4.16/minio-tenant-helmrelease/release.yaml
  services/project-grafana-loki/0.33.2/jobs/minio.yaml
  services/project-grafana-loki/0.33.2/kustomization.yaml
  services/project-grafana-loki/0.33.2/minio.yaml
Labels: ready-for-review, ok-to-test

#357 chore: logs published url for the release
  make/release.mk
Labels: ready-for-review, ok-to-test

#361 fix: Bump kiali to 1.49.0 to mitigate CVEs
  services/kiali/1.49.0/defaults/cm.yaml
  services/kiali/1.49.0/defaults/kustomization.yaml
  services/kiali/1.49.0/kiali.yaml
  services/kiali/1.49.0/kustomization.yaml
Labels: ready-for-review, ok-to-test, needs-backport

#363 fix: Bump external-dns to 6.2.7
  services/external-dns/6.2.7/defaults/cm.yaml
  services/external-dns/6.2.7/defaults/kustomization.yaml
  services/external-dns/6.2.7/external-dns.yaml
  services/external-dns/6.2.7/kustomization.yaml
Labels: ready-for-review, ok-to-test, do-not-merge/testing

#366 feat: notify in slack about repo tarball release
  make/ci.mk
  make/release.mk
Labels: ready-for-review, ok-to-test

#166 feat: Upgrade loki-distributed to 0.48.3
  services/grafana-loki/0.48.3/defaults/cm.yaml
  services/grafana-loki/0.48.3/defaults/kustomization.yaml
  services/grafana-loki/0.48.3/grafana-loki.yaml
  services/grafana-loki/0.48.3/kustomization.yaml
  services/grafana-loki/0.48.3/minio.yaml
  services/project-grafana-loki/0.48.3/defaults/cm.yaml
  services/project-grafana-loki/0.48.3/defaults/kustomization.yaml
  services/project-grafana-loki/0.48.3/kustomization.yaml
  services/project-grafana-loki/0.48.3/minio.yaml
  services/project-grafana-loki/0.48.3/project-grafana-loki.yaml
Labels: ready-for-review, ok-to-test

#367 feat: Upgrade flux to 0.29.4
  .tool-versions
  services/kommander-flux/0.29.4/defaults/cm.yaml
  services/kommander-flux/0.29.4/defaults/kustomization.yaml
  services/kommander-flux/0.29.4/kustomization.yaml
  services/kommander-flux/0.29.4/patch-proxy-env-vars.yaml
  services/kommander-flux/0.29.4/patch-source-ctrl-network-policy.yaml
  services/kommander-flux/0.29.4/templates/apiextensions.k8s.io_v1_customresourcedefinition_alerts.notification.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.29.4/templates/apiextensions.k8s.io_v1_customresourcedefinition_buckets.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.29.4/templates/apiextensions.k8s.io_v1_customresourcedefinition_gitrepositories.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.29.4/templates/apiextensions.k8s.io_v1_customresourcedefinition_helmcharts.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.29.4/templates/apiextensions.k8s.io_v1_customresourcedefinition_helmreleases.helm.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.29.4/templates/apiextensions.k8s.io_v1_customresourcedefinition_helmrepositories.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.29.4/templates/apiextensions.k8s.io_v1_customresourcedefinition_kustomizations.kustomize.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.29.4/templates/apiextensions.k8s.io_v1_customresourcedefinition_providers.notification.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.29.4/templates/apiextensions.k8s.io_v1_customresourcedefinition_receivers.notification.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.29.4/templates/apps_v1_deployment_helm-controller.yaml
  services/kommander-flux/0.29.4/templates/apps_v1_deployment_kustomize-controller.yaml
  services/kommander-flux/0.29.4/templates/apps_v1_deployment_notification-controller.yaml
  services/kommander-flux/0.29.4/templates/apps_v1_deployment_source-controller.yaml
  services/kommander-flux/0.29.4/templates/kustomization.yaml
  services/kommander-flux/0.29.4/templates/networking.k8s.io_v1_networkpolicy_allow-egress.yaml
  services/kommander-flux/0.29.4/templates/networking.k8s.io_v1_networkpolicy_allow-scraping.yaml
  services/kommander-flux/0.29.4/templates/networking.k8s.io_v1_networkpolicy_allow-source.yaml
  services/kommander-flux/0.29.4/templates/networking.k8s.io_v1_networkpolicy_allow-webhooks.yaml
  services/kommander-flux/0.29.4/templates/rbac.authorization.k8s.io_v1_clusterrole_crd-controller-kommander-flux.yaml
  services/kommander-flux/0.29.4/templates/rbac.authorization.k8s.io_v1_clusterrolebinding_cluster-reconciler-kommander-flux.yaml
  services/kommander-flux/0.29.4/templates/rbac.authorization.k8s.io_v1_clusterrolebinding_crd-controller-kommander-flux.yaml
  services/kommander-flux/0.29.4/templates/v1_namespace_kommander-flux.yaml
  services/kommander-flux/0.29.4/templates/v1_service_notification-controller.yaml
  services/kommander-flux/0.29.4/templates/v1_service_source-controller.yaml
  services/kommander-flux/0.29.4/templates/v1_service_webhook-receiver.yaml
  services/kommander-flux/0.29.4/templates/v1_serviceaccount_helm-controller.yaml
  services/kommander-flux/0.29.4/templates/v1_serviceaccount_kustomize-controller.yaml
  services/kommander-flux/0.29.4/templates/v1_serviceaccount_notification-controller.yaml
  services/kommander-flux/0.29.4/templates/v1_serviceaccount_source-controller.yaml
  services/kommander/0.3.0/defaults/cm.yaml
Labels: ready-for-review, ok-to-test, slack-notify

#368 fix: Set user creds on minio tenant
  services/grafana-loki/0.48.3/minio.yaml
  services/project-grafana-loki/0.48.3/minio.yaml
Labels: ready-for-review, ok-to-test

#371 feat: bump kubetunnel to 0.0.13
  services/kubetunnel/0.0.13/defaults/cm.yaml
  services/kubetunnel/0.0.13/defaults/kustomization.yaml
  services/kubetunnel/0.0.13/kubetunnel.yaml
  services/kubetunnel/0.0.13/kustomization.yaml
Labels: ready-for-review, ok-to-test

#370 chore: skip notification if it is dev release
  make/release.mk
Labels: ready-for-review, ok-to-test

#374 feat: Bump grafana logging apps to 6.28.0
  services/grafana-logging/6.28.0/defaults/cm.yaml
  services/grafana-logging/6.28.0/defaults/kustomization.yaml
  services/grafana-logging/6.28.0/grafana-dashboards/audit.json
  services/grafana-logging/6.28.0/grafana-dashboards/kustomization.yaml
  services/grafana-logging/6.28.0/grafana.yaml
  services/grafana-logging/6.28.0/kustomization.yaml
  services/project-grafana-logging/6.28.0/defaults/cm.yaml
  services/project-grafana-logging/6.28.0/defaults/kustomization.yaml
  services/project-grafana-logging/6.28.0/kustomization.yaml
  services/project-grafana-logging/6.28.0/project-grafana.yaml
Labels: ready-for-review, ok-to-test, let-me-merge-it
