Repository mesosphere/kommander-applications, pull requests merged in 2022-03, with the labels that each got.

#222 feat: Upgrade flux to 0.27.3
  .tool-versions
  services/kommander-flux/0.27.3/defaults/cm.yaml
  services/kommander-flux/0.27.3/defaults/kustomization.yaml
  services/kommander-flux/0.27.3/kustomization.yaml
  services/kommander-flux/0.27.3/patch-proxy-env-vars.yaml
  services/kommander-flux/0.27.3/patch-source-ctrl-network-policy.yaml
  services/kommander-flux/0.27.3/templates/apiextensions.k8s.io_v1_customresourcedefinition_alerts.notification.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.27.3/templates/apiextensions.k8s.io_v1_customresourcedefinition_buckets.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.27.3/templates/apiextensions.k8s.io_v1_customresourcedefinition_gitrepositories.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.27.3/templates/apiextensions.k8s.io_v1_customresourcedefinition_helmcharts.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.27.3/templates/apiextensions.k8s.io_v1_customresourcedefinition_helmreleases.helm.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.27.3/templates/apiextensions.k8s.io_v1_customresourcedefinition_helmrepositories.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.27.3/templates/apiextensions.k8s.io_v1_customresourcedefinition_kustomizations.kustomize.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.27.3/templates/apiextensions.k8s.io_v1_customresourcedefinition_providers.notification.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.27.3/templates/apiextensions.k8s.io_v1_customresourcedefinition_receivers.notification.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.27.3/templates/apps_v1_deployment_helm-controller.yaml
  services/kommander-flux/0.27.3/templates/apps_v1_deployment_kustomize-controller.yaml
  services/kommander-flux/0.27.3/templates/apps_v1_deployment_notification-controller.yaml
  services/kommander-flux/0.27.3/templates/apps_v1_deployment_source-controller.yaml
  services/kommander-flux/0.27.3/templates/kustomization.yaml
  services/kommander-flux/0.27.3/templates/networking.k8s.io_v1_networkpolicy_allow-egress.yaml
  services/kommander-flux/0.27.3/templates/networking.k8s.io_v1_networkpolicy_allow-scraping.yaml
  services/kommander-flux/0.27.3/templates/networking.k8s.io_v1_networkpolicy_allow-source.yaml
  services/kommander-flux/0.27.3/templates/networking.k8s.io_v1_networkpolicy_allow-webhooks.yaml
  services/kommander-flux/0.27.3/templates/rbac.authorization.k8s.io_v1_clusterrole_crd-controller-kommander-flux.yaml
  services/kommander-flux/0.27.3/templates/rbac.authorization.k8s.io_v1_clusterrolebinding_cluster-reconciler-kommander-flux.yaml
  services/kommander-flux/0.27.3/templates/rbac.authorization.k8s.io_v1_clusterrolebinding_crd-controller-kommander-flux.yaml
  services/kommander-flux/0.27.3/templates/v1_namespace_kommander-flux.yaml
  services/kommander-flux/0.27.3/templates/v1_service_notification-controller.yaml
  services/kommander-flux/0.27.3/templates/v1_service_source-controller.yaml
  services/kommander-flux/0.27.3/templates/v1_service_webhook-receiver.yaml
  services/kommander-flux/0.27.3/templates/v1_serviceaccount_helm-controller.yaml
  services/kommander-flux/0.27.3/templates/v1_serviceaccount_kustomize-controller.yaml
  services/kommander-flux/0.27.3/templates/v1_serviceaccount_notification-controller.yaml
  services/kommander-flux/0.27.3/templates/v1_serviceaccount_source-controller.yaml
Labels: ready-for-review, ok-to-test

#218 feat: Bump grafana and kps to latest
  services/centralized-grafana/33.0.1/centralized-grafana.yaml
  services/centralized-grafana/33.0.1/defaults/cm.yaml
  services/centralized-grafana/33.0.1/defaults/kustomization.yaml
  services/centralized-grafana/33.0.1/grafana-dashboards/global-overview.json
  services/centralized-grafana/33.0.1/grafana-dashboards/kustomization.yaml
  services/centralized-grafana/33.0.1/kustomization.yaml
  services/grafana-logging/6.22.0/defaults/cm.yaml
  services/grafana-logging/6.22.0/defaults/kustomization.yaml
  services/grafana-logging/6.22.0/grafana-dashboards/audit.json
  services/grafana-logging/6.22.0/grafana-dashboards/kustomization.yaml
  services/grafana-logging/6.22.0/grafana.yaml
  services/grafana-logging/6.22.0/kustomization.yaml
  services/kommander/0.2.0/defaults/cm.yaml
  services/kube-prometheus-stack/33.0.1/defaults/cm.yaml
  services/kube-prometheus-stack/33.0.1/defaults/kustomization.yaml
  services/kube-prometheus-stack/33.0.1/grafana-dashboards/calico.json
  services/kube-prometheus-stack/33.0.1/grafana-dashboards/flux-cluster-stats.json
  services/kube-prometheus-stack/33.0.1/grafana-dashboards/flux-control-plane.json
  services/kube-prometheus-stack/33.0.1/grafana-dashboards/grafana.json
  services/kube-prometheus-stack/33.0.1/grafana-dashboards/kustomization.yaml
  services/kube-prometheus-stack/33.0.1/kube-prometheus-stack.yaml
  services/kube-prometheus-stack/33.0.1/kustomization.yaml
  services/project-grafana-logging/6.20.6/defaults/cm.yaml
  services/project-grafana-logging/6.20.6/project-grafana.yaml
  services/traefik/10.9.1/grafana-dashboards/kustomization.yaml
  services/velero/3.1.5/grafana-dashboards/kustomization.yaml
Labels: ready-for-review, ok-to-test

#223 chore: adds spec.wait to Kustomizations
  services/centralized-kubecost/0.22.1/post-install-jobs.yaml
  services/centralized-kubecost/0.22.1/release.yaml
  services/cert-manager/1.7.1/release.yaml
  services/cert-manager/1.7.1/root-ca.yaml
  services/gatekeeper/3.7.0/cleanup.yaml
  services/gatekeeper/3.7.0/constraints.yaml
  services/gatekeeper/3.7.0/constrainttemplates.yaml
  services/gatekeeper/3.7.0/release.yaml
  services/kubefed/0.9.1/federatedtypeconfigs.yaml
  services/kubefed/0.9.1/kube-federation-system-namespace.yaml
  services/kubefed/0.9.1/release.yaml
Labels: ready-for-review, ok-to-test

#219 feat: Bump jaeger and kiali
  services/jaeger/2.29.0/defaults/cm.yaml
  services/jaeger/2.29.0/defaults/kustomization.yaml
  services/jaeger/2.29.0/jaeger.yaml
  services/jaeger/2.29.0/kustomization.yaml
  services/kiali/1.47.0/defaults/cm.yaml
  services/kiali/1.47.0/defaults/kustomization.yaml
  services/kiali/1.47.0/kiali.yaml
  services/kiali/1.47.0/kustomization.yaml
Labels: ready-for-review, ok-to-test

#224 chore: adds slack notification label to flux update PRs
  hack/flux/update-flux.sh
Labels: enhancement, ready-for-review, ok-to-test

#227 feat: Add pre-upgrade strategy for jaeger
  services/istio/1.11.5/helmrelease.yaml
  services/istio/1.11.5/helmrelease/helmrelease.yaml
  services/istio/1.11.5/kustomization.yaml
  services/jaeger/2.29.0/helmrelease.yaml
  services/jaeger/2.29.0/helmrelease/release.yaml
  services/jaeger/2.29.0/kustomization.yaml
  services/jaeger/2.29.0/pre-upgrade.yaml
  services/jaeger/2.29.0/pre-upgrade/delete-jaeger-deployment.yaml
Labels: ready-for-review, ok-to-test

#229 feat: Bump kps, add upgrade strategy
  services/centralized-grafana/33.1.1/centralized-grafana.yaml
  services/centralized-grafana/33.1.1/defaults/cm.yaml
  services/centralized-grafana/33.1.1/defaults/kustomization.yaml
  services/centralized-grafana/33.1.1/grafana-dashboards/global-overview.json
  services/centralized-grafana/33.1.1/grafana-dashboards/kustomization.yaml
  services/centralized-grafana/33.1.1/kustomization.yaml
  services/kommander/0.2.0/defaults/cm.yaml
  services/kube-prometheus-stack/33.1.1/defaults/cm.yaml
  services/kube-prometheus-stack/33.1.1/defaults/kustomization.yaml
  services/kube-prometheus-stack/33.1.1/grafana-dashboards/calico.json
  services/kube-prometheus-stack/33.1.1/grafana-dashboards/flux-cluster-stats.json
  services/kube-prometheus-stack/33.1.1/grafana-dashboards/flux-control-plane.json
  services/kube-prometheus-stack/33.1.1/grafana-dashboards/grafana.json
  services/kube-prometheus-stack/33.1.1/grafana-dashboards/kustomization.yaml
  services/kube-prometheus-stack/33.1.1/kube-prometheus-stack.yaml
  services/kube-prometheus-stack/33.1.1/kustomization.yaml
  services/kube-prometheus-stack/metadata.yaml
Labels: ready-for-review, ok-to-test

#234 chore: Remove old versions of kommander apps
  services/kommander-appmanagement/0.1.0/defaults/cm.yaml
  services/kommander-appmanagement/0.1.0/defaults/kustomization.yaml
  services/kommander-appmanagement/0.1.0/kommander-appmanagement.yaml
  services/kommander-appmanagement/0.1.0/kustomization.yaml
  services/kommander/0.1.0/defaults/cm.yaml
  services/kommander/0.1.0/defaults/kustomization.yaml
  services/kommander/0.1.0/dynamic-helmreleases/README.txt
  services/kommander/0.1.0/dynamic-helmreleases/cluster-observer/cluster-observer.yaml
  services/kommander/0.1.0/dynamic-helmreleases/cluster-observer/kustomization.yaml
  services/kommander/0.1.0/dynamic-helmreleases/mtls-proxy/kustomization.yaml
  services/kommander/0.1.0/dynamic-helmreleases/mtls-proxy/mtls-proxy.yaml
  services/kommander/0.1.0/kommander.yaml
  services/kommander/0.1.0/kustomization.yaml
Labels: ready-for-review, ok-to-test

#236 build: Use asdf pre-commit and upgrade tool versions
  .tool-versions
  Dockerfile.ci
Labels: ready-for-review, ok-to-test

#233 chore: bump external dns
  common/helm-repositories/bitnami.yaml
  common/helm-repositories/kustomization.yaml
  services/external-dns/6.1.8/defaults/cm.yaml
  services/external-dns/6.1.8/defaults/kustomization.yaml
  services/external-dns/6.1.8/external-dns.yaml
  services/external-dns/6.1.8/kustomization.yaml
Labels: ready-for-review, ok-to-test

#232 fix: Bump loki app version
  services/grafana-loki/0.33.2/defaults/cm.yaml
  services/grafana-loki/0.33.2/defaults/kustomization.yaml
  services/grafana-loki/0.33.2/grafana-loki.yaml
  services/grafana-loki/0.33.2/kustomization.yaml
  services/grafana-loki/0.33.2/minio.yaml
  services/project-grafana-loki/0.33.2/defaults/cm.yaml
  services/project-grafana-loki/0.33.2/defaults/kustomization.yaml
  services/project-grafana-loki/0.33.2/kustomization.yaml
  services/project-grafana-loki/0.33.2/minio.yaml
  services/project-grafana-loki/0.33.2/project-grafana-loki.yaml
Labels: ready-for-review, ok-to-test

#231 fix: Use label selector for jaeger pre-upgrade
  services/jaeger/2.29.0/defaults/cm.yaml
  services/jaeger/2.29.0/helmrelease.yaml
  services/jaeger/2.29.0/pre-upgrade.yaml
  services/jaeger/2.29.0/pre-upgrade/delete-jaeger-deployment.yaml
Labels: ready-for-review, ok-to-test

#230 feat: Bump minio, add upgrade strategy
  services/grafana-loki/0.33.2/minio.yaml
  services/minio-operator/4.4.10/defaults/cm.yaml
  services/minio-operator/4.4.10/defaults/kustomization.yaml
  services/minio-operator/4.4.10/kustomization.yaml
  services/minio-operator/4.4.10/minio-operator-helmrelease.yaml
  services/minio-operator/4.4.10/minio-operator-helmrelease/release.yaml
  services/minio-operator/4.4.10/minio-operator-pre-upgrade.yaml
  services/minio-operator/4.4.10/minio-operator-pre-upgrade/delete-minio-operator-deployment.yaml
  services/minio-operator/4.4.10/minio-tenant-helmrelease.yaml
  services/minio-operator/4.4.10/minio-tenant-helmrelease/release.yaml
  services/minio-operator/4.4.3/kustomization.yaml
  services/project-grafana-loki/0.33.2/minio.yaml
Labels: ready-for-review, ok-to-test

#235 refactor: rename kommander version variables
  services/kommander-appmanagement/0.2.0/defaults/cm.yaml
  services/kommander/0.2.0/defaults/cm.yaml
Labels: ready-for-review, ok-to-test

#238 feat: Add kubecost as a default enterprise app
  services/kommander/0.2.0/defaults/cm.yaml
Labels: ready-for-review, ok-to-test

#243 build: Add repo dev tag target for nightly tagging
  .go-tools
  make/repo.mk
Labels: ready-for-review, ok-to-test

#237 fix: Restore grafana metrics
  services/kube-prometheus-stack/33.1.1/defaults/cm.yaml
Labels: ready-for-review, ok-to-test

#244 fix: make the select label a string
  services/kube-prometheus-stack/33.1.1/defaults/cm.yaml
Labels: ready-for-review, ok-to-test

#242 fix: Bump kubecost, fix ingresses
  services/centralized-kubecost/0.23.0/defaults/cm.yaml
  services/centralized-kubecost/0.23.0/defaults/kustomization.yaml
  services/centralized-kubecost/0.23.0/kustomization.yaml
  services/centralized-kubecost/0.23.0/post-install-jobs.yaml
  services/centralized-kubecost/0.23.0/post-install-jobs/post-install-jobs.yaml
  services/centralized-kubecost/0.23.0/release.yaml
  services/centralized-kubecost/0.23.0/release/release.yaml
  services/kommander/0.2.0/defaults/cm.yaml
  services/kubecost/0.23.0/defaults/cm.yaml
  services/kubecost/0.23.0/defaults/kustomization.yaml
  services/kubecost/0.23.0/kubecost.yaml
  services/kubecost/0.23.0/kustomization.yaml
Labels: ready-for-review, ok-to-test

#246 feat: Upgrade flux to 0.27.4
  .tool-versions
  services/kommander-flux/0.27.4/defaults/cm.yaml
  services/kommander-flux/0.27.4/defaults/kustomization.yaml
  services/kommander-flux/0.27.4/kustomization.yaml
  services/kommander-flux/0.27.4/patch-proxy-env-vars.yaml
  services/kommander-flux/0.27.4/patch-source-ctrl-network-policy.yaml
  services/kommander-flux/0.27.4/templates/apiextensions.k8s.io_v1_customresourcedefinition_alerts.notification.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.27.4/templates/apiextensions.k8s.io_v1_customresourcedefinition_buckets.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.27.4/templates/apiextensions.k8s.io_v1_customresourcedefinition_gitrepositories.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.27.4/templates/apiextensions.k8s.io_v1_customresourcedefinition_helmcharts.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.27.4/templates/apiextensions.k8s.io_v1_customresourcedefinition_helmreleases.helm.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.27.4/templates/apiextensions.k8s.io_v1_customresourcedefinition_helmrepositories.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.27.4/templates/apiextensions.k8s.io_v1_customresourcedefinition_kustomizations.kustomize.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.27.4/templates/apiextensions.k8s.io_v1_customresourcedefinition_providers.notification.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.27.4/templates/apiextensions.k8s.io_v1_customresourcedefinition_receivers.notification.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.27.4/templates/apps_v1_deployment_helm-controller.yaml
  services/kommander-flux/0.27.4/templates/apps_v1_deployment_kustomize-controller.yaml
  services/kommander-flux/0.27.4/templates/apps_v1_deployment_notification-controller.yaml
  services/kommander-flux/0.27.4/templates/apps_v1_deployment_source-controller.yaml
  services/kommander-flux/0.27.4/templates/kustomization.yaml
  services/kommander-flux/0.27.4/templates/networking.k8s.io_v1_networkpolicy_allow-egress.yaml
  services/kommander-flux/0.27.4/templates/networking.k8s.io_v1_networkpolicy_allow-scraping.yaml
  services/kommander-flux/0.27.4/templates/networking.k8s.io_v1_networkpolicy_allow-source.yaml
  services/kommander-flux/0.27.4/templates/networking.k8s.io_v1_networkpolicy_allow-webhooks.yaml
  services/kommander-flux/0.27.4/templates/rbac.authorization.k8s.io_v1_clusterrole_crd-controller-kommander-flux.yaml
  services/kommander-flux/0.27.4/templates/rbac.authorization.k8s.io_v1_clusterrolebinding_cluster-reconciler-kommander-flux.yaml
  services/kommander-flux/0.27.4/templates/rbac.authorization.k8s.io_v1_clusterrolebinding_crd-controller-kommander-flux.yaml
  services/kommander-flux/0.27.4/templates/v1_namespace_kommander-flux.yaml
  services/kommander-flux/0.27.4/templates/v1_service_notification-controller.yaml
  services/kommander-flux/0.27.4/templates/v1_service_source-controller.yaml
  services/kommander-flux/0.27.4/templates/v1_service_webhook-receiver.yaml
  services/kommander-flux/0.27.4/templates/v1_serviceaccount_helm-controller.yaml
  services/kommander-flux/0.27.4/templates/v1_serviceaccount_kustomize-controller.yaml
  services/kommander-flux/0.27.4/templates/v1_serviceaccount_notification-controller.yaml
  services/kommander-flux/0.27.4/templates/v1_serviceaccount_source-controller.yaml
Labels: ready-for-review, ok-to-test, slack-notify

#240 chore: remove unused directories
  common/defaults/project/catalog-repositories/kustomization.yaml
  common/defaults/project/kustomization.yaml
  common/defaults/workspace/catalog-repositories/kustomization.yaml
  common/defaults/workspace/kustomization.yaml
Labels: ready-for-review, do-not-merge, ok-to-test

#245 chore: inject airgappedEnabled to kommander-appmanagement
  services/kommander-appmanagement/0.2.0/defaults/cm.yaml
Labels: ready-for-review, ok-to-test

#248 fix: Label istio servicemonitor to match selector
  services/istio/1.11.6/defaults/cm.yaml
  services/istio/1.11.6/defaults/kustomization.yaml
  services/istio/1.11.6/helmrelease.yaml
  services/istio/1.11.6/helmrelease/helmrelease.yaml
  services/istio/1.11.6/kustomization.yaml
Labels: ready-for-review, ok-to-test

#239 fix: grafana dashboard view only
  services/centralized-grafana/33.1.4/centralized-grafana.yaml
  services/centralized-grafana/33.1.4/defaults/cm.yaml
  services/centralized-grafana/33.1.4/defaults/kustomization.yaml
  services/centralized-grafana/33.1.4/grafana-dashboards/global-overview.json
  services/centralized-grafana/33.1.4/grafana-dashboards/kustomization.yaml
  services/centralized-grafana/33.1.4/kustomization.yaml
  services/kommander/0.2.0/defaults/cm.yaml
  services/kube-prometheus-stack/33.1.4/defaults/cm.yaml
  services/kube-prometheus-stack/33.1.4/defaults/kustomization.yaml
  services/kube-prometheus-stack/33.1.4/grafana-dashboards/calico.json
  services/kube-prometheus-stack/33.1.4/grafana-dashboards/flux-cluster-stats.json
  services/kube-prometheus-stack/33.1.4/grafana-dashboards/flux-control-plane.json
  services/kube-prometheus-stack/33.1.4/grafana-dashboards/grafana.json
  services/kube-prometheus-stack/33.1.4/grafana-dashboards/kustomization.yaml
  services/kube-prometheus-stack/33.1.4/kube-prometheus-stack.yaml
  services/kube-prometheus-stack/33.1.4/kustomization.yaml
Labels: ready-for-review, ok-to-test

#250 feat: Bump kubecost to 0.23.1
  services/centralized-kubecost/0.23.1/defaults/cm.yaml
  services/centralized-kubecost/0.23.1/defaults/kustomization.yaml
  services/centralized-kubecost/0.23.1/kustomization.yaml
  services/centralized-kubecost/0.23.1/post-install-jobs.yaml
  services/centralized-kubecost/0.23.1/post-install-jobs/post-install-jobs.yaml
  services/centralized-kubecost/0.23.1/release.yaml
  services/centralized-kubecost/0.23.1/release/release.yaml
  services/kommander/0.2.0/defaults/cm.yaml
  services/kubecost/0.23.1/defaults/cm.yaml
  services/kubecost/0.23.1/defaults/kustomization.yaml
  services/kubecost/0.23.1/kubecost.yaml
  services/kubecost/0.23.1/kustomization.yaml
Labels: ready-for-review, ok-to-test

#251 fix: Define servicemonitor labels at the top level
  services/kube-prometheus-stack/33.1.4/defaults/cm.yaml
Labels: ready-for-review, ok-to-test

#252 feat: enable startupProbe for gitea pod
  services/gitea/4.1.1/defaults/cm.yaml
Labels: ready-for-review, ok-to-test

#253 feat: bump chartmuseum to 3.6.2
  services/chartmuseum/3.4.0/README.md
  services/chartmuseum/3.4.0/chartmuseum-3.4.0.tgz
  services/chartmuseum/3.6.2/README.md
  services/chartmuseum/3.6.2/chartmuseum-3.6.2.tgz
  services/chartmuseum/3.6.2/chartmuseum.yaml
  services/chartmuseum/3.6.2/defaults/cm.yaml
  services/chartmuseum/3.6.2/defaults/kustomization.yaml
  services/chartmuseum/3.6.2/kustomization.yaml
Labels: ready-for-review, ok-to-test

#256 fix: Increase kustomization interval to 6h
  services/centralized-kubecost/0.23.1/post-install-jobs.yaml
  services/centralized-kubecost/0.23.1/release.yaml
  services/cert-manager/1.7.1/release.yaml
  services/cert-manager/1.7.1/root-ca.yaml
  services/gatekeeper/3.7.0/cleanup.yaml
  services/gatekeeper/3.7.0/constraints.yaml
  services/gatekeeper/3.7.0/constrainttemplates.yaml
  services/gatekeeper/3.7.0/release.yaml
  services/istio/1.11.6/helmrelease.yaml
  services/jaeger/2.29.0/helmrelease.yaml
  services/jaeger/2.29.0/pre-upgrade.yaml
  services/kubefed/0.9.1/federatedtypeconfigs.yaml
  services/kubefed/0.9.1/kube-federation-system-namespace.yaml
  services/kubefed/0.9.1/release.yaml
  services/minio-operator/4.4.10/minio-operator-helmrelease.yaml
  services/minio-operator/4.4.10/minio-operator-pre-upgrade.yaml
  services/minio-operator/4.4.10/minio-tenant-helmrelease.yaml
Labels: ready-for-review, ok-to-test

#257 fix: update kubetunnel crds on upgrade
  services/kubetunnel/0.0.10/kubetunnel.yaml
Labels: ready-for-review, ok-to-test

#261 Revert "fix: Increase kustomization interval to 6h"
  services/centralized-kubecost/0.23.1/post-install-jobs.yaml
  services/centralized-kubecost/0.23.1/release.yaml
  services/cert-manager/1.7.1/release.yaml
  services/cert-manager/1.7.1/root-ca.yaml
  services/gatekeeper/3.7.0/cleanup.yaml
  services/gatekeeper/3.7.0/constraints.yaml
  services/gatekeeper/3.7.0/constrainttemplates.yaml
  services/gatekeeper/3.7.0/release.yaml
  services/istio/1.11.6/helmrelease.yaml
  services/jaeger/2.29.0/helmrelease.yaml
  services/jaeger/2.29.0/pre-upgrade.yaml
  services/kubefed/0.9.1/federatedtypeconfigs.yaml
  services/kubefed/0.9.1/kube-federation-system-namespace.yaml
  services/kubefed/0.9.1/release.yaml
  services/minio-operator/4.4.10/minio-operator-helmrelease.yaml
  services/minio-operator/4.4.10/minio-operator-pre-upgrade.yaml
  services/minio-operator/4.4.10/minio-tenant-helmrelease.yaml
Labels: ready-for-review, ok-to-test

#260 fix: Add retryInterval to all kustomizations
  services/centralized-kubecost/0.23.1/post-install-jobs.yaml
  services/centralized-kubecost/0.23.1/release.yaml
  services/cert-manager/1.7.1/release.yaml
  services/cert-manager/1.7.1/root-ca.yaml
  services/gatekeeper/3.7.0/cleanup.yaml
  services/gatekeeper/3.7.0/constraints.yaml
  services/gatekeeper/3.7.0/constrainttemplates.yaml
  services/gatekeeper/3.7.0/release.yaml
  services/istio/1.11.6/helmrelease.yaml
  services/jaeger/2.29.0/helmrelease.yaml
  services/jaeger/2.29.0/pre-upgrade.yaml
  services/kubefed/0.9.1/federatedtypeconfigs.yaml
  services/kubefed/0.9.1/kube-federation-system-namespace.yaml
  services/kubefed/0.9.1/release.yaml
  services/minio-operator/4.4.10/minio-operator-helmrelease.yaml
  services/minio-operator/4.4.10/minio-operator-pre-upgrade.yaml
  services/minio-operator/4.4.10/minio-tenant-helmrelease.yaml
Labels: ready-for-review, ok-to-test

#265 jimmi/fix release tarball
  make/release.mk
Labels: ready-for-review, ok-to-test

#263 feat: Add dkp-insights-management v0.1.2
  common/helm-repositories/mesosphere-repos.yaml
  services/dkp-insights-management/0.1.2/defaults/cm.yaml
  services/dkp-insights-management/0.1.2/defaults/kustomization.yaml
  services/dkp-insights-management/0.1.2/helmrelease.yaml
  services/dkp-insights-management/0.1.2/helmrelease/helmrelease.yaml
  services/dkp-insights-management/0.1.2/kustomization.yaml
  services/dkp-insights-management/metadata.yaml
Labels: ready-for-review, do-not-merge, ok-to-test

#267 feat: bump kubecost to 0.23.2
  services/centralized-kubecost/0.23.2/defaults/cm.yaml
  services/centralized-kubecost/0.23.2/defaults/kustomization.yaml
  services/centralized-kubecost/0.23.2/kustomization.yaml
  services/centralized-kubecost/0.23.2/post-install-jobs.yaml
  services/centralized-kubecost/0.23.2/post-install-jobs/post-install-jobs.yaml
  services/centralized-kubecost/0.23.2/release.yaml
  services/centralized-kubecost/0.23.2/release/release.yaml
  services/kommander/0.2.0/defaults/cm.yaml
  services/kubecost/0.23.2/defaults/cm.yaml
  services/kubecost/0.23.2/defaults/kustomization.yaml
  services/kubecost/0.23.2/kubecost.yaml
  services/kubecost/0.23.2/kustomization.yaml
Labels: ready-for-review, ok-to-test

#269 chore(logging-operator): bump configmap-reload image to v0.7.1
  services/logging-operator/3.17.0/defaults/cm.yaml
Labels: ready-for-review, ok-to-test

#272 build: Use /dkp/<version> as s3 path for release
  make/release.mk
Labels: ready-for-review, ok-to-test

#270 feat: bump kubecost to 0.23.3
  services/centralized-kubecost/0.23.3/defaults/cm.yaml
  services/centralized-kubecost/0.23.3/defaults/kustomization.yaml
  services/centralized-kubecost/0.23.3/kustomization.yaml
  services/centralized-kubecost/0.23.3/post-install-jobs.yaml
  services/centralized-kubecost/0.23.3/post-install-jobs/post-install-jobs.yaml
  services/centralized-kubecost/0.23.3/release.yaml
  services/centralized-kubecost/0.23.3/release/release.yaml
  services/kommander/0.2.0/defaults/cm.yaml
  services/kubecost/0.23.3/defaults/cm.yaml
  services/kubecost/0.23.3/defaults/kustomization.yaml
  services/kubecost/0.23.3/kubecost.yaml
  services/kubecost/0.23.3/kustomization.yaml
Labels: ready-for-review, ok-to-test

#277 feat: bump logging-operator to 3.17.2
  services/logging-operator/3.17.2/defaults/cm.yaml
  services/logging-operator/3.17.2/defaults/kustomization.yaml
  services/logging-operator/3.17.2/kustomization.yaml
  services/logging-operator/3.17.2/logging-operator-logging.yaml
  services/logging-operator/3.17.2/logging-operator.yaml
Labels: ready-for-review, ok-to-test

#278 chore(loki): Bump gateway nginx image tag
  services/grafana-loki/0.33.2/defaults/cm.yaml
Labels: ready-for-review, ok-to-test

#280 feat: bump dex chart to 2.9.14
  services/dex/2.9.14/defaults/cm.yaml
  services/dex/2.9.14/defaults/kustomization.yaml
  services/dex/2.9.14/dex.yaml
  services/dex/2.9.14/kustomization.yaml
Labels: ok-to-test

#281 fix: Add metadata name to mtls-proxy
  services/kommander/0.2.0/dynamic-helmreleases/mtls-proxy/mtls-proxy.yaml
Labels: ready-for-review, ok-to-test

#282 feat: bump KPS to 33.1.5
  services/centralized-grafana/33.1.5/centralized-grafana.yaml
  services/centralized-grafana/33.1.5/defaults/cm.yaml
  services/centralized-grafana/33.1.5/defaults/kustomization.yaml
  services/centralized-grafana/33.1.5/grafana-dashboards/global-overview.json
  services/centralized-grafana/33.1.5/grafana-dashboards/kustomization.yaml
  services/centralized-grafana/33.1.5/kustomization.yaml
  services/kommander/0.2.0/defaults/cm.yaml
  services/kube-prometheus-stack/33.1.5/defaults/cm.yaml
  services/kube-prometheus-stack/33.1.5/defaults/kustomization.yaml
  services/kube-prometheus-stack/33.1.5/grafana-dashboards/calico.json
  services/kube-prometheus-stack/33.1.5/grafana-dashboards/flux-cluster-stats.json
  services/kube-prometheus-stack/33.1.5/grafana-dashboards/flux-control-plane.json
  services/kube-prometheus-stack/33.1.5/grafana-dashboards/grafana.json
  services/kube-prometheus-stack/33.1.5/grafana-dashboards/kustomization.yaml
  services/kube-prometheus-stack/33.1.5/kube-prometheus-stack.yaml
  services/kube-prometheus-stack/33.1.5/kustomization.yaml
Labels: ready-for-review, ok-to-test

#283 [release-2.2] bump to rc.3
  services/centralized-grafana/33.1.5/centralized-grafana.yaml
  services/centralized-grafana/33.1.5/defaults/cm.yaml
  services/centralized-grafana/33.1.5/defaults/kustomization.yaml
  services/centralized-grafana/33.1.5/grafana-dashboards/global-overview.json
  services/centralized-grafana/33.1.5/grafana-dashboards/kustomization.yaml
  services/centralized-grafana/33.1.5/kustomization.yaml
  services/dex/2.9.14/defaults/cm.yaml
  services/dex/2.9.14/defaults/kustomization.yaml
  services/dex/2.9.14/dex.yaml
  services/dex/2.9.14/kustomization.yaml
  services/gitea/5.0.4/defaults/cm.yaml
  services/gitea/5.0.4/defaults/kustomization.yaml
  services/gitea/5.0.4/gitea.yaml
  services/gitea/5.0.4/kustomization.yaml
  services/grafana-loki/0.33.2/defaults/cm.yaml
  services/kommander-appmanagement/0.2.0/kommander-appmanagement.yaml
  services/kommander/0.2.0/defaults/cm.yaml
  services/kommander/0.2.0/dynamic-helmreleases/mtls-proxy/mtls-proxy.yaml
  services/kommander/0.2.0/kommander.yaml
  services/kube-prometheus-stack/33.1.5/defaults/cm.yaml
  services/kube-prometheus-stack/33.1.5/defaults/kustomization.yaml
  services/kube-prometheus-stack/33.1.5/grafana-dashboards/calico.json
  services/kube-prometheus-stack/33.1.5/grafana-dashboards/flux-cluster-stats.json
  services/kube-prometheus-stack/33.1.5/grafana-dashboards/flux-control-plane.json
  services/kube-prometheus-stack/33.1.5/grafana-dashboards/grafana.json
  services/kube-prometheus-stack/33.1.5/grafana-dashboards/kustomization.yaml
  services/kube-prometheus-stack/33.1.5/kube-prometheus-stack.yaml
  services/kube-prometheus-stack/33.1.5/kustomization.yaml
  services/logging-operator/3.17.2/defaults/cm.yaml
  services/logging-operator/3.17.2/defaults/kustomization.yaml
  services/logging-operator/3.17.2/kustomization.yaml
  services/logging-operator/3.17.2/logging-operator-logging.yaml
  services/logging-operator/3.17.2/logging-operator.yaml
Labels: ready-for-review, ok-to-test

#286 fix: Use - instead of _ in arch name
  make/release.mk
Labels: ready-for-review, ok-to-test

#271 feat: add flux to default apps
  services/kommander/0.2.0/defaults/cm.yaml
Labels: ready-for-review, ok-to-test
