Repository mesosphere/kommander-applications, pull requests merged in 2022-01, with the labels that each got.

#125 fix: Add chartmuseum metadata
  services/chartmuseum/metadata.yaml
Labels: ready-for-review

#124 feat: Update to kubetunnel 0.0.10 (compatible with kubernetes 1.22)
  services/kubetunnel/0.0.10/defaults/cm.yaml
  services/kubetunnel/0.0.10/defaults/kustomization.yaml
  services/kubetunnel/0.0.10/kubetunnel.yaml
  services/kubetunnel/0.0.10/kustomization.yaml
Labels: ready-for-review, ok-to-test

#123 feat: disable user registration in Gitea
  services/gitea/4.1.1/defaults/cm.yaml
Labels: ready-for-review, ok-to-test

#127 feat: add pre-commit and mergebot configuration
  .gitlint
  .pre-commit-config.yaml
  Dockerfile.ci
  README.md
  hack/validate-service-metadata.sh
  make/all.mk
  make/pre-commit.mk
  mergebot-config.json
Labels: ready-for-review, ok-to-test

#126 feat: add dummy helm releases
  services/kommander/0.1.0/dynamic-helmreleases/README.txt
  services/kommander/0.1.0/dynamic-helmreleases/cluster-observer/cluster-observer.yaml
  services/kommander/0.1.0/dynamic-helmreleases/cluster-observer/kustomization.yaml
  services/kommander/0.1.0/dynamic-helmreleases/mtls-proxy/kustomization.yaml
  services/kommander/0.1.0/dynamic-helmreleases/mtls-proxy/mtls-proxy.yaml
Labels: ready-for-review, ok-to-test

#122 feat: Upgrade logging-operator and fluent-bit
  services/fluent-bit/0.19.5/defaults/cm.yaml
  services/fluent-bit/0.19.5/defaults/kustomization.yaml
  services/fluent-bit/0.19.5/fluent-bit.yaml
  services/fluent-bit/0.19.5/kustomization.yaml
  services/logging-operator/3.16.0/defaults/cm.yaml
  services/logging-operator/3.16.0/defaults/kustomization.yaml
  services/logging-operator/3.16.0/kustomization.yaml
  services/logging-operator/3.16.0/logging-operator-logging.yaml
  services/logging-operator/3.16.0/logging-operator.yaml
Labels: ready-for-review, ok-to-test

#134 fix: Bump velero to 3.1.5 (CVE)
  services/velero/3.1.5/defaults/cm.yaml
  services/velero/3.1.5/defaults/kustomization.yaml
  services/velero/3.1.5/kustomization.yaml
  services/velero/3.1.5/velero.yaml
Labels: ready-for-review, ok-to-test, needs-backport

#132 chore: bump kommander and kommander-application to 0.2.0
  services/kommander-appmanagement/0.2.0/defaults/cm.yaml
  services/kommander-appmanagement/0.2.0/defaults/kustomization.yaml
  services/kommander-appmanagement/0.2.0/kommander-appmanagement.yaml
  services/kommander-appmanagement/0.2.0/kustomization.yaml
  services/kommander/0.2.0/defaults/cm.yaml
  services/kommander/0.2.0/defaults/kustomization.yaml
  services/kommander/0.2.0/dynamic-helmreleases/README.txt
  services/kommander/0.2.0/dynamic-helmreleases/cluster-observer/cluster-observer.yaml
  services/kommander/0.2.0/dynamic-helmreleases/cluster-observer/kustomization.yaml
  services/kommander/0.2.0/dynamic-helmreleases/mtls-proxy/kustomization.yaml
  services/kommander/0.2.0/dynamic-helmreleases/mtls-proxy/mtls-proxy.yaml
  services/kommander/0.2.0/kommander.yaml
  services/kommander/0.2.0/kustomization.yaml
Labels: ready-for-review, ok-to-test

#130 fix: Remove older version dirs
  services/centralized-kubecost/0.20.0/defaults/cm.yaml
  services/centralized-kubecost/0.20.0/defaults/kustomization.yaml
  services/centralized-kubecost/0.20.0/kustomization.yaml
  services/centralized-kubecost/0.20.0/post-install-jobs.yaml
  services/centralized-kubecost/0.20.0/post-install-jobs/post-install-jobs.yaml
  services/centralized-kubecost/0.20.0/release.yaml
  services/centralized-kubecost/0.20.0/release/release.yaml
  services/kubecost/0.20.0/defaults/cm.yaml
  services/kubecost/0.20.0/defaults/kustomization.yaml
  services/kubecost/0.20.0/kubecost.yaml
  services/kubecost/0.20.0/kustomization.yaml
Labels: ready-for-review, ok-to-test

#129 chore: Remove old kubetunnel
  services/kubetunnel/0.0.8/defaults/cm.yaml
  services/kubetunnel/0.0.8/defaults/kustomization.yaml
  services/kubetunnel/0.0.8/kubetunnel.yaml
  services/kubetunnel/0.0.8/kustomization.yaml
Labels: ready-for-review, ok-to-test

#138 [release-2.1] build: Bump mergebot fixversion map
  mergebot-config.json
Labels: ready-for-review, ok-to-test

#139 refactor: Move grafana dashboards into services dir
  grafana-dashboards/kube-prometheus-stack/kustomization.yaml
  services/centralized-grafana/18.1.1/grafana-dashboards/global-overview.json
  services/centralized-grafana/18.1.1/grafana-dashboards/kustomization.yaml
  services/centralized-grafana/18.1.1/kustomization.yaml
  services/grafana-logging/6.16.14/grafana-dashboards/audit.json
  services/grafana-logging/6.16.14/grafana-dashboards/kustomization.yaml
  services/grafana-logging/6.16.14/kustomization.yaml
  services/kube-prometheus-stack/18.1.1/grafana-dashboards/calico.json
  services/kube-prometheus-stack/18.1.1/grafana-dashboards/flux-cluster-stats.json
  services/kube-prometheus-stack/18.1.1/grafana-dashboards/flux-control-plane.json
  services/kube-prometheus-stack/18.1.1/grafana-dashboards/grafana.json
  services/kube-prometheus-stack/18.1.1/grafana-dashboards/kustomization.yaml
  services/kube-prometheus-stack/18.1.1/kustomization.yaml
  services/traefik/10.3.0/grafana-dashboards/kustomization.yaml
  services/traefik/10.3.0/grafana-dashboards/traefik.json
  services/traefik/10.3.0/kustomization.yaml
  services/velero/3.1.5/grafana-dashboards/kustomization.yaml
  services/velero/3.1.5/grafana-dashboards/velero.json
  services/velero/3.1.5/kustomization.yaml
Labels: ready-for-review, ok-to-test

#133 chore: Bump kubecost
  services/centralized-kubecost/0.21.0/defaults/cm.yaml
  services/centralized-kubecost/0.21.0/defaults/kustomization.yaml
  services/centralized-kubecost/0.21.0/kustomization.yaml
  services/centralized-kubecost/0.21.0/post-install-jobs.yaml
  services/centralized-kubecost/0.21.0/post-install-jobs/post-install-jobs.yaml
  services/centralized-kubecost/0.21.0/release.yaml
  services/centralized-kubecost/0.21.0/release/release.yaml
  services/kubecost/0.21.0/defaults/cm.yaml
  services/kubecost/0.21.0/defaults/kustomization.yaml
  services/kubecost/0.21.0/kubecost.yaml
  services/kubecost/0.21.0/kustomization.yaml
Labels: ready-for-review, ok-to-test

#136 chore: bump kube-prometheus-stack chart to 18.1.2
  services/centralized-grafana/18.1.2/centralized-grafana.yaml
  services/centralized-grafana/18.1.2/defaults/cm.yaml
  services/centralized-grafana/18.1.2/defaults/kustomization.yaml
  services/centralized-grafana/18.1.2/grafana-dashboards/global-overview.json
  services/centralized-grafana/18.1.2/grafana-dashboards/kustomization.yaml
  services/centralized-grafana/18.1.2/kustomization.yaml
  services/kube-prometheus-stack/18.1.2/defaults/cm.yaml
  services/kube-prometheus-stack/18.1.2/defaults/kustomization.yaml
  services/kube-prometheus-stack/18.1.2/grafana-dashboards/calico.json
  services/kube-prometheus-stack/18.1.2/grafana-dashboards/flux-cluster-stats.json
  services/kube-prometheus-stack/18.1.2/grafana-dashboards/flux-control-plane.json
  services/kube-prometheus-stack/18.1.2/grafana-dashboards/grafana.json
  services/kube-prometheus-stack/18.1.2/grafana-dashboards/kustomization.yaml
  services/kube-prometheus-stack/18.1.2/kube-prometheus-stack.yaml
  services/kube-prometheus-stack/18.1.2/kustomization.yaml
Labels: ready-for-review, ok-to-test, needs-backport

#140 fix: Bump gatekeeper to 0.6.9, configure sideEffects
  services/gatekeeper/0.6.9/constraints.yaml
  services/gatekeeper/0.6.9/constraints/enforce-helmrelease-sa.yaml
  services/gatekeeper/0.6.9/constraints/enforce-kustomization-sa.yaml
  services/gatekeeper/0.6.9/constrainttemplates.yaml
  services/gatekeeper/0.6.9/constrainttemplates/enforce-sa-constrainttemplate.yaml
  services/gatekeeper/0.6.9/defaults/cm.yaml
  services/gatekeeper/0.6.9/defaults/kustomization.yaml
  services/gatekeeper/0.6.9/kustomization.yaml
  services/gatekeeper/0.6.9/release.yaml
  services/gatekeeper/0.6.9/release/kustomization.yaml
  services/gatekeeper/0.6.9/release/release.yaml
  services/gatekeeper/bootstrap/kustomization.yaml
Labels: ready-for-review, ok-to-test, needs-backport

#142 feat: Upgrade flux to 0.25.2
  .tool-versions
  services/kommander-flux/0.25.2/defaults/cm.yaml
  services/kommander-flux/0.25.2/defaults/kustomization.yaml
  services/kommander-flux/0.25.2/kustomization.yaml
  services/kommander-flux/0.25.2/patch-proxy-env-vars.yaml
  services/kommander-flux/0.25.2/patch-source-ctrl-network-policy.yaml
  services/kommander-flux/0.25.2/templates/apiextensions.k8s.io_v1_customresourcedefinition_alerts.notification.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.25.2/templates/apiextensions.k8s.io_v1_customresourcedefinition_buckets.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.25.2/templates/apiextensions.k8s.io_v1_customresourcedefinition_gitrepositories.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.25.2/templates/apiextensions.k8s.io_v1_customresourcedefinition_helmcharts.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.25.2/templates/apiextensions.k8s.io_v1_customresourcedefinition_helmreleases.helm.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.25.2/templates/apiextensions.k8s.io_v1_customresourcedefinition_helmrepositories.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.25.2/templates/apiextensions.k8s.io_v1_customresourcedefinition_kustomizations.kustomize.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.25.2/templates/apiextensions.k8s.io_v1_customresourcedefinition_providers.notification.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.25.2/templates/apiextensions.k8s.io_v1_customresourcedefinition_receivers.notification.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.25.2/templates/apps_v1_deployment_helm-controller.yaml
  services/kommander-flux/0.25.2/templates/apps_v1_deployment_kustomize-controller.yaml
  services/kommander-flux/0.25.2/templates/apps_v1_deployment_notification-controller.yaml
  services/kommander-flux/0.25.2/templates/apps_v1_deployment_source-controller.yaml
  services/kommander-flux/0.25.2/templates/kustomization.yaml
  services/kommander-flux/0.25.2/templates/networking.k8s.io_v1_networkpolicy_allow-egress.yaml
  services/kommander-flux/0.25.2/templates/networking.k8s.io_v1_networkpolicy_allow-scraping.yaml
  services/kommander-flux/0.25.2/templates/networking.k8s.io_v1_networkpolicy_allow-source.yaml
  services/kommander-flux/0.25.2/templates/networking.k8s.io_v1_networkpolicy_allow-webhooks.yaml
  services/kommander-flux/0.25.2/templates/rbac.authorization.k8s.io_v1_clusterrole_crd-controller-kommander-flux.yaml
  services/kommander-flux/0.25.2/templates/rbac.authorization.k8s.io_v1_clusterrolebinding_cluster-reconciler-kommander-flux.yaml
  services/kommander-flux/0.25.2/templates/rbac.authorization.k8s.io_v1_clusterrolebinding_crd-controller-kommander-flux.yaml
  services/kommander-flux/0.25.2/templates/v1_namespace_kommander-flux.yaml
  services/kommander-flux/0.25.2/templates/v1_service_notification-controller.yaml
  services/kommander-flux/0.25.2/templates/v1_service_source-controller.yaml
  services/kommander-flux/0.25.2/templates/v1_service_webhook-receiver.yaml
  services/kommander-flux/0.25.2/templates/v1_serviceaccount_helm-controller.yaml
  services/kommander-flux/0.25.2/templates/v1_serviceaccount_kustomize-controller.yaml
  services/kommander-flux/0.25.2/templates/v1_serviceaccount_notification-controller.yaml
  services/kommander-flux/0.25.2/templates/v1_serviceaccount_source-controller.yaml
Labels: ready-for-review, ok-to-test

#73 feat: Bump thanos to 0.4.6
  services/thanos/0.4.6/defaults/cm.yaml
  services/thanos/0.4.6/defaults/kustomization.yaml
  services/thanos/0.4.6/kustomization.yaml
  services/thanos/0.4.6/thanos.yaml
Labels: ready-for-review, ok-to-test

#146 Revert "feat: Upgrade flux to 0.25.2"
  .tool-versions
  services/kommander-flux/0.24.1/defaults/cm.yaml
  services/kommander-flux/0.24.1/defaults/kustomization.yaml
  services/kommander-flux/0.24.1/kustomization.yaml
  services/kommander-flux/0.24.1/patch-proxy-env-vars.yaml
  services/kommander-flux/0.24.1/patch-source-ctrl-network-policy.yaml
  services/kommander-flux/0.24.1/templates/apiextensions.k8s.io_v1_customresourcedefinition_alerts.notification.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.24.1/templates/apiextensions.k8s.io_v1_customresourcedefinition_buckets.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.24.1/templates/apiextensions.k8s.io_v1_customresourcedefinition_gitrepositories.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.24.1/templates/apiextensions.k8s.io_v1_customresourcedefinition_helmcharts.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.24.1/templates/apiextensions.k8s.io_v1_customresourcedefinition_helmreleases.helm.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.24.1/templates/apiextensions.k8s.io_v1_customresourcedefinition_helmrepositories.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.24.1/templates/apiextensions.k8s.io_v1_customresourcedefinition_kustomizations.kustomize.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.24.1/templates/apiextensions.k8s.io_v1_customresourcedefinition_providers.notification.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.24.1/templates/apiextensions.k8s.io_v1_customresourcedefinition_receivers.notification.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.24.1/templates/apps_v1_deployment_helm-controller.yaml
  services/kommander-flux/0.24.1/templates/apps_v1_deployment_kustomize-controller.yaml
  services/kommander-flux/0.24.1/templates/apps_v1_deployment_notification-controller.yaml
  services/kommander-flux/0.24.1/templates/apps_v1_deployment_source-controller.yaml
  services/kommander-flux/0.24.1/templates/kustomization.yaml
  services/kommander-flux/0.24.1/templates/networking.k8s.io_v1_networkpolicy_allow-egress.yaml
  services/kommander-flux/0.24.1/templates/networking.k8s.io_v1_networkpolicy_allow-scraping.yaml
  services/kommander-flux/0.24.1/templates/networking.k8s.io_v1_networkpolicy_allow-source.yaml
  services/kommander-flux/0.24.1/templates/networking.k8s.io_v1_networkpolicy_allow-webhooks.yaml
  services/kommander-flux/0.24.1/templates/rbac.authorization.k8s.io_v1_clusterrole_crd-controller-kommander-flux.yaml
  services/kommander-flux/0.24.1/templates/rbac.authorization.k8s.io_v1_clusterrolebinding_cluster-reconciler-kommander-flux.yaml
  services/kommander-flux/0.24.1/templates/rbac.authorization.k8s.io_v1_clusterrolebinding_crd-controller-kommander-flux.yaml
  services/kommander-flux/0.24.1/templates/v1_namespace_kommander-flux.yaml
  services/kommander-flux/0.24.1/templates/v1_service_notification-controller.yaml
  services/kommander-flux/0.24.1/templates/v1_service_source-controller.yaml
  services/kommander-flux/0.24.1/templates/v1_service_webhook-receiver.yaml
  services/kommander-flux/0.24.1/templates/v1_serviceaccount_helm-controller.yaml
  services/kommander-flux/0.24.1/templates/v1_serviceaccount_kustomize-controller.yaml
  services/kommander-flux/0.24.1/templates/v1_serviceaccount_notification-controller.yaml
  services/kommander-flux/0.24.1/templates/v1_serviceaccount_source-controller.yaml
Labels: ok-to-test

#148 fix: synchronize kubetunmnel versioning scheme
  services/kubetunnel/0.0.10/kubetunnel.yaml
Labels: ready-for-review, ok-to-test

#149 feat: make helmrepositories use chartmuseum's CA certificate
  common/helm-repositories/banzaicloud.yaml
  common/helm-repositories/dashboard.yaml
  common/helm-repositories/fluent.yaml
  common/helm-repositories/gitea.yaml
  common/helm-repositories/grafana.yaml
  common/helm-repositories/jaegertracing.yaml
  common/helm-repositories/kaptain.yaml
  common/helm-repositories/kiali.yaml
  common/helm-repositories/kommander-ui.yaml
  common/helm-repositories/kommander.yaml
  common/helm-repositories/kubefed.yaml
  common/helm-repositories/kubetunnel.yaml
  common/helm-repositories/mesosphere-repos.yaml
  common/helm-repositories/minio.yaml
  common/helm-repositories/prometheus-community.yaml
  common/helm-repositories/reloader.yaml
  common/helm-repositories/traefik.yaml
Labels: ready-for-review, ok-to-test

#150 Revert "feat: make helmrepositories use chartmuseum's CA certificate"
  common/helm-repositories/banzaicloud.yaml
  common/helm-repositories/dashboard.yaml
  common/helm-repositories/fluent.yaml
  common/helm-repositories/gitea.yaml
  common/helm-repositories/grafana.yaml
  common/helm-repositories/jaegertracing.yaml
  common/helm-repositories/kaptain.yaml
  common/helm-repositories/kiali.yaml
  common/helm-repositories/kommander-ui.yaml
  common/helm-repositories/kommander.yaml
  common/helm-repositories/kubefed.yaml
  common/helm-repositories/kubetunnel.yaml
  common/helm-repositories/mesosphere-repos.yaml
  common/helm-repositories/minio.yaml
  common/helm-repositories/prometheus-community.yaml
  common/helm-repositories/reloader.yaml
  common/helm-repositories/traefik.yaml
Labels: ready-for-review, ok-to-test

#144 fix: Enable home dashboard in centralized grafana
  services/kube-prometheus-stack/18.1.2/defaults/cm.yaml
Labels: ready-for-review, ok-to-test, needs-backport

#156 chore: Bump reloader to 0.0.104
  services/reloader/0.0.104/defaults/cm.yaml
  services/reloader/0.0.104/defaults/kustomization.yaml
  services/reloader/0.0.104/kustomization.yaml
  services/reloader/0.0.104/reloader.yaml
Labels: ready-for-review, ok-to-test

#154 fix: Enable home dash on centralized-grafana not kps
  services/centralized-grafana/18.1.2/defaults/cm.yaml
  services/kube-prometheus-stack/18.1.2/defaults/cm.yaml
Labels: ready-for-review, ok-to-test, needs-backport

#157 chore: Bump kubernetes-dashboard to 5.1.1
  services/kubernetes-dashboard/5.1.1/defaults/cm.yaml
  services/kubernetes-dashboard/5.1.1/defaults/kustomization.yaml
  services/kubernetes-dashboard/5.1.1/kubernetes-dashboard.yaml
  services/kubernetes-dashboard/5.1.1/kustomization.yaml
Labels: ready-for-review, ok-to-test

#158 chore: Bump grafana versions
  services/grafana-logging/6.20.6/defaults/cm.yaml
  services/grafana-logging/6.20.6/defaults/kustomization.yaml
  services/grafana-logging/6.20.6/grafana-dashboards/audit.json
  services/grafana-logging/6.20.6/grafana-dashboards/kustomization.yaml
  services/grafana-logging/6.20.6/grafana.yaml
  services/grafana-logging/6.20.6/kustomization.yaml
  services/project-grafana-logging/6.20.6/defaults/cm.yaml
  services/project-grafana-logging/6.20.6/defaults/kustomization.yaml
  services/project-grafana-logging/6.20.6/kustomization.yaml
  services/project-grafana-logging/6.20.6/project-grafana.yaml
Labels: ready-for-review, ok-to-test

#164 feat: Kustomize dynamic helmreleases
  services/kommander/0.2.0/dynamic-helmreleases/cluster-observer/cluster-observer.yaml
  services/kommander/0.2.0/dynamic-helmreleases/mtls-proxy/mtls-proxy.yaml
Labels: ready-for-review, ok-to-test

#162 chore: bump prometheus adapter to 2.17.1
  services/prometheus-adapter/2.17.1/defaults/cm.yaml
  services/prometheus-adapter/2.17.1/defaults/kustomization.yaml
  services/prometheus-adapter/2.17.1/kustomization.yaml
  services/prometheus-adapter/2.17.1/prometheus-adapter.yaml
Labels: ready-for-review, ok-to-test

#160 feat: bump fluent-bit to 0.19.17
  services/fluent-bit/0.19.17/defaults/cm.yaml
  services/fluent-bit/0.19.17/defaults/kustomization.yaml
  services/fluent-bit/0.19.17/fluent-bit.yaml
  services/fluent-bit/0.19.17/kustomization.yaml
Labels: ready-for-review, ok-to-test

#167 fix: Release istio in the workspace namespace
  services/istio/1.9.2/defaults/cm.yaml
  services/istio/1.9.2/defaults/kustomization.yaml
  services/istio/1.9.2/helmrelease.yaml
  services/istio/1.9.2/helmrelease/helmrelease.yaml
  services/istio/1.9.2/istio-ca.yaml
  services/istio/1.9.2/istio-ca/istio-ca.yaml
  services/istio/1.9.2/istio-system-namespace.yaml
  services/istio/1.9.2/istio-system-namespace/istio-system.yaml
  services/istio/1.9.2/kustomization.yaml
Labels: ready-for-review, ok-to-test

#168 fix: Override values to fix centralized-grafana cronjob
  services/centralized-grafana/18.1.3/centralized-grafana.yaml
  services/centralized-grafana/18.1.3/defaults/cm.yaml
  services/centralized-grafana/18.1.3/defaults/kustomization.yaml
  services/centralized-grafana/18.1.3/grafana-dashboards/global-overview.json
  services/centralized-grafana/18.1.3/grafana-dashboards/kustomization.yaml
  services/centralized-grafana/18.1.3/kustomization.yaml
  services/kube-prometheus-stack/18.1.3/defaults/cm.yaml
  services/kube-prometheus-stack/18.1.3/defaults/kustomization.yaml
  services/kube-prometheus-stack/18.1.3/grafana-dashboards/calico.json
  services/kube-prometheus-stack/18.1.3/grafana-dashboards/flux-cluster-stats.json
  services/kube-prometheus-stack/18.1.3/grafana-dashboards/flux-control-plane.json
  services/kube-prometheus-stack/18.1.3/grafana-dashboards/grafana.json
  services/kube-prometheus-stack/18.1.3/grafana-dashboards/kustomization.yaml
  services/kube-prometheus-stack/18.1.3/kube-prometheus-stack.yaml
  services/kube-prometheus-stack/18.1.3/kustomization.yaml
Labels: ready-for-review, ok-to-test

#172 fix: Add required env var to config reloader container
  services/kube-prometheus-stack/18.1.3/defaults/cm.yaml
Labels: ready-for-review, ok-to-test

#173 feat: Bump kubecost to 0.21.1
  services/centralized-kubecost/0.21.1/defaults/cm.yaml
  services/centralized-kubecost/0.21.1/defaults/kustomization.yaml
  services/centralized-kubecost/0.21.1/kustomization.yaml
  services/centralized-kubecost/0.21.1/post-install-jobs.yaml
  services/centralized-kubecost/0.21.1/post-install-jobs/post-install-jobs.yaml
  services/centralized-kubecost/0.21.1/release.yaml
  services/centralized-kubecost/0.21.1/release/release.yaml
  services/kubecost/0.21.1/defaults/cm.yaml
  services/kubecost/0.21.1/defaults/kustomization.yaml
  services/kubecost/0.21.1/kubecost.yaml
  services/kubecost/0.21.1/kustomization.yaml
Labels: ready-for-review, ok-to-test

#170 feat: bump kube-oidc-proxy to 0.3.0
  services/kube-oidc-proxy/0.3.0/defaults/cm.yaml
  services/kube-oidc-proxy/0.3.0/defaults/kustomization.yaml
  services/kube-oidc-proxy/0.3.0/kube-oidc-proxy.yaml
  services/kube-oidc-proxy/0.3.0/kustomization.yaml
Labels: ready-for-review, ok-to-test
