Repository mesosphere/kommander-applications, pull requests merged in 2022-06, with the labels that each got.

#376 feat: Upgrade flux to 0.30.2
  .tool-versions
  services/kommander-flux/0.30.2/defaults/cm.yaml
  services/kommander-flux/0.30.2/defaults/kustomization.yaml
  services/kommander-flux/0.30.2/kustomization.yaml
  services/kommander-flux/0.30.2/patch-proxy-env-vars.yaml
  services/kommander-flux/0.30.2/patch-source-ctrl-network-policy.yaml
  services/kommander-flux/0.30.2/templates/apiextensions.k8s.io_v1_customresourcedefinition_alerts.notification.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.30.2/templates/apiextensions.k8s.io_v1_customresourcedefinition_buckets.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.30.2/templates/apiextensions.k8s.io_v1_customresourcedefinition_gitrepositories.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.30.2/templates/apiextensions.k8s.io_v1_customresourcedefinition_helmcharts.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.30.2/templates/apiextensions.k8s.io_v1_customresourcedefinition_helmreleases.helm.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.30.2/templates/apiextensions.k8s.io_v1_customresourcedefinition_helmrepositories.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.30.2/templates/apiextensions.k8s.io_v1_customresourcedefinition_kustomizations.kustomize.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.30.2/templates/apiextensions.k8s.io_v1_customresourcedefinition_providers.notification.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.30.2/templates/apiextensions.k8s.io_v1_customresourcedefinition_receivers.notification.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.30.2/templates/apps_v1_deployment_helm-controller.yaml
  services/kommander-flux/0.30.2/templates/apps_v1_deployment_kustomize-controller.yaml
  services/kommander-flux/0.30.2/templates/apps_v1_deployment_notification-controller.yaml
  services/kommander-flux/0.30.2/templates/apps_v1_deployment_source-controller.yaml
  services/kommander-flux/0.30.2/templates/kustomization.yaml
  services/kommander-flux/0.30.2/templates/networking.k8s.io_v1_networkpolicy_allow-egress.yaml
  services/kommander-flux/0.30.2/templates/networking.k8s.io_v1_networkpolicy_allow-scraping.yaml
  services/kommander-flux/0.30.2/templates/networking.k8s.io_v1_networkpolicy_allow-source.yaml
  services/kommander-flux/0.30.2/templates/networking.k8s.io_v1_networkpolicy_allow-webhooks.yaml
  services/kommander-flux/0.30.2/templates/rbac.authorization.k8s.io_v1_clusterrole_crd-controller-kommander-flux.yaml
  services/kommander-flux/0.30.2/templates/rbac.authorization.k8s.io_v1_clusterrolebinding_cluster-reconciler-kommander-flux.yaml
  services/kommander-flux/0.30.2/templates/rbac.authorization.k8s.io_v1_clusterrolebinding_crd-controller-kommander-flux.yaml
  services/kommander-flux/0.30.2/templates/v1_namespace_kommander-flux.yaml
  services/kommander-flux/0.30.2/templates/v1_service_notification-controller.yaml
  services/kommander-flux/0.30.2/templates/v1_service_source-controller.yaml
  services/kommander-flux/0.30.2/templates/v1_service_webhook-receiver.yaml
  services/kommander-flux/0.30.2/templates/v1_serviceaccount_helm-controller.yaml
  services/kommander-flux/0.30.2/templates/v1_serviceaccount_kustomize-controller.yaml
  services/kommander-flux/0.30.2/templates/v1_serviceaccount_notification-controller.yaml
  services/kommander-flux/0.30.2/templates/v1_serviceaccount_source-controller.yaml
  services/kommander/0.3.0/defaults/cm.yaml
Labels: ready-for-review, ok-to-test, slack-notify

#406 chore: bump logging operator to 3.17.7
  services/logging-operator/3.17.7/defaults/cm.yaml
  services/logging-operator/3.17.7/defaults/kustomization.yaml
  services/logging-operator/3.17.7/kustomization.yaml
  services/logging-operator/3.17.7/logging-operator-logging.yaml
  services/logging-operator/3.17.7/logging-operator.yaml
Labels: ready-for-review, ok-to-test

#419 feat: bump dex-k8s-authenticator image to v1.2.4-d2iq
  services/dex-k8s-authenticator/1.2.10/defaults/cm.yaml
  services/dex-k8s-authenticator/1.2.10/defaults/kustomization.yaml
  services/dex-k8s-authenticator/1.2.10/dex-k8s-authenticator.yaml
  services/dex-k8s-authenticator/1.2.10/kustomization.yaml
Labels: ready-for-review, ok-to-test

#424 chore: remove no longer needed Traefik init container
  services/kommander/0.3.0/defaults/cm.yaml
  services/traefik/10.9.3/defaults/cm.yaml
  services/traefik/10.9.3/defaults/kustomization.yaml
  services/traefik/10.9.3/grafana-dashboards/kustomization.yaml
  services/traefik/10.9.3/grafana-dashboards/traefik.json
  services/traefik/10.9.3/kustomization.yaml
  services/traefik/10.9.3/traefik-plugin-rewritebody.yaml
  services/traefik/10.9.3/traefik.yaml
Labels: ready-for-review, ok-to-test

#421 [release-2.1] feat: bump dex-k8s-authenticator image to v1.2.4-d2iq
  services/dex-k8s-authenticator/1.2.10/defaults/cm.yaml
  services/dex-k8s-authenticator/1.2.10/defaults/kustomization.yaml
  services/dex-k8s-authenticator/1.2.10/dex-k8s-authenticator.yaml
  services/dex-k8s-authenticator/1.2.10/kustomization.yaml
Labels: ready-for-review, ok-to-test

#422 feat: Bump Istio to 1.13.4
  services/istio/1.13.4/defaults/cm.yaml
  services/istio/1.13.4/defaults/kustomization.yaml
  services/istio/1.13.4/helmrelease.yaml
  services/istio/1.13.4/helmrelease/helmrelease.yaml
  services/istio/1.13.4/kustomization.yaml
Labels: ready-for-review, ok-to-test

#428 fix: Expand Loki storage
  services/grafana-loki/0.48.3/minio.yaml
  services/project-grafana-loki/0.48.3/minio.yaml
Labels: ready-for-review, ok-to-test, needs-backport

#429 chore: Minor bump of kubectl 1.2x
  common/build/kommander-cert-federation.yaml
  services/centralized-grafana/34.9.2/centralized-grafana.yaml
  services/centralized-grafana/34.9.2/defaults/cm.yaml
  services/centralized-grafana/34.9.2/defaults/kustomization.yaml
  services/centralized-grafana/34.9.2/grafana-dashboards/global-overview.json
  services/centralized-grafana/34.9.2/grafana-dashboards/kustomization.yaml
  services/centralized-grafana/34.9.2/kustomization.yaml
  services/centralized-kubecost/0.25.1/defaults/cm.yaml
  services/centralized-kubecost/0.25.1/defaults/kustomization.yaml
  services/centralized-kubecost/0.25.1/kustomization.yaml
  services/centralized-kubecost/0.25.1/post-install-jobs.yaml
  services/centralized-kubecost/0.25.1/post-install-jobs/post-install-jobs.yaml
  services/centralized-kubecost/0.25.1/release.yaml
  services/centralized-kubecost/0.25.1/release/release.yaml
  services/gatekeeper/3.7.0/cleanup/cert-cleanup.yaml
  services/jaeger/2.29.0/pre-upgrade/delete-jaeger-deployment.yaml
  services/kommander/0.3.0/defaults/cm.yaml
  services/kube-prometheus-stack/34.9.2/defaults/cm.yaml
  services/kube-prometheus-stack/34.9.2/defaults/kustomization.yaml
  services/kube-prometheus-stack/34.9.2/grafana-dashboards/calico.json
  services/kube-prometheus-stack/34.9.2/grafana-dashboards/flux-cluster-stats.json
  services/kube-prometheus-stack/34.9.2/grafana-dashboards/flux-control-plane.json
  services/kube-prometheus-stack/34.9.2/grafana-dashboards/grafana.json
  services/kube-prometheus-stack/34.9.2/grafana-dashboards/kustomization.yaml
  services/kube-prometheus-stack/34.9.2/kube-prometheus-stack.yaml
  services/kube-prometheus-stack/34.9.2/kustomization.yaml
  services/kubecost/0.25.1/defaults/cm.yaml
  services/kubecost/0.25.1/defaults/kustomization.yaml
  services/kubecost/0.25.1/kubecost.yaml
  services/kubecost/0.25.1/kustomization.yaml
  services/kubetunnel/0.0.13/defaults/cm.yaml
  services/minio-operator/4.4.16/minio-operator-pre-upgrade/delete-minio-operator-deployment.yaml
  services/thanos/0.4.6/jobs/jobs.yaml
  services/traefik/10.9.3/defaults/cm.yaml
  services/velero/3.2.2/defaults/cm.yaml
  services/velero/3.2.2/defaults/kustomization.yaml
  services/velero/3.2.2/grafana-dashboards/kustomization.yaml
  services/velero/3.2.2/grafana-dashboards/velero.json
  services/velero/3.2.2/kustomization.yaml
  services/velero/3.2.2/velero.yaml
Labels: ready-for-review, ok-to-test

#432 feat: Add helper CLI tool for managing the kommander chart versions
  .github/workflows/test.yaml
  .tool-versions
  hack/release/README.md
  hack/release/cmd/prerelease/prerelease.go
  hack/release/cmd/prerelease/prerelease_test.go
  hack/release/cmd/root.go
  hack/release/go.mod
  hack/release/go.sum
  hack/release/main.go
  make/all.mk
  make/go.mk
Labels: ready-for-review, ok-to-test

#434 feat: Upgrade flux to 0.31.1
  .tool-versions
  services/kommander-flux/0.31.1/defaults/cm.yaml
  services/kommander-flux/0.31.1/defaults/kustomization.yaml
  services/kommander-flux/0.31.1/kustomization.yaml
  services/kommander-flux/0.31.1/patch-proxy-env-vars.yaml
  services/kommander-flux/0.31.1/patch-source-ctrl-network-policy.yaml
  services/kommander-flux/0.31.1/templates/apiextensions.k8s.io_v1_customresourcedefinition_alerts.notification.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.31.1/templates/apiextensions.k8s.io_v1_customresourcedefinition_buckets.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.31.1/templates/apiextensions.k8s.io_v1_customresourcedefinition_gitrepositories.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.31.1/templates/apiextensions.k8s.io_v1_customresourcedefinition_helmcharts.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.31.1/templates/apiextensions.k8s.io_v1_customresourcedefinition_helmreleases.helm.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.31.1/templates/apiextensions.k8s.io_v1_customresourcedefinition_helmrepositories.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.31.1/templates/apiextensions.k8s.io_v1_customresourcedefinition_kustomizations.kustomize.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.31.1/templates/apiextensions.k8s.io_v1_customresourcedefinition_providers.notification.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.31.1/templates/apiextensions.k8s.io_v1_customresourcedefinition_receivers.notification.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.31.1/templates/apps_v1_deployment_helm-controller.yaml
  services/kommander-flux/0.31.1/templates/apps_v1_deployment_kustomize-controller.yaml
  services/kommander-flux/0.31.1/templates/apps_v1_deployment_notification-controller.yaml
  services/kommander-flux/0.31.1/templates/apps_v1_deployment_source-controller.yaml
  services/kommander-flux/0.31.1/templates/kustomization.yaml
  services/kommander-flux/0.31.1/templates/networking.k8s.io_v1_networkpolicy_allow-egress.yaml
  services/kommander-flux/0.31.1/templates/networking.k8s.io_v1_networkpolicy_allow-scraping.yaml
  services/kommander-flux/0.31.1/templates/networking.k8s.io_v1_networkpolicy_allow-source.yaml
  services/kommander-flux/0.31.1/templates/networking.k8s.io_v1_networkpolicy_allow-webhooks.yaml
  services/kommander-flux/0.31.1/templates/rbac.authorization.k8s.io_v1_clusterrole_crd-controller-kommander-flux.yaml
  services/kommander-flux/0.31.1/templates/rbac.authorization.k8s.io_v1_clusterrolebinding_cluster-reconciler-kommander-flux.yaml
  services/kommander-flux/0.31.1/templates/rbac.authorization.k8s.io_v1_clusterrolebinding_crd-controller-kommander-flux.yaml
  services/kommander-flux/0.31.1/templates/v1_namespace_kommander-flux.yaml
  services/kommander-flux/0.31.1/templates/v1_service_notification-controller.yaml
  services/kommander-flux/0.31.1/templates/v1_service_source-controller.yaml
  services/kommander-flux/0.31.1/templates/v1_service_webhook-receiver.yaml
  services/kommander-flux/0.31.1/templates/v1_serviceaccount_helm-controller.yaml
  services/kommander-flux/0.31.1/templates/v1_serviceaccount_kustomize-controller.yaml
  services/kommander-flux/0.31.1/templates/v1_serviceaccount_notification-controller.yaml
  services/kommander-flux/0.31.1/templates/v1_serviceaccount_source-controller.yaml
  services/kommander/0.3.0/defaults/cm.yaml
Labels: ready-for-review, ok-to-test, slack-notify

#436 feat: bump TFA to 0.3.8
  services/traefik-forward-auth-mgmt/0.3.8/defaults/cm.yaml
  services/traefik-forward-auth-mgmt/0.3.8/defaults/kustomization.yaml
  services/traefik-forward-auth-mgmt/0.3.8/kustomization.yaml
  services/traefik-forward-auth-mgmt/0.3.8/traefik-forward-auth-mgmt.yaml
  services/traefik-forward-auth/0.3.8/defaults/cm.yaml
  services/traefik-forward-auth/0.3.8/defaults/kustomization.yaml
  services/traefik-forward-auth/0.3.8/kustomization.yaml
  services/traefik-forward-auth/0.3.8/traefik-forward-auth.yaml
Labels: ready-for-review, ok-to-test, auto-backport, backport-to-release-2.2

#441 chore: kommander: remove unused parameter `ingressCertificateSecret`
  services/kommander/0.3.0/defaults/cm.yaml
Labels: ready-for-review, ok-to-test

#440 Fix kiali references to istio and jaeger
  services/kiali/1.49.1/defaults/cm.yaml
  services/kiali/1.49.1/defaults/kustomization.yaml
  services/kiali/1.49.1/kiali.yaml
  services/kiali/1.49.1/kustomization.yaml
Labels: ready-for-review, ok-to-test, needs-backport

#445 feat: Bump Gitea to 5.0.9
  services/gitea/5.0.9/defaults/cm.yaml
  services/gitea/5.0.9/defaults/kustomization.yaml
  services/gitea/5.0.9/gitea.yaml
  services/gitea/5.0.9/kustomization.yaml
Labels: ready-for-review, ok-to-test

#435 chore: Bump external-dns to 6.5.5
  services/external-dns/6.5.5/defaults/cm.yaml
  services/external-dns/6.5.5/defaults/kustomization.yaml
  services/external-dns/6.5.5/external-dns.yaml
  services/external-dns/6.5.5/kustomization.yaml
Labels: ready-for-review, ok-to-test

#444 feat: Bump grafana-loki to 0.48.4
  services/grafana-loki/0.48.4/defaults/cm.yaml
  services/grafana-loki/0.48.4/defaults/kustomization.yaml
  services/grafana-loki/0.48.4/grafana-loki.yaml
  services/grafana-loki/0.48.4/kustomization.yaml
  services/grafana-loki/0.48.4/minio.yaml
Labels: ready-for-review, ok-to-test

#447 add pre-release hooks to release-2.2 branch
  .github/workflows/test.yaml
  .tool-versions
  hack/release/README.md
  hack/release/cmd/prerelease/prerelease.go
  hack/release/cmd/prerelease/prerelease_test.go
  hack/release/cmd/root.go
  hack/release/go.mod
  hack/release/go.sum
  hack/release/main.go
  make/all.mk
  make/go.mk
Labels: ready-for-review, ok-to-test

#446 chore: bump dex chart version
  services/dex/2.9.18/defaults/cm.yaml
  services/dex/2.9.18/defaults/kustomization.yaml
  services/dex/2.9.18/dex.yaml
  services/dex/2.9.18/kustomization.yaml
Labels: ready-for-review, ok-to-test, auto-backport, backport-to-release-2.2

#433 ci: add make targets to execute e2e tests
  .gitignore
  Dockerfile.ci
  Makefile
  make/all.mk
  make/test.mk
  mergebot-config.json
Labels: ready-for-review, ok-to-test

#452 feat: remove init container from dex-k8s-authenticator
  services/dex-k8s-authenticator/1.2.11/defaults/cm.yaml
  services/dex-k8s-authenticator/1.2.11/defaults/kustomization.yaml
  services/dex-k8s-authenticator/1.2.11/dex-k8s-authenticator.yaml
  services/dex-k8s-authenticator/1.2.11/kustomization.yaml
Labels: ready-for-review, ok-to-test

#450 feat: Bump minio-operator to 4.4.25
  services/minio-operator/4.4.16/minio-operator-pre-upgrade/delete-minio-operator-deployment.yaml
  services/minio-operator/4.4.25/defaults/cm.yaml
  services/minio-operator/4.4.25/defaults/kustomization.yaml
  services/minio-operator/4.4.25/kustomization.yaml
  services/minio-operator/4.4.25/minio-operator-helmrelease.yaml
  services/minio-operator/4.4.25/minio-operator-helmrelease/release.yaml
  services/minio-operator/4.4.25/minio-operator-pre-upgrade.yaml
  services/minio-operator/4.4.25/minio-operator-pre-upgrade/update-minio-tenant-crd-metadata.yaml
  services/minio-operator/4.4.25/minio-tenant-helmrelease.yaml
  services/minio-operator/4.4.25/minio-tenant-helmrelease/release.yaml
Labels: ready-for-review, ok-to-test

#453 feat: Upgrade flux to 0.31.2
  .tool-versions
  services/kommander-flux/0.31.2/defaults/cm.yaml
  services/kommander-flux/0.31.2/defaults/kustomization.yaml
  services/kommander-flux/0.31.2/kustomization.yaml
  services/kommander-flux/0.31.2/patch-proxy-env-vars.yaml
  services/kommander-flux/0.31.2/patch-source-ctrl-network-policy.yaml
  services/kommander-flux/0.31.2/templates/apiextensions.k8s.io_v1_customresourcedefinition_alerts.notification.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.31.2/templates/apiextensions.k8s.io_v1_customresourcedefinition_buckets.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.31.2/templates/apiextensions.k8s.io_v1_customresourcedefinition_gitrepositories.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.31.2/templates/apiextensions.k8s.io_v1_customresourcedefinition_helmcharts.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.31.2/templates/apiextensions.k8s.io_v1_customresourcedefinition_helmreleases.helm.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.31.2/templates/apiextensions.k8s.io_v1_customresourcedefinition_helmrepositories.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.31.2/templates/apiextensions.k8s.io_v1_customresourcedefinition_kustomizations.kustomize.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.31.2/templates/apiextensions.k8s.io_v1_customresourcedefinition_providers.notification.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.31.2/templates/apiextensions.k8s.io_v1_customresourcedefinition_receivers.notification.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.31.2/templates/apps_v1_deployment_helm-controller.yaml
  services/kommander-flux/0.31.2/templates/apps_v1_deployment_kustomize-controller.yaml
  services/kommander-flux/0.31.2/templates/apps_v1_deployment_notification-controller.yaml
  services/kommander-flux/0.31.2/templates/apps_v1_deployment_source-controller.yaml
  services/kommander-flux/0.31.2/templates/kustomization.yaml
  services/kommander-flux/0.31.2/templates/networking.k8s.io_v1_networkpolicy_allow-egress.yaml
  services/kommander-flux/0.31.2/templates/networking.k8s.io_v1_networkpolicy_allow-scraping.yaml
  services/kommander-flux/0.31.2/templates/networking.k8s.io_v1_networkpolicy_allow-source.yaml
  services/kommander-flux/0.31.2/templates/networking.k8s.io_v1_networkpolicy_allow-webhooks.yaml
  services/kommander-flux/0.31.2/templates/rbac.authorization.k8s.io_v1_clusterrole_crd-controller-kommander-flux.yaml
  services/kommander-flux/0.31.2/templates/rbac.authorization.k8s.io_v1_clusterrolebinding_cluster-reconciler-kommander-flux.yaml
  services/kommander-flux/0.31.2/templates/rbac.authorization.k8s.io_v1_clusterrolebinding_crd-controller-kommander-flux.yaml
  services/kommander-flux/0.31.2/templates/v1_namespace_kommander-flux.yaml
  services/kommander-flux/0.31.2/templates/v1_service_notification-controller.yaml
  services/kommander-flux/0.31.2/templates/v1_service_source-controller.yaml
  services/kommander-flux/0.31.2/templates/v1_service_webhook-receiver.yaml
  services/kommander-flux/0.31.2/templates/v1_serviceaccount_helm-controller.yaml
  services/kommander-flux/0.31.2/templates/v1_serviceaccount_kustomize-controller.yaml
  services/kommander-flux/0.31.2/templates/v1_serviceaccount_notification-controller.yaml
  services/kommander-flux/0.31.2/templates/v1_serviceaccount_source-controller.yaml
  services/kommander/0.3.0/defaults/cm.yaml
Labels: ready-for-review, ok-to-test, slack-notify

#456 feat: Upgrade gatekeeper
  services/gatekeeper/3.8.1/cleanup.yaml
  services/gatekeeper/3.8.1/cleanup/cert-cleanup.yaml
  services/gatekeeper/3.8.1/cleanup/kustomization.yaml
  services/gatekeeper/3.8.1/constraints.yaml
  services/gatekeeper/3.8.1/constraints/enforce-helmrelease-sa.yaml
  services/gatekeeper/3.8.1/constraints/enforce-kustomization-sa.yaml
  services/gatekeeper/3.8.1/constrainttemplates.yaml
  services/gatekeeper/3.8.1/constrainttemplates/enforce-sa-constrainttemplate.yaml
  services/gatekeeper/3.8.1/defaults/cm.yaml
  services/gatekeeper/3.8.1/defaults/kustomization.yaml
  services/gatekeeper/3.8.1/kustomization.yaml
  services/gatekeeper/3.8.1/release.yaml
  services/gatekeeper/3.8.1/release/kustomization.yaml
  services/gatekeeper/3.8.1/release/release.yaml
  services/gatekeeper/bootstrap/kustomization.yaml
  services/kommander/0.3.0/defaults/cm.yaml
Labels: ready-for-review, ok-to-test
