Repository mesosphere/kommander-applications, pull requests merged in 2022-08, with the labels that each got.

#514 feat: Move kommander apps into a new directory
  hack/release/cmd/postrelease/postrelease.go
  hack/release/pkg/appversion/appversion.go
  hack/release/pkg/appversion/appversion_test.go
  hack/release/pkg/chartversion/chartversion.go
  hack/release/pkg/constants/constants.go
Labels: ready-for-review, ok-to-test

#524 feat: Bump DKP-Insights to 0.2.3
  services/dkp-insights-management/0.2.3/defaults/cm.yaml
  services/dkp-insights-management/0.2.3/defaults/kustomization.yaml
  services/dkp-insights-management/0.2.3/helmrelease.yaml
  services/dkp-insights-management/0.2.3/helmrelease/helmrelease.yaml
  services/dkp-insights-management/0.2.3/kustomization.yaml
Labels: ready-for-review, ok-to-test, needs-backport, auto-backport, backport-to-release-2.3

#508 fix: Remove gk 2.2 upgrade job
  services/gatekeeper/3.8.1/cleanup.yaml
  services/gatekeeper/3.8.1/cleanup/cert-cleanup.yaml
  services/gatekeeper/3.8.1/cleanup/kustomization.yaml
  services/gatekeeper/3.8.1/kustomization.yaml
  services/gatekeeper/3.8.1/release.yaml
Labels: ready-for-review, ok-to-test, needs-backport

#512 feat: Upgrade flux to 0.31.5
  .tool-versions
  services/kommander-flux/0.31.5/defaults/cm.yaml
  services/kommander-flux/0.31.5/defaults/kustomization.yaml
  services/kommander-flux/0.31.5/kustomization.yaml
  services/kommander-flux/0.31.5/patch-proxy-env-vars.yaml
  services/kommander-flux/0.31.5/patch-source-ctrl-network-policy.yaml
  services/kommander-flux/0.31.5/templates/apiextensions.k8s.io_v1_customresourcedefinition_alerts.notification.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.31.5/templates/apiextensions.k8s.io_v1_customresourcedefinition_buckets.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.31.5/templates/apiextensions.k8s.io_v1_customresourcedefinition_gitrepositories.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.31.5/templates/apiextensions.k8s.io_v1_customresourcedefinition_helmcharts.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.31.5/templates/apiextensions.k8s.io_v1_customresourcedefinition_helmreleases.helm.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.31.5/templates/apiextensions.k8s.io_v1_customresourcedefinition_helmrepositories.source.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.31.5/templates/apiextensions.k8s.io_v1_customresourcedefinition_kustomizations.kustomize.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.31.5/templates/apiextensions.k8s.io_v1_customresourcedefinition_providers.notification.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.31.5/templates/apiextensions.k8s.io_v1_customresourcedefinition_receivers.notification.toolkit.fluxcd.io.yaml
  services/kommander-flux/0.31.5/templates/apps_v1_deployment_helm-controller.yaml
  services/kommander-flux/0.31.5/templates/apps_v1_deployment_kustomize-controller.yaml
  services/kommander-flux/0.31.5/templates/apps_v1_deployment_notification-controller.yaml
  services/kommander-flux/0.31.5/templates/apps_v1_deployment_source-controller.yaml
  services/kommander-flux/0.31.5/templates/kustomization.yaml
  services/kommander-flux/0.31.5/templates/networking.k8s.io_v1_networkpolicy_allow-egress.yaml
  services/kommander-flux/0.31.5/templates/networking.k8s.io_v1_networkpolicy_allow-scraping.yaml
  services/kommander-flux/0.31.5/templates/networking.k8s.io_v1_networkpolicy_allow-source.yaml
  services/kommander-flux/0.31.5/templates/networking.k8s.io_v1_networkpolicy_allow-webhooks.yaml
  services/kommander-flux/0.31.5/templates/rbac.authorization.k8s.io_v1_clusterrole_crd-controller-kommander-flux.yaml
  services/kommander-flux/0.31.5/templates/rbac.authorization.k8s.io_v1_clusterrolebinding_cluster-reconciler-kommander-flux.yaml
  services/kommander-flux/0.31.5/templates/rbac.authorization.k8s.io_v1_clusterrolebinding_crd-controller-kommander-flux.yaml
  services/kommander-flux/0.31.5/templates/v1_namespace_kommander-flux.yaml
  services/kommander-flux/0.31.5/templates/v1_service_notification-controller.yaml
  services/kommander-flux/0.31.5/templates/v1_service_source-controller.yaml
  services/kommander-flux/0.31.5/templates/v1_service_webhook-receiver.yaml
  services/kommander-flux/0.31.5/templates/v1_serviceaccount_helm-controller.yaml
  services/kommander-flux/0.31.5/templates/v1_serviceaccount_kustomize-controller.yaml
  services/kommander-flux/0.31.5/templates/v1_serviceaccount_notification-controller.yaml
  services/kommander-flux/0.31.5/templates/v1_serviceaccount_source-controller.yaml
  services/kommander/0.4.0/defaults/cm.yaml
Labels: ready-for-review, ok-to-test, slack-notify

#515 feat: Change kommander apps variable names
  hack/release/cmd/postrelease/postrelease.go
  hack/release/pkg/appversion/appversion.go
  hack/release/pkg/appversion/appversion_test.go
  hack/release/pkg/constants/constants.go
Labels: ready-for-review, ok-to-test

#526 fix: Do not move if target is the same
  hack/release/pkg/appversion/appversion.go
Labels: ready-for-review, ok-to-test

#528 fix: increase flux helm-controller memory/CPU limit
  services/kommander-flux/0.31.5/templates/apps_v1_deployment_helm-controller.yaml
Labels: ready-for-review, ok-to-test, needs-backport, auto-backport, backport-to-release-2.3

#531 feat: bump project-grafana-loki to 0.48.4
  services/project-grafana-loki/0.48.4/defaults/cm.yaml
  services/project-grafana-loki/0.48.4/defaults/kustomization.yaml
  services/project-grafana-loki/0.48.4/kustomization.yaml
  services/project-grafana-loki/0.48.4/minio.yaml
  services/project-grafana-loki/0.48.4/project-grafana-loki.yaml
Labels: ready-for-review, ok-to-test

#534 feat: enable compaction in grafana-loki defaults cm
  services/grafana-loki/0.48.4/defaults/cm.yaml
  services/project-grafana-loki/0.48.4/defaults/cm.yaml
Labels: ready-for-review, ok-to-test, auto-backport, backport-to-release-2.3

#538 chore: Start adding labels to PRs according to their size
  .github/code.yml
Labels: ready-for-review, ok-to-test

#536 feat: Kubefed v0.10.0
  services/kubefed/0.10.0/defaults/cm.yaml
  services/kubefed/0.10.0/defaults/kustomization.yaml
  services/kubefed/0.10.0/federatedtypeconfigs.yaml
  services/kubefed/0.10.0/federatedtypeconfigs/federatedtypeconfigs.yaml
  services/kubefed/0.10.0/kube-federation-system-namespace.yaml
  services/kubefed/0.10.0/kube-federation-system-namespace/kube-federation-system.yaml
  services/kubefed/0.10.0/kustomization.yaml
  services/kubefed/0.10.0/release.yaml
  services/kubefed/0.10.0/release/release.yaml
Labels: ready-for-review, ok-to-test

#541 fix: `warn` log level for multiple logging stack components
  services/fluent-bit/0.19.20/defaults/cm.yaml
  services/grafana-loki/0.48.4/defaults/cm.yaml
  services/project-grafana-loki/0.48.4/defaults/cm.yaml
Labels: ready-for-review, ok-to-test, backport-pr, auto-backport, backport-to-release-2.3

#543 fix: Move workflow file to its directory
  .github/workflows/code.yml
Labels: ready-for-review, ok-to-test, size/XS

#544 feat: Kubetunnel v0.0.14
  services/kubetunnel/0.0.14/defaults/cm.yaml
  services/kubetunnel/0.0.14/defaults/kustomization.yaml
  services/kubetunnel/0.0.14/kubetunnel.yaml
  services/kubetunnel/0.0.14/kustomization.yaml
Labels: ready-for-review, ok-to-test, size/XS

#545 feat: configurable log level
  hack/flux/update-flux.sh
  services/centralized-grafana/34.9.3/defaults/cm.yaml
  services/fluent-bit/0.19.20/defaults/cm.yaml
  services/grafana-logging/6.28.0/defaults/cm.yaml
  services/grafana-loki/0.48.4/defaults/cm.yaml
  services/karma/2.0.1/defaults/cm.yaml
  services/kommander-flux/0.31.5/templates/apps_v1_deployment_helm-controller.yaml
  services/kommander-flux/0.31.5/templates/apps_v1_deployment_kustomize-controller.yaml
  services/kommander-flux/0.31.5/templates/apps_v1_deployment_notification-controller.yaml
  services/kommander-flux/0.31.5/templates/apps_v1_deployment_source-controller.yaml
  services/kube-prometheus-stack/34.9.3/defaults/cm.yaml
  services/kubecost/0.26.0/defaults/cm.yaml
  services/logging-operator/3.17.7/defaults/cm.yaml
  services/project-grafana-logging/6.28.0/defaults/cm.yaml
  services/project-grafana-loki/0.48.4/defaults/cm.yaml
  services/prometheus-adapter/2.17.1/defaults/cm.yaml
  services/traefik-forward-auth-mgmt/0.3.9/defaults/cm.yaml
  services/traefik-forward-auth/0.3.8/defaults/cm.yaml
Labels: ready-for-review, ok-to-test, size/M

#548 revert: karma config map change of `warn` level
  hack/flux/update-flux.sh
  services/fluent-bit/0.19.21/grafana-dashboards-logging/audit.json
  services/fluent-bit/0.19.21/grafana-dashboards-logging/kustomization.yaml
  services/fluent-bit/0.19.21/kustomization.yaml
  services/grafana-logging/6.28.0/kustomization.yaml
  services/karma/2.0.1/defaults/cm.yaml
  services/kommander-flux/0.31.4/templates/apps_v1_deployment_helm-controller.yaml
  services/kommander-flux/0.31.4/templates/apps_v1_deployment_kustomize-controller.yaml
  services/kommander-flux/0.31.4/templates/apps_v1_deployment_notification-controller.yaml
  services/kommander-flux/0.31.4/templates/apps_v1_deployment_source-controller.yaml
  services/prometheus-adapter/2.17.1/defaults/cm.yaml
Labels: ready-for-review, ok-to-test

#540 fix(loki): set flush_op_timeout to 10m
  services/grafana-loki/0.48.4/defaults/cm.yaml
  services/project-grafana-loki/0.48.4/defaults/cm.yaml
Labels: ready-for-review, ok-to-test, needs-backport, auto-backport, backport-to-release-2.2

#550 chore: revert flux controllers log level changes
  hack/flux/update-flux.sh
  services/karma/2.0.1/defaults/cm.yaml
  services/kommander-flux/0.31.5/templates/apps_v1_deployment_helm-controller.yaml
  services/kommander-flux/0.31.5/templates/apps_v1_deployment_kustomize-controller.yaml
  services/kommander-flux/0.31.5/templates/apps_v1_deployment_notification-controller.yaml
  services/kommander-flux/0.31.5/templates/apps_v1_deployment_source-controller.yaml
Labels: ready-for-review, ok-to-test, size/S

#551 feat: dex upgrade chart to v2.10.0
  services/dex/2.10.0/defaults/cm.yaml
  services/dex/2.10.0/defaults/kustomization.yaml
  services/dex/2.10.0/dex.yaml
  services/dex/2.10.0/kustomization.yaml
Labels: ready-for-review, ok-to-test

#539 feat: Update project-grafana-loki values
  services/grafana-loki/0.48.4/defaults/cm.yaml
  services/project-grafana-loki/0.48.4/defaults/cm.yaml
Labels: ok-to-test, size/S

#557 feat: Upgrade kube-prometheus-stack to 39.7.0
  services/centralized-grafana/39.7.0/centralized-grafana.yaml
  services/centralized-grafana/39.7.0/defaults/cm.yaml
  services/centralized-grafana/39.7.0/defaults/kustomization.yaml
  services/centralized-grafana/39.7.0/grafana-dashboards/global-overview.json
  services/centralized-grafana/39.7.0/grafana-dashboards/kustomization.yaml
  services/centralized-grafana/39.7.0/kustomization.yaml
  services/kommander/0.4.0/defaults/cm.yaml
  services/kube-prometheus-stack/39.7.0/defaults/cm.yaml
  services/kube-prometheus-stack/39.7.0/defaults/kustomization.yaml
  services/kube-prometheus-stack/39.7.0/grafana-dashboards/calico.json
  services/kube-prometheus-stack/39.7.0/grafana-dashboards/flux-cluster-stats.json
  services/kube-prometheus-stack/39.7.0/grafana-dashboards/flux-control-plane.json
  services/kube-prometheus-stack/39.7.0/grafana-dashboards/kustomization.yaml
  services/kube-prometheus-stack/39.7.0/kube-prometheus-stack.yaml
  services/kube-prometheus-stack/39.7.0/kustomization.yaml
Labels: ok-to-test, size/S

#558 fix: Prevent gatekeeper from ignoring the kommander namespace
  services/gatekeeper/3.8.1/defaults/cm.yaml
Labels: ready-for-review, ok-to-test, needs-backport, auto-backport, backport-to-release-2.2, backport-to-release-2.1, backport-to-release-2.3, size/XS

#556 feat: Bump kubecost to 0.27.0
  services/centralized-kubecost/0.27.0/defaults/cm.yaml
  services/centralized-kubecost/0.27.0/defaults/kustomization.yaml
  services/centralized-kubecost/0.27.0/kustomization.yaml
  services/centralized-kubecost/0.27.0/post-install-jobs.yaml
  services/centralized-kubecost/0.27.0/post-install-jobs/post-install-jobs.yaml
  services/centralized-kubecost/0.27.0/release.yaml
  services/centralized-kubecost/0.27.0/release/release.yaml
  services/kommander/0.4.0/defaults/cm.yaml
  services/kubecost/0.27.0/defaults/cm.yaml
  services/kubecost/0.27.0/defaults/kustomization.yaml
  services/kubecost/0.27.0/kubecost.yaml
  services/kubecost/0.27.0/kustomization.yaml
Labels: ok-to-test, needs-backport, auto-backport, backport-to-release-2.3, size/S

#555 feat: Bump reloader to 0.0.118
  services/kommander/0.4.0/defaults/cm.yaml
  services/reloader/0.0.118/defaults/cm.yaml
  services/reloader/0.0.118/defaults/kustomization.yaml
  services/reloader/0.0.118/kustomization.yaml
  services/reloader/0.0.118/reloader.yaml
Labels: ready-for-review, ok-to-test, do-not-merge/testing, size/XS

#530 feat: bump gitea to v6.0.0
  services/gitea/6.0.0/defaults/cm.yaml
  services/gitea/6.0.0/defaults/kustomization.yaml
  services/gitea/6.0.0/gitea.yaml
  services/gitea/6.0.0/kustomization.yaml
Labels: ready-for-review, ok-to-test, size/XS

#577 fix: Fix loki writes resources dashboard title
  services/grafana-loki/0.48.4/grafana-dashboards/loki-writes-resources.json
Labels: ready-for-review, ok-to-test, size/XS

#582 build: Bump e2e and mergebot config versions post-2.3
  make/test.mk
  mergebot-config.json
Labels: ready-for-review, ok-to-test, size/XS

#581 fix: Revert kube-prometheus-stack bump to 39.7.0 (#557)
  services/centralized-grafana/34.9.3/centralized-grafana.yaml
  services/centralized-grafana/34.9.3/defaults/cm.yaml
  services/centralized-grafana/34.9.3/defaults/kustomization.yaml
  services/centralized-grafana/34.9.3/grafana-dashboards/global-overview.json
  services/centralized-grafana/34.9.3/grafana-dashboards/kustomization.yaml
  services/centralized-grafana/34.9.3/kustomization.yaml
  services/kommander/0.4.0/defaults/cm.yaml
  services/kube-prometheus-stack/34.9.3/defaults/cm.yaml
  services/kube-prometheus-stack/34.9.3/defaults/kustomization.yaml
  services/kube-prometheus-stack/34.9.3/grafana-dashboards/calico.json
  services/kube-prometheus-stack/34.9.3/grafana-dashboards/flux-cluster-stats.json
  services/kube-prometheus-stack/34.9.3/grafana-dashboards/flux-control-plane.json
  services/kube-prometheus-stack/34.9.3/grafana-dashboards/kustomization.yaml
  services/kube-prometheus-stack/34.9.3/kube-prometheus-stack.yaml
  services/kube-prometheus-stack/34.9.3/kustomization.yaml
Labels: ready-for-review, ok-to-test, size/S

#554 feat: Deploy resource quota with fluent-bit
  services/fluent-bit/0.20.5/kustomization.yaml
  services/fluent-bit/0.20.5/resource-quota.yaml
  services/fluent-bit/0.20.5/resource-quota/resourcequota.yaml
Labels: ready-for-review, ok-to-test, auto-backport, backport-to-release-2.3, size/M
