Repository mesosphere/kommander-applications, pull requests merged in 2023-09, with the labels that each got.

#1538 fix: disables telemetry transmission for Grafana
  services/centralized-grafana/48.3.1/defaults/cm.yaml
  services/grafana-logging/6.58.6/defaults/cm.yaml
  services/kube-prometheus-stack/48.3.1/defaults/cm.yaml
  services/kubecost/0.35.1/defaults/cm.yaml
  services/project-grafana-logging/6.58.6/defaults/cm.yaml
Labels: bug, ready-for-review, ok-to-test, auto-backport, size/S, services/centralized-grafana, services/grafana-logging, services/kube-prometheus-stack, services/kubecost, services/project-grafana-logging, backport-to-release-2.4, backport-to-release-2.5, backport-to-release-2.6

#1545 feat: bump kubetunnel to v0.0.29
  licenses.d2iq.yaml
  services/kubetunnel/0.0.29/defaults/cm.yaml
  services/kubetunnel/0.0.29/defaults/kustomization.yaml
  services/kubetunnel/0.0.29/extra-images.txt
  services/kubetunnel/0.0.29/kubetunnel.yaml
  services/kubetunnel/0.0.29/kustomization.yaml
Labels: ready-for-review, ok-to-test, size/S, open-kommander-pr, services/kubetunnel

#1543 feat: Release DKP-Insights v0.6.0-dev.5
  licenses.d2iq.yaml
  services/dkp-insights-management/0.6.0/defaults/cm.yaml
  services/dkp-insights-management/0.6.0/helmrelease/helmrelease.yaml
  services/dkp-insights/0.6.0/defaults/cm.yaml
  services/dkp-insights/0.6.0/helmrelease/helmrelease.yaml
Labels: ready-for-review, ok-to-test, size/S, services/dkp-insights-management, services/dkp-insights

#1516 feat(koperator): Update CRD
  charts/kommander-operator/crds/crd_kommandercores.yaml
Labels: ready-for-review, ok-to-test, size/L

#1547 feat: Introduce empty kustomization of ai-navigation-app
  .github/service-labeler.yaml
  services/ai-navigator-app/0.1.0/defaults/cm.yaml
  services/ai-navigator-app/0.1.0/defaults/kustomization.yaml
  services/ai-navigator-app/0.1.0/kustomization.yaml
  services/ai-navigator-app/metadata.yaml
Labels: ready-for-review, ok-to-test, let-me-merge-it, size/S, services/ai-navigator-app

#1546 feat: kubetunnel bump backport 2.6
  licenses.d2iq.yaml
  services/kubetunnel/0.0.29/defaults/cm.yaml
  services/kubetunnel/0.0.29/defaults/kustomization.yaml
  services/kubetunnel/0.0.29/extra-images.txt
  services/kubetunnel/0.0.29/kubetunnel.yaml
  services/kubetunnel/0.0.29/kustomization.yaml
Labels: ready-for-review, ok-to-test, size/S

#1550 build: Change the way we execute release target
  .github/workflows/release.yml
Labels: ready-for-review, ok-to-test, size/XS

#1557 fix: fixes linter to stay in the release-branch 2.6
  make/pre-commit.mk
Labels: bug, ready-for-review, ok-to-test, size/XS

#1559 fix: fixes linter to stay on release branch 2.5
  make/pre-commit.mk
Labels: bug, ready-for-review, ok-to-test, size/XS

#1560 fix: fixes linter to stay on release branch 2.4
  make/pre-commit.mk
Labels: bug, ready-for-review, ok-to-test, size/XS

#1553 fix: change dkp-insights logo
  services/dkp-insights/metadata.yaml
Labels: ready-for-review, ok-to-test, size/XS, services/dkp-insights

#1552 feat(koperator): Update chart version, pass version into deployment
  charts/kommander-operator/Chart.yaml
  charts/kommander-operator/templates/deployment.yaml
  charts/kommander-operator/templates/post_install_kommandercore_hook.yaml
  charts/kommander-operator/values.yaml
  common/kommander-operator/helmrelease.yaml
Labels: ready-for-review, ok-to-test, size/S

#1514 feat: add ai-navigator-app
  services/ai-navigator-app/0.1.0/ai-navigator-app.yaml
  services/ai-navigator-app/0.1.0/kustomization.yaml
  services/ai-navigator-app/metadata.yaml
Labels: ready-for-review, ok-to-test, needs-backport, auto-backport, size/L, backport-to-release-2.6, services/ai-navigator-app

#1562 feat: Bump kube-prometheus-stack to 46.8.1
  licenses.d2iq.yaml
  services/kube-prometheus-stack/46.8.1/defaults/cm.yaml
  services/kube-prometheus-stack/46.8.1/defaults/kustomization.yaml
  services/kube-prometheus-stack/46.8.1/etcd-metrics-proxy.yaml
  services/kube-prometheus-stack/46.8.1/etcd-metrics-proxy/cert.yaml
  services/kube-prometheus-stack/46.8.1/etcd-metrics-proxy/client-rbac.yaml
  services/kube-prometheus-stack/46.8.1/etcd-metrics-proxy/kube-rbac-proxy.yaml
  services/kube-prometheus-stack/46.8.1/grafana-dashboards/calico.json
  services/kube-prometheus-stack/46.8.1/grafana-dashboards/controller-runtime.json
  services/kube-prometheus-stack/46.8.1/grafana-dashboards/flux-cluster-stats.json
  services/kube-prometheus-stack/46.8.1/grafana-dashboards/flux-control-plane.json
  services/kube-prometheus-stack/46.8.1/grafana-dashboards/kustomization.yaml
  services/kube-prometheus-stack/46.8.1/helmrelease.yaml
  services/kube-prometheus-stack/46.8.1/helmrelease/extra-images.txt
  services/kube-prometheus-stack/46.8.1/helmrelease/kube-prometheus-stack.yaml
  services/kube-prometheus-stack/46.8.1/helmrelease/kustomization.yaml
  services/kube-prometheus-stack/46.8.1/kustomization.yaml
Labels: ready-for-review, ok-to-test, size/S, services/kube-prometheus-stack, update-licenses

#1544 chore: bump gitea to v9.3.0
  licenses.d2iq.yaml
  services/gitea/9.3.0/defaults/cm.yaml
  services/gitea/9.3.0/defaults/kustomization.yaml
  services/gitea/9.3.0/gitea.yaml
  services/gitea/9.3.0/kustomization.yaml
  services/gitea/9.3.0/pvc.yaml
Labels: ready-for-review, ok-to-test, size/M, services/gitea

#1569 feat: Bump kube-prometheus-stack to 44.2.3
  services/kommander/0.5.2/defaults/cm.yaml
  services/kube-prometheus-stack/44.2.3/defaults/cm.yaml
  services/kube-prometheus-stack/44.2.3/defaults/kustomization.yaml
  services/kube-prometheus-stack/44.2.3/grafana-dashboards/calico.json
  services/kube-prometheus-stack/44.2.3/grafana-dashboards/controller-runtime.json
  services/kube-prometheus-stack/44.2.3/grafana-dashboards/flux-cluster-stats.json
  services/kube-prometheus-stack/44.2.3/grafana-dashboards/flux-control-plane.json
  services/kube-prometheus-stack/44.2.3/grafana-dashboards/kustomization.yaml
  services/kube-prometheus-stack/44.2.3/helmrelease.yaml
  services/kube-prometheus-stack/44.2.3/helmrelease/kube-prometheus-stack.yaml
  services/kube-prometheus-stack/44.2.3/kustomization.yaml
  services/kube-prometheus-stack/44.2.3/pre-upgrade.yaml
  services/kube-prometheus-stack/44.2.3/pre-upgrade/delete-node-exporter-daemonset.yaml
Labels: ready-for-review, ok-to-test, size/S

#1549 fix: create dev tag pipeline
  .github/workflows/create-dev-tag.yml
Labels: ok-to-test, size/M

#1531 feat: Bump prometheus-adapter to 4.4.1
  services/prometheus-adapter/4.4.1/defaults/cm.yaml
  services/prometheus-adapter/4.4.1/defaults/kustomization.yaml
  services/prometheus-adapter/4.4.1/helmrelease/prometheus-adapter.yaml
  services/prometheus-adapter/4.4.1/kustomization.yaml
  services/prometheus-adapter/4.4.1/prometheus-adapter-helmrelease.yaml
Labels: ready-for-review, ok-to-test, size/XS, services/prometheus-adapter, update-licenses

#1576 feat: Release DKP-Insights v0.6.0-dev.6
  licenses.d2iq.yaml
  services/dkp-insights-management/0.6.0/defaults/cm.yaml
  services/dkp-insights-management/0.6.0/helmrelease/helmrelease.yaml
  services/dkp-insights/0.6.0/defaults/cm.yaml
  services/dkp-insights/0.6.0/helmrelease/helmrelease.yaml
Labels: ready-for-review, ok-to-test, services/dkp-insights-management, services/dkp-insights

#1584 chore: Post release bumps
  mergebot-config.json
Labels: ok-to-test, size/XS

#1582 chore: Post release bumps
  mergebot-config.json
Labels: ready-for-review, ok-to-test, size/XS

#1586 build: Add a workflow to build artifacts for 2.6 branch
  .github/workflows/release.yml
Labels: ready-for-review, ok-to-test, size/M

#1588 build: Add a workflow to build artifacts for 2.4 branch
  .github/workflows/release.yml
Labels: ready-for-review, ok-to-test, size/M

#1590 fix: disables E2E tests on release-2.6
  mergebot-config.json
Labels: bug, ready-for-review, ok-to-test, size/S

#1583 chore: Post release bumps
  common/kommander-operator/helmrelease.yaml
  mergebot-config.json
  services/gatekeeper/3.11.1/pre-upgrade/pre-upgrade.yaml
  services/kommander-appmanagement/0.5.3/defaults/cm.yaml
  services/kommander-appmanagement/0.5.3/defaults/kustomization.yaml
  services/kommander-appmanagement/0.5.3/kommander-appmanagement.yaml
  services/kommander-appmanagement/0.5.3/kustomization.yaml
  services/kommander/0.5.3/defaults/cm.yaml
  services/kommander/0.5.3/defaults/kustomization.yaml
  services/kommander/0.5.3/dynamic-helmreleases/README.txt
  services/kommander/0.5.3/dynamic-helmreleases/cluster-observer/cluster-observer.yaml
  services/kommander/0.5.3/dynamic-helmreleases/cluster-observer/kustomization.yaml
  services/kommander/0.5.3/dynamic-helmreleases/mtls-proxy/kustomization.yaml
  services/kommander/0.5.3/dynamic-helmreleases/mtls-proxy/mtls-proxy.yaml
  services/kommander/0.5.3/kommander.yaml
  services/kommander/0.5.3/kustomization.yaml
  services/kubecost/0.33.2/pre-upgrade/pre-upgrade.yaml
  services/logging-operator/3.17.11/pre-upgrade/pre-upgrade.yaml
Labels: ready-for-review, ok-to-test, size/S

#1591 fix: disables E2E tests on release-2.5
  mergebot-config.json
Labels: bug, ready-for-review, ok-to-test, size/S

#1593 fix: disables E2E tests on release-2.4
  mergebot-config.json
Labels: bug, ready-for-review, ok-to-test, size/S

#1580 chore: Post release bumps
  mergebot-config.json
Labels: ready-for-review, ok-to-test, size/XS

#1594 build: validate manifests against 1.28.0
  .bloodhound.yml
Labels: ready-for-review, ok-to-test, size/XS

#1527 feat: Bump loki-distributed to 0.71.2
  licenses.d2iq.yaml
  services/grafana-loki/0.71.2/defaults/cm.yaml
  services/grafana-loki/0.71.2/defaults/kustomization.yaml
  services/grafana-loki/0.71.2/grafana-dashboards-logging/kustomization.yaml
  services/grafana-loki/0.71.2/grafana-dashboards-logging/logging-loki-dashboard.json
  services/grafana-loki/0.71.2/grafana-dashboards/grafana-loki.json
  services/grafana-loki/0.71.2/grafana-dashboards/kustomization.yaml
  services/grafana-loki/0.71.2/grafana-dashboards/loki-chunks.json
  services/grafana-loki/0.71.2/grafana-dashboards/loki-deletion.json
  services/grafana-loki/0.71.2/grafana-dashboards/loki-reads-resources.json
  services/grafana-loki/0.71.2/grafana-dashboards/loki-retention.json
  services/grafana-loki/0.71.2/grafana-dashboards/loki-writes-resources.json
  services/grafana-loki/0.71.2/grafana-loki-helmrelease.yaml
  services/grafana-loki/0.71.2/grafana-loki-helmrelease/grafana-loki.yaml
  services/grafana-loki/0.71.2/grafana-loki-pre-install-jobs/pre-install.yaml
  services/grafana-loki/0.71.2/grafana-loki-pre-install.yaml
  services/grafana-loki/0.71.2/kustomization.yaml
  services/project-grafana-loki/0.71.2/defaults/cm.yaml
  services/project-grafana-loki/0.71.2/defaults/kustomization.yaml
  services/project-grafana-loki/0.71.2/grafana-dashboards-logging/kustomization.yaml
  services/project-grafana-loki/0.71.2/grafana-dashboards-logging/logging-loki-dashboard.json
  services/project-grafana-loki/0.71.2/kustomization.yaml
  services/project-grafana-loki/0.71.2/object-bucket-claims.yaml
  services/project-grafana-loki/0.71.2/project-grafana-loki.yaml
Labels: ready-for-review, ok-to-test, size/S, open-kommander-pr, services/grafana-loki, services/project-grafana-loki, update-licenses

#1529 feat: Bump external-dns to 6.24.1
  licenses.d2iq.yaml
  services/external-dns/6.24.1/defaults/cm.yaml
  services/external-dns/6.24.1/defaults/kustomization.yaml
  services/external-dns/6.24.1/external-dns.yaml
  services/external-dns/6.24.1/kustomization.yaml
Labels: ready-for-review, ok-to-test, size/XS, open-kommander-pr, services/external-dns, update-licenses

#1595 ci: Disable 2.3
  .github/workflows/create-dev-tag.yml
Labels: ready-for-review, ok-to-test, size/XS

#1585 feat(ai-navigator): set proper resource limits and requests
  services/ai-navigator-app/0.1.0/ai-navigator-app.yaml
  services/ai-navigator-app/0.1.0/defaults/cm.yaml
  services/ai-navigator-app/0.1.0/defaults/kustomization.yaml
Labels: ready-for-review, ok-to-test, needs-backport, auto-backport, size/S, backport-to-release-2.6, services/ai-navigator-app

#1563 chore: Update coveralls setup
  .github/workflows/test.yaml
  .go-tools
  make/go.mk
Labels: ok-to-test, size/S

#1602 chore: Post release bumps
  mergebot-config.json
Labels: size/XS

#1601 chore: Post release bumps
  mergebot-config.json
Labels: size/XS

#1600 chore: Post release bumps
  mergebot-config.json
Labels: size/XS

#1606 feat: Release DKP-Insights v0.6.0-dev.7
  licenses.d2iq.yaml
  services/dkp-insights-management/0.6.0/defaults/cm.yaml
  services/dkp-insights-management/0.6.0/helmrelease/helmrelease.yaml
  services/dkp-insights/0.6.0/defaults/cm.yaml
  services/dkp-insights/0.6.0/helmrelease/helmrelease.yaml
Labels: ready-for-review, ok-to-test, size/M, services/dkp-insights-management, services/dkp-insights

#1568 feat(koperator): Revert to using arbitrary chart version
  charts/kommander-operator/Chart.yaml
  charts/kommander-operator/templates/deployment.yaml
  charts/kommander-operator/templates/post_install_kommandercore_hook.yaml
  charts/kommander-operator/templates/rback_v1_clusterrole_operator_kommander-operator.yaml
  common/kommander-operator/helmrelease.yaml
Labels: ready-for-review, ok-to-test, size/S

#1613 ci: add workflow_dispatch on release workflow (2.6)
  .github/workflows/release.yml
Labels: ready-for-review, ok-to-test, size/XS

#1614 ci: add workflow_dispatch on release workflow (2.5)
  .github/workflows/release.yml
Labels: ready-for-review, ok-to-test, size/XS

#1615 ci: add workflow_dispatch on release workflow (2.4)
  .github/workflows/release.yml
Labels: ready-for-review, ok-to-test, size/XS

#1611 fix: update-licenses reorders keys and removes comments
  .github/workflows/validate-licenses.yaml
Labels: ready-for-review, size/XS, update-licenses

#1627 feat: Bump loki-distributed to 0.74.5
  licenses.d2iq.yaml
  services/grafana-loki/0.74.5/defaults/cm.yaml
  services/grafana-loki/0.74.5/defaults/kustomization.yaml
  services/grafana-loki/0.74.5/grafana-dashboards-logging/kustomization.yaml
  services/grafana-loki/0.74.5/grafana-dashboards-logging/logging-loki-dashboard.json
  services/grafana-loki/0.74.5/grafana-dashboards/grafana-loki.json
  services/grafana-loki/0.74.5/grafana-dashboards/kustomization.yaml
  services/grafana-loki/0.74.5/grafana-dashboards/loki-chunks.json
  services/grafana-loki/0.74.5/grafana-dashboards/loki-deletion.json
  services/grafana-loki/0.74.5/grafana-dashboards/loki-reads-resources.json
  services/grafana-loki/0.74.5/grafana-dashboards/loki-retention.json
  services/grafana-loki/0.74.5/grafana-dashboards/loki-writes-resources.json
  services/grafana-loki/0.74.5/grafana-loki-helmrelease.yaml
  services/grafana-loki/0.74.5/grafana-loki-helmrelease/grafana-loki.yaml
  services/grafana-loki/0.74.5/grafana-loki-pre-install-jobs/pre-install.yaml
  services/grafana-loki/0.74.5/grafana-loki-pre-install.yaml
  services/grafana-loki/0.74.5/kustomization.yaml
  services/project-grafana-loki/0.74.5/defaults/cm.yaml
  services/project-grafana-loki/0.74.5/defaults/kustomization.yaml
  services/project-grafana-loki/0.74.5/grafana-dashboards-logging/kustomization.yaml
  services/project-grafana-loki/0.74.5/grafana-dashboards-logging/logging-loki-dashboard.json
  services/project-grafana-loki/0.74.5/kustomization.yaml
  services/project-grafana-loki/0.74.5/object-bucket-claims.yaml
  services/project-grafana-loki/0.74.5/project-grafana-loki.yaml
Labels: ready-for-review, ok-to-test, size/S, open-kommander-pr, services/grafana-loki, services/project-grafana-loki, update-licenses

#1604 feat: bump cert-manager to v1.12.3
  licenses.d2iq.yaml
  services/cert-manager/1.12.3/cert-manager-namespace.yaml
  services/cert-manager/1.12.3/cert-manager-namespace/namespace.yaml
  services/cert-manager/1.12.3/defaults/cm.yaml
  services/cert-manager/1.12.3/defaults/kustomization.yaml
  services/cert-manager/1.12.3/kustomization.yaml
  services/cert-manager/1.12.3/priorityclass-resource-quota.yaml
  services/cert-manager/1.12.3/priorityclass-resource-quota/resourcequota.yaml
  services/cert-manager/1.12.3/release.yaml
  services/cert-manager/1.12.3/release/kustomization.yaml
  services/cert-manager/1.12.3/release/release.yaml
  services/cert-manager/1.12.3/root-ca.yaml
  services/cert-manager/1.12.3/root-ca/root-ca.yaml
  services/cert-manager/bootstrap/kustomization.yaml
Labels: ready-for-review, ok-to-test, let-me-merge-it, size/S, services/cert-manager

#1634 feat: Release DKP-Insights v0.6.0-dev.9
  licenses.d2iq.yaml
  services/dkp-insights-management/0.6.0/defaults/cm.yaml
  services/dkp-insights-management/0.6.0/helmrelease/helmrelease.yaml
  services/dkp-insights/0.6.0/defaults/cm.yaml
  services/dkp-insights/0.6.0/helmrelease/helmrelease.yaml
Labels: ready-for-review, ok-to-test, size/M, services/dkp-insights-management, services/dkp-insights

#1637 chore: Post release bumps
  mergebot-config.json
Labels: ok-to-test, size/XS

#1639 chore: Post release bumps
  mergebot-config.json
Labels: ok-to-test, size/XS

#1630 ci: migrate flux-update-schedule-check to gha
  .github/workflows/flux-update-scheduled-check.yml
Labels: ready-for-review, ok-to-test, size/S

#1647 revert: "ci: change aws role"
  .github/workflows/release.yml
Labels: ready-for-review, ok-to-test, size/XS
