Repository mesosphere/kommander-applications, pull requests merged in 2023-02, with the labels that each got.

#935 build: use downloads.d2iq.com
  .github/workflows/validate-licenses.yaml
  make/release.mk
  make/validate.mk
Labels: ready-for-review, ok-to-test, size/XS

#926 feat: Add Loki pre-install job
  services/grafana-loki/0.48.7/defaults/cm.yaml
  services/grafana-loki/0.48.7/defaults/kustomization.yaml
  services/grafana-loki/0.48.7/grafana-dashboards-logging/kustomization.yaml
  services/grafana-loki/0.48.7/grafana-dashboards-logging/logging-loki-dashboard.json
  services/grafana-loki/0.48.7/grafana-dashboards/grafana-loki.json
  services/grafana-loki/0.48.7/grafana-dashboards/kustomization.yaml
  services/grafana-loki/0.48.7/grafana-dashboards/loki-chunks.json
  services/grafana-loki/0.48.7/grafana-dashboards/loki-deletion.json
  services/grafana-loki/0.48.7/grafana-dashboards/loki-reads-resources.json
  services/grafana-loki/0.48.7/grafana-dashboards/loki-retention.json
  services/grafana-loki/0.48.7/grafana-dashboards/loki-writes-resources.json
  services/grafana-loki/0.48.7/grafana-loki-helmrelease.yaml
  services/grafana-loki/0.48.7/grafana-loki-helmrelease/grafana-loki.yaml
  services/grafana-loki/0.48.7/grafana-loki-pre-install-jobs/pre-install.yaml
  services/grafana-loki/0.48.7/grafana-loki-pre-install.yaml
  services/grafana-loki/0.48.7/kustomization.yaml
  services/project-grafana-loki/0.48.7/defaults/cm.yaml
  services/project-grafana-loki/0.48.7/defaults/kustomization.yaml
  services/project-grafana-loki/0.48.7/grafana-dashboards-logging/kustomization.yaml
  services/project-grafana-loki/0.48.7/grafana-dashboards-logging/logging-loki-dashboard.json
  services/project-grafana-loki/0.48.7/kustomization.yaml
  services/project-grafana-loki/0.48.7/object-bucket-claims.yaml
  services/project-grafana-loki/0.48.7/project-grafana-loki.yaml
  services/rook-ceph-cluster/1.10.10/objectbucketclaims/helmrelease.yaml
Labels: ready-for-review, ok-to-test, do-not-merge/testing, auto-backport, size/L, open-kommander-pr, services/rook-ceph-cluster, services/grafana-loki, services/project-grafana-loki, backport-to-release-2.4

#928 fix: Fix capimate image to be last stable (2.4)
  hack/release/pkg/constants/constants.go
  hack/release/pkg/updatecapimate/updatecapimate_test.go
  services/kommander/0.4.1/defaults/cm.yaml
Labels: ready-for-review, ok-to-test, size/S

#911 feat: Bump gitea to 7.0.2
  licenses.d2iq.yaml
  services/gitea/7.0.2/defaults/cm.yaml
  services/gitea/7.0.2/defaults/kustomization.yaml
  services/gitea/7.0.2/gitea.yaml
  services/gitea/7.0.2/kustomization.yaml
Labels: ok-to-test, size/XS, open-kommander-pr, services/gitea

#939 build: use downloads.d2iq.com (2.3)
  .github/workflows/validate-licenses.yaml
  make/release.mk
  make/validate.mk
Labels: ready-for-review, ok-to-test

#941 build: use downloads.d2iq.com (2.1)
  .github/workflows/validate-licenses.yaml
  make/release.mk
Labels: ready-for-review, ok-to-test

#938 build: use downloads.d2iq.com (2.4)
  .github/workflows/validate-licenses.yaml
  make/release.mk
  make/validate.mk
Labels: ready-for-review, ok-to-test, size/XS

#940 build: use downloads.d2iq.com (2.2)
  .github/workflows/validate-licenses.yaml
  make/release.mk
  make/validate.mk
Labels: ready-for-review, ok-to-test

#944 feat: Remove allowcrossnamespace from traefik configuration
  services/traefik/20.8.0/defaults/cm.yaml
Labels: ready-for-review, ok-to-test

#946 chore: add kommander2-core-installer
  licenses.d2iq.yaml
Labels: ok-to-test, size/XS

#945 feat: Use newly created operator image
  charts/kommander-operator/values.yaml
Labels: ready-for-review, ok-to-test, size/XS

#949 fix: revert s3 bucket name
  make/release.mk
Labels: ok-to-test, size/XS

#953 [release-2.1] fix: revert s3 bucket name (#949)
  make/release.mk
Labels: ready-for-review, ok-to-test

#933 feat: Add Velero pre-install job
  services/velero/3.3.1/defaults/cm.yaml
  services/velero/3.3.1/defaults/kustomization.yaml
  services/velero/3.3.1/grafana-dashboards/kustomization.yaml
  services/velero/3.3.1/grafana-dashboards/velero.json
  services/velero/3.3.1/helmrelease/helmrelease.yaml
  services/velero/3.3.1/kustomization.yaml
  services/velero/3.3.1/pre-install/pre-install-job.yaml
  services/velero/3.3.1/velero-pre-install.yaml
  services/velero/3.3.1/velero.yaml
Labels: ready-for-review, ok-to-test, auto-backport, size/L, services/velero, backport-to-release-2.4

#947 feat: Bump velero to 3.1.2
  .github/workflows/kommander-branch.yaml
  licenses.d2iq.yaml
  services/velero/3.4.0/defaults/cm.yaml
  services/velero/3.4.0/defaults/kustomization.yaml
  services/velero/3.4.0/grafana-dashboards/kustomization.yaml
  services/velero/3.4.0/grafana-dashboards/velero.json
  services/velero/3.4.0/helmrelease/helmrelease.yaml
  services/velero/3.4.0/kustomization.yaml
  services/velero/3.4.0/pre-install/pre-install-job.yaml
  services/velero/3.4.0/velero-pre-install.yaml
  services/velero/3.4.0/velero.yaml
Labels: ready-for-review, ok-to-test, size/M, services/velero

#955 fix: Add necessary permissions to kommander-operator chart
  charts/kommander-operator/templates/deployment.yaml
  charts/kommander-operator/templates/rback_v1_clusterrole_binding_operator_kommander-operator.yaml
  charts/kommander-operator/templates/rback_v1_clusterrole_operator_kommander-operator.yaml
Labels: ok-to-test, size/M

#962 fix: Sum clusterroles instead of ANDing
  charts/kommander-operator/templates/rback_v1_clusterrole_operator_kommander-operator.yaml
Labels: ok-to-test, size/XS

#967 chore: update crd kommandercore
  charts/kommander-operator/crds/crd_kommandercores.yaml
Labels: ok-to-test, size/L

#966 fix: Include charts in kommander applications release
  make/release.mk
Labels: ok-to-test, size/XS

#969 ci: Only run pr labeler on chartbump prs
  .github/workflows/labeler.yaml
Labels: size/XS

#968 feat: wait for ceph operator in ceph cluster preupgrade
  services/rook-ceph-cluster/1.10.10/pre-install.yaml
  services/rook-ceph-cluster/1.10.10/pre-install/ceph-crd-check.yaml
Labels: ready-for-review, ok-to-test, size/M

#964 feat: Automate kommander operator docker images versioning
  charts/kommander-operator/values.yaml
  common/kommander-operator/helmrelease.yaml
  hack/release/pkg/chartversion/chartversion.go
  hack/release/pkg/chartversion/chartversion_test.go
Labels: ok-to-test, size/M

#970 feat: wait for ceph operator in ceph cluster preupgrade (2.4)
  services/rook-ceph-cluster/1.10.8/pre-install.yaml
  services/rook-ceph-cluster/1.10.8/pre-install/ceph-crd-check.yaml
Labels: ready-for-review, ok-to-test, backport-pr

#934 feat: Enable "lazy" connector initialization in dex
  licenses.d2iq.yaml
  services/dex/2.10.0/defaults/cm.yaml
Labels: ready-for-review, ok-to-test, size/XS, services/dex

#963 feat: bump Loki version to 0.48.20
  services/grafana-loki/0.48.20/defaults/cm.yaml
  services/grafana-loki/0.48.20/defaults/kustomization.yaml
  services/grafana-loki/0.48.20/grafana-dashboards-logging/kustomization.yaml
  services/grafana-loki/0.48.20/grafana-dashboards-logging/logging-loki-dashboard.json
  services/grafana-loki/0.48.20/grafana-dashboards/grafana-loki.json
  services/grafana-loki/0.48.20/grafana-dashboards/kustomization.yaml
  services/grafana-loki/0.48.20/grafana-dashboards/loki-chunks.json
  services/grafana-loki/0.48.20/grafana-dashboards/loki-deletion.json
  services/grafana-loki/0.48.20/grafana-dashboards/loki-reads-resources.json
  services/grafana-loki/0.48.20/grafana-dashboards/loki-retention.json
  services/grafana-loki/0.48.20/grafana-dashboards/loki-writes-resources.json
  services/grafana-loki/0.48.20/grafana-loki-helmrelease.yaml
  services/grafana-loki/0.48.20/grafana-loki-helmrelease/grafana-loki.yaml
  services/grafana-loki/0.48.20/grafana-loki-pre-install-jobs/pre-install.yaml
  services/grafana-loki/0.48.20/grafana-loki-pre-install.yaml
  services/grafana-loki/0.48.20/kustomization.yaml
  services/project-grafana-loki/0.48.20/defaults/cm.yaml
  services/project-grafana-loki/0.48.20/defaults/kustomization.yaml
  services/project-grafana-loki/0.48.20/grafana-dashboards-logging/kustomization.yaml
  services/project-grafana-loki/0.48.20/grafana-dashboards-logging/logging-loki-dashboard.json
  services/project-grafana-loki/0.48.20/kustomization.yaml
  services/project-grafana-loki/0.48.20/object-bucket-claims.yaml
  services/project-grafana-loki/0.48.20/project-grafana-loki.yaml
Labels: ready-for-review, ok-to-test, do-not-merge/testing, size/S, open-kommander-pr, services/grafana-loki, services/project-grafana-loki

#971 feat: recategorize istio, kiali, jaeger as platform app, add supported and certified bages
  .github/workflows/kommander-branch.yaml
  services/istio/metadata.yaml
  services/jaeger/metadata.yaml
  services/kiali/metadata.yaml
Labels: ok-to-test, size/S, services/kiali, services/istio, services/jaeger

#978 feat: bump dex to v2.11.0
  services/dex/2.11.0/defaults/cm.yaml
  services/dex/2.11.0/defaults/kustomization.yaml
  services/dex/2.11.0/dex.yaml
  services/dex/2.11.0/kustomization.yaml
Labels: ready-for-review, ok-to-test, size/XS, services/dex

#973 feat: Bump istio to 1.16.2
  licenses.d2iq.yaml
  services/istio/1.16.2/defaults/cm.yaml
  services/istio/1.16.2/defaults/kustomization.yaml
  services/istio/1.16.2/helmrelease.yaml
  services/istio/1.16.2/helmrelease/helmrelease.yaml
  services/istio/1.16.2/kustomization.yaml
Labels: ready-for-review, ok-to-test, size/S, open-kommander-pr, services/istio

#976 feat: Add optional configmap to kommander-operator
  common/kommander-operator/helmrelease.yaml
Labels: ready-for-review, ok-to-test, size/XS

#961 feat: Bump kiali to 1.63.2
  licenses.d2iq.yaml
  services/kiali/1.63.2/defaults/cm.yaml
  services/kiali/1.63.2/defaults/kustomization.yaml
  services/kiali/1.63.2/kiali.yaml
  services/kiali/1.63.2/kustomization.yaml
Labels: ok-to-test, do-not-merge/testing, size/XS, open-kommander-pr, services/kiali

#917 feat: Bump gatekeeper to 3.11.0
  licenses.d2iq.yaml
  services/gatekeeper/3.11.0/constraints.yaml
  services/gatekeeper/3.11.0/constraints/enforce-helmrelease-sa.yaml
  services/gatekeeper/3.11.0/constraints/enforce-kustomization-sa.yaml
  services/gatekeeper/3.11.0/constrainttemplates.yaml
  services/gatekeeper/3.11.0/constrainttemplates/enforce-sa-constrainttemplate.yaml
  services/gatekeeper/3.11.0/defaults/cm.yaml
  services/gatekeeper/3.11.0/defaults/kustomization.yaml
  services/gatekeeper/3.11.0/kustomization.yaml
  services/gatekeeper/3.11.0/release.yaml
  services/gatekeeper/3.11.0/release/kustomization.yaml
  services/gatekeeper/3.11.0/release/release.yaml
  services/gatekeeper/bootstrap/kustomization.yaml
  services/kommander/0.5.0/defaults/cm.yaml
Labels: ready-for-review, ok-to-test, size/M, services/gatekeeper, services/kommander

#956 feat: Bump external-dns to 6.13.2
  services/external-dns/6.13.2/defaults/cm.yaml
  services/external-dns/6.13.2/defaults/kustomization.yaml
  services/external-dns/6.13.2/external-dns.yaml
  services/external-dns/6.13.2/kustomization.yaml
Labels: ready-for-review, ok-to-test, size/XS, open-kommander-pr, services/external-dns

#987 feat: Bump dex to v2.11.1
  licenses.d2iq.yaml
  services/dex/2.11.1/defaults/cm.yaml
  services/dex/2.11.1/defaults/kustomization.yaml
  services/dex/2.11.1/dex.yaml
  services/dex/2.11.1/kustomization.yaml
Labels: ready-for-review, ok-to-test, size/XS, services/dex

#985 feat: Post release bumps
  mergebot-config.json
Labels: size/XS

#986 feat: Post release bumps
  mergebot-config.json
Labels: size/XS

#975 feat: Add post-install job to overwrite velero s3Url
  licenses.d2iq.yaml
  services/traefik/20.8.0/defaults/cm.yaml
  services/velero/3.4.0/defaults/cm.yaml
  services/velero/3.4.0/helmrelease/helmrelease.yaml
  services/velero/3.4.0/kustomization.yaml
  services/velero/3.4.0/post-install/post-install-job.yaml
  services/velero/3.4.0/velero-post-install.yaml
Labels: ready-for-review, ok-to-test, needs-backport, auto-backport, size/L, services/traefik, services/velero, backport-to-release-2.4

#988 fix: patch mutating/validating gatekeeper webhooks
  services/gatekeeper/3.11.0/release/release.yaml
Labels: ready-for-review, ok-to-test, size/S, open-kommander-pr, services/gatekeeper

#989 feat: Add post-install job to overwrite velero s3Url
  licenses.d2iq.yaml
  services/traefik/10.30.1/defaults/cm.yaml
  services/velero/3.3.1/defaults/cm.yaml
  services/velero/3.3.1/helmrelease/helmrelease.yaml
  services/velero/3.3.1/kustomization.yaml
  services/velero/3.3.1/post-install/post-install-job.yaml
  services/velero/3.3.1/velero-post-install.yaml
Labels: ready-for-review, ok-to-test, backport-pr, size/L

#991 feat: Bump kubecost to 0.33.0
  licenses.d2iq.yaml
  services/centralized-kubecost/0.33.0/defaults/cm.yaml
  services/centralized-kubecost/0.33.0/defaults/kustomization.yaml
  services/centralized-kubecost/0.33.0/kustomization.yaml
  services/centralized-kubecost/0.33.0/post-install-jobs.yaml
  services/centralized-kubecost/0.33.0/post-install-jobs/post-install-jobs.yaml
  services/centralized-kubecost/0.33.0/release.yaml
  services/centralized-kubecost/0.33.0/release/release.yaml
  services/kommander/0.5.0/defaults/cm.yaml
  services/kubecost/0.33.0/defaults/cm.yaml
  services/kubecost/0.33.0/defaults/kustomization.yaml
  services/kubecost/0.33.0/kubecost.yaml
  services/kubecost/0.33.0/kustomization.yaml
Labels: ready-for-review, ok-to-test, size/M, services/kommander, services/centralized-kubecost, services/kubecost

#981 feat: bump grafana-loki to 0.69.4
  licenses.d2iq.yaml
  services/grafana-loki/0.69.4/defaults/cm.yaml
  services/grafana-loki/0.69.4/defaults/kustomization.yaml
  services/grafana-loki/0.69.4/grafana-dashboards-logging/kustomization.yaml
  services/grafana-loki/0.69.4/grafana-dashboards-logging/logging-loki-dashboard.json
  services/grafana-loki/0.69.4/grafana-dashboards/grafana-loki.json
  services/grafana-loki/0.69.4/grafana-dashboards/kustomization.yaml
  services/grafana-loki/0.69.4/grafana-dashboards/loki-chunks.json
  services/grafana-loki/0.69.4/grafana-dashboards/loki-deletion.json
  services/grafana-loki/0.69.4/grafana-dashboards/loki-reads-resources.json
  services/grafana-loki/0.69.4/grafana-dashboards/loki-retention.json
  services/grafana-loki/0.69.4/grafana-dashboards/loki-writes-resources.json
  services/grafana-loki/0.69.4/grafana-loki-helmrelease.yaml
  services/grafana-loki/0.69.4/grafana-loki-helmrelease/grafana-loki.yaml
  services/grafana-loki/0.69.4/grafana-loki-pre-install-jobs/pre-install.yaml
  services/grafana-loki/0.69.4/grafana-loki-pre-install.yaml
  services/grafana-loki/0.69.4/kustomization.yaml
  services/project-grafana-loki/0.69.4/defaults/cm.yaml
  services/project-grafana-loki/0.69.4/defaults/kustomization.yaml
  services/project-grafana-loki/0.69.4/grafana-dashboards-logging/kustomization.yaml
  services/project-grafana-loki/0.69.4/grafana-dashboards-logging/logging-loki-dashboard.json
  services/project-grafana-loki/0.69.4/kustomization.yaml
  services/project-grafana-loki/0.69.4/object-bucket-claims.yaml
  services/project-grafana-loki/0.69.4/project-grafana-loki.yaml
Labels: ready-for-review, ok-to-test, size/M, open-kommander-pr, services/grafana-loki, services/project-grafana-loki

#996 feat: Bump reloader to 1.0.5
  licenses.d2iq.yaml
  services/kommander/0.5.0/defaults/cm.yaml
  services/reloader/1.0.5/defaults/cm.yaml
  services/reloader/1.0.5/defaults/kustomization.yaml
  services/reloader/1.0.5/kustomization.yaml
  services/reloader/1.0.5/reloader.yaml
Labels: ready-for-review, ok-to-test, do-not-merge/testing, size/S, open-kommander-pr, services/kommander, services/reloader

#995 feat: Bump jaeger to 2.40.0
  services/jaeger/2.40.0/defaults/cm.yaml
  services/jaeger/2.40.0/defaults/kustomization.yaml
  services/jaeger/2.40.0/helmrelease.yaml
  services/jaeger/2.40.0/helmrelease/release.yaml
  services/jaeger/2.40.0/kustomization.yaml
  services/jaeger/2.40.0/pre-upgrade.yaml
  services/jaeger/2.40.0/pre-upgrade/delete-jaeger-deployment.yaml
Labels: ready-for-review, ok-to-test, size/S, open-kommander-pr, services/jaeger

#980 feat: Bump cert-manager to 1.11.0
  licenses.d2iq.yaml
  services/cert-manager/1.11.0/defaults/cm.yaml
  services/cert-manager/1.11.0/defaults/kustomization.yaml
  services/cert-manager/1.11.0/kustomization.yaml
  services/cert-manager/1.11.0/release.yaml
  services/cert-manager/1.11.0/release/kustomization.yaml
  services/cert-manager/1.11.0/release/release.yaml
  services/cert-manager/1.11.0/root-ca.yaml
  services/cert-manager/1.11.0/root-ca/root-ca.yaml
  services/cert-manager/bootstrap/kustomization.yaml
  services/kommander/0.5.0/defaults/cm.yaml
Labels: ready-for-review, ok-to-test, do-not-merge/testing, size/M, open-kommander-pr, services/kommander, services/cert-manager

#997 feat: Bump rook-ceph to 1.10.11
  licenses.d2iq.yaml
  services/rook-ceph-cluster/1.10.11/defaults/cm.yaml
  services/rook-ceph-cluster/1.10.11/defaults/kustomization.yaml
  services/rook-ceph-cluster/1.10.11/grafana-dashboards/kustomization.yaml
  services/rook-ceph-cluster/1.10.11/grafana-dashboards/rook-ceph-cluster.json
  services/rook-ceph-cluster/1.10.11/grafana-dashboards/rook-ceph-osd.json
  services/rook-ceph-cluster/1.10.11/grafana-dashboards/rook-ceph-pools.json
  services/rook-ceph-cluster/1.10.11/helmrelease/dashboard-cm.yaml
  services/rook-ceph-cluster/1.10.11/helmrelease/helmrelease.yaml
  services/rook-ceph-cluster/1.10.11/helmrelease/kustomization.yaml
  services/rook-ceph-cluster/1.10.11/kustomization.yaml
  services/rook-ceph-cluster/1.10.11/object-bucket-claims.yaml
  services/rook-ceph-cluster/1.10.11/objectbucketclaims/helmrelease.yaml
  services/rook-ceph-cluster/1.10.11/objectbucketclaims/kustomization.yaml
  services/rook-ceph-cluster/1.10.11/pre-install.yaml
  services/rook-ceph-cluster/1.10.11/pre-install/ceph-crd-check.yaml
  services/rook-ceph-cluster/1.10.11/rook-ceph-cluster.yaml
  services/rook-ceph/1.10.11/defaults/cm.yaml
  services/rook-ceph/1.10.11/defaults/kustomization.yaml
  services/rook-ceph/1.10.11/helmrelease/helmrelease.yaml
  services/rook-ceph/1.10.11/helmrelease/kustomization.yaml
  services/rook-ceph/1.10.11/kustomization.yaml
  services/rook-ceph/1.10.11/rook-ceph.yaml
Labels: ok-to-test, size/S, open-kommander-pr, services/rook-ceph-cluster, services/rook-ceph

#1004 feat: Add permission to kommander operator to access git repository
  charts/kommander-operator/templates/rback_v1_clusterrole_operator_kommander-operator.yaml
Labels: ready-for-review, ok-to-test, size/XS

#1003 feat: automate image bump for licenses.d2iq.yaml
  .github/workflows/validate-licenses.yaml
  licenses.d2iq.yaml
Labels: ready-for-review, ok-to-test, size/M

#1007 feat: Update readme for image automation
  README.md
Labels: ready-for-review, size/S

#1013 feat: Add managementApps to kommander default values
  services/kommander/0.5.0/defaults/cm.yaml
Labels: ready-for-review, ok-to-test, size/S, services/kommander

#1012 fix: update validate license to be opt-in
  .github/workflows/validate-licenses.yaml
Labels: ready-for-review, size/S
